# Cronie cron daemon
# Provides scheduled task execution
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.crond;

  # Create system crontab
  systemCrontab = pkgs.writeText "crontab" ''
    # System-wide crontab file
    # Generated by ekaos crond module
    #
    # Format:
    # MIN HOUR DOM MON DOW USER COMMAND
    #
    # Example:
    # 0 2 * * * root /path/to/backup-script.sh

    SHELL=/bin/sh
    PATH=/run/current-system/sw/bin:/bin:/sbin

    # User-defined system cron jobs
    ${cfg.systemCronJobs}
  '';

in

{
  options = {
    services.crond = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to enable the cronie cron daemon.

          This allows scheduling recurring tasks to run at specific times.
        '';
      };

      description = mkOption {
        type = types.str;
        default = "Cronie Cron Daemon";
        description = "Service description";
      };

      command = mkOption {
        type = types.str;
        internal = true;
        description = "Command to run (set automatically)";
      };

      args = mkOption {
        type = types.listOf types.str;
        internal = true;
        default = [ ];
        description = "Command arguments (set automatically)";
      };

      user = mkOption {
        type = types.str;
        default = "root";
        description = "User to run service as";
      };

      restartPolicy = mkOption {
        type = types.str;
        default = "always";
        description = "Restart policy";
      };

      systemd = mkOption {
        type = types.attrsOf types.anything;
        default = { };
        description = "Systemd-specific options";
      };

      systemCronJobs = mkOption {
        type = types.lines;
        default = "";
        example = ''
          # Run backup every day at 2am
          0 2 * * * root /path/to/backup.sh

          # Clean tmp every hour
          0 * * * * root /usr/bin/find /tmp -type f -atime +7 -delete
        '';
        description = ''
          System-wide cron jobs to run.

          These are added to /etc/crontab and run as the specified user.
          Format: MIN HOUR DOM MON DOW USER COMMAND
        '';
      };

      mailto = mkOption {
        type = types.nullOr types.str;
        default = null;
        example = "admin@example.com";
        description = ''
          Email address to send cron output to.

          If null, mail functionality is disabled (-m off).
          To send mail, you need a working mail transfer agent.
        '';
      };
    };
  };

  config = mkIf cfg.enable {
    # Set command and arguments
    services.crond = {
      command = "${pkgs.cronie}/bin/crond";
      args = [
        "-n" # Run in foreground
      ] ++ (if cfg.mailto == null then [ "-m" "off" ] else [ ]);

      # Systemd-specific configuration
      systemd = {
        after = [ "local-fs.target" ];
        wantedBy = [ "multi-user.target" ];
      };
    };

    # Install system crontab
    environment.etc."crontab" = {
      text = readFile systemCrontab;
      mode = "0644";
    };

    # Add cronie to system packages
    environment.systemPackages = [ pkgs.cronie ];

    # PAM configuration for cron
    environment.etc."pam.d/crond".text = ''
      # PAM configuration for crond
      auth      required    pam_env.so
      auth      sufficient  pam_unix.so
      account   required    pam_unix.so
      session   required    pam_loginuid.so
      session   required    pam_limits.so
      session   required    pam_unix.so
    '';

    # Create required directories
    system.activationScripts.crond = stringAfter [ "etc" ] ''
      # Create cron directories
      mkdir -p /etc/cron.d
      mkdir -p /var/spool/cron
      mkdir -p /var/log

      # Set proper permissions
      chmod 755 /etc/cron.d
      chmod 700 /var/spool/cron

      # Create cron log file if it doesn't exist
      touch /var/log/cron.log
      chmod 644 /var/log/cron.log
    '';
  };
}
