# Adios port of ekaos/modules/services/crond.nix.
# TODO(adios-cutover): command/args were internal options set by the legacy
# config; they are computed in impl, not user options.
{ types, pkgs, ... }:

{
  options = {
    enable = {
      type = types.bool;
      default = false;
      description = ''
        Whether to enable the cronie cron daemon.

        This allows scheduling recurring tasks to run at specific times.
      '';
    };

    description = {
      type = types.string;
      default = "Cronie Cron Daemon";
      description = "Service description";
    };

    user = {
      type = types.string;
      default = "root";
      description = "User to run service as";
    };

    restartPolicy = {
      type = types.string;
      default = "always";
      description = "Restart policy";
    };

    systemd = {
      type = types.attrsOf types.any;
      default = { };
      description = "Systemd-specific options";
    };

    systemCronJobs = {
      type = types.string;
      default = "";
      description = ''
        System-wide cron jobs to run.

        These are added to /etc/crontab and run as the specified user.
        Format: MIN HOUR DOM MON DOW USER COMMAND
      '';
    };

    mailto = {
      type = types.nullOr types.string;
      default = null;
      description = ''
        Email address to send cron output to.

        If null, mail functionality is disabled (-m off).
        To send mail, you need a working mail transfer agent.
      '';
    };
  };

  impl =
    { options, ... }:
    if !options.enable then
      { }
    else
      let
        systemCrontab = pkgs.writeText "crontab" ''
          # System-wide crontab file
          # Generated by ekaos crond module
          #
          # Format:
          # MIN HOUR DOM MON DOW USER COMMAND
          #
          # Example:
          # 0 2 * * * root /path/to/backup-script.sh

          SHELL=/bin/sh
          PATH=/run/current-system/sw/bin:/bin:/sbin

          # User-defined system cron jobs
          ${options.systemCronJobs}
        '';
      in
      {
        services.crond = {
          inherit (options)
            enable
            description
            user
            restartPolicy
            ;
          command = "${pkgs.cronie}/bin/crond";
          args = [
            "-n"
          ]
          ++ (
            if options.mailto == null then
              [
                "-m"
                "off"
              ]
            else
              [ ]
          );
          systemd = {
            after = [ "local-fs.target" ];
            wantedBy = [ "multi-user.target" ];
          }
          // options.systemd;
        };

        environment.etc."crontab" = {
          text = builtins.readFile systemCrontab;
          mode = "0644";
        };

        environment.systemPackages = [ pkgs.cronie ];

        environment.etc."pam.d/crond".text = ''
          # PAM configuration for crond
          auth      required    pam_env.so
          auth      sufficient  pam_unix.so
          account   required    pam_unix.so
          session   required    pam_loginuid.so
          session   required    pam_limits.so
          session   required    pam_unix.so
        '';

        # TODO(adios-cutover): legacy ordering (after "etc") lost; plain script.
        system.activationScripts.crond = ''
          # Create cron directories
          mkdir -p /etc/cron.d
          mkdir -p /var/spool/cron
          mkdir -p /var/log

          # Set proper permissions
          chmod 755 /etc/cron.d
          chmod 700 /var/spool/cron

          # Create cron log file if it doesn't exist
          touch /var/log/cron.log
          chmod 644 /var/log/cron.log
        '';
      };
}
