# systemd-journald configuration
# Provides log management and rotation
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.journald;

  # Generate journald.conf
  journaldConf = pkgs.writeText "journald.conf" ''
    # Generated by ekaos journald module
    [Journal]
    ${optionalString (cfg.settings.storage != null) "Storage=${cfg.settings.storage}"}
    ${optionalString (cfg.settings.compress != null)
      "Compress=${if cfg.settings.compress then "yes" else "no"}"
    }
    ${optionalString (cfg.settings.seal != null) "Seal=${if cfg.settings.seal then "yes" else "no"}"}
    ${optionalString (cfg.settings.systemMaxUse != null) "SystemMaxUse=${cfg.settings.systemMaxUse}"}
    ${optionalString (
      cfg.settings.systemKeepFree != null
    ) "SystemKeepFree=${cfg.settings.systemKeepFree}"}
    ${optionalString (
      cfg.settings.systemMaxFileSize != null
    ) "SystemMaxFileSize=${cfg.settings.systemMaxFileSize}"}
    ${optionalString (
      cfg.settings.systemMaxFiles != null
    ) "SystemMaxFiles=${toString cfg.settings.systemMaxFiles}"}
    ${optionalString (cfg.settings.runtimeMaxUse != null) "RuntimeMaxUse=${cfg.settings.runtimeMaxUse}"}
    ${optionalString (
      cfg.settings.runtimeKeepFree != null
    ) "RuntimeKeepFree=${cfg.settings.runtimeKeepFree}"}
    ${optionalString (
      cfg.settings.runtimeMaxFileSize != null
    ) "RuntimeMaxFileSize=${cfg.settings.runtimeMaxFileSize}"}
    ${optionalString (
      cfg.settings.runtimeMaxFiles != null
    ) "RuntimeMaxFiles=${toString cfg.settings.runtimeMaxFiles}"}
    ${optionalString (
      cfg.settings.maxRetentionSec != null
    ) "MaxRetentionSec=${toString cfg.settings.maxRetentionSec}"}
    ${optionalString (cfg.settings.maxFileSec != null) "MaxFileSec=${toString cfg.settings.maxFileSec}"}
    ${optionalString (cfg.settings.forwardToSyslog != null)
      "ForwardToSyslog=${if cfg.settings.forwardToSyslog then "yes" else "no"}"
    }
    ${optionalString (cfg.settings.forwardToKMsg != null)
      "ForwardToKMsg=${if cfg.settings.forwardToKMsg then "yes" else "no"}"
    }
    ${optionalString (cfg.settings.forwardToConsole != null)
      "ForwardToConsole=${if cfg.settings.forwardToConsole then "yes" else "no"}"
    }
    ${optionalString (cfg.settings.rateLimit != null)
      "RateLimitIntervalSec=${toString cfg.settings.rateLimit.intervalSec}\nRateLimitBurst=${toString cfg.settings.rateLimit.burst}"
    }
    ${cfg.settings.extraConfig}
  '';

in

{
  options = {
    services.journald = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = ''
          Whether to enable systemd-journald log management.

          systemd-journald is a system service that collects and stores
          logging data. It creates and maintains structured, indexed journals.
        '';
      };

      settings = mkOption {
        type = types.submodule {
          options = {
            storage = mkOption {
              type = types.nullOr (
                types.enum [
                  "volatile"
                  "persistent"
                  "auto"
                  "none"
                ]
              );
              default = "persistent";
              description = ''
                Where to store journal data.

                - volatile: Store in /run/log/journal (RAM, lost on reboot)
                - persistent: Store in /var/log/journal (survives reboot)
                - auto: Persistent if /var/log/journal exists, volatile otherwise
                - none: Turn off all storage
              '';
            };

            compress = mkOption {
              type = types.nullOr types.bool;
              default = true;
              description = ''
                Whether to compress journal files.

                Reduces disk space usage at the cost of CPU time.
              '';
            };

            seal = mkOption {
              type = types.nullOr types.bool;
              default = true;
              description = ''
                Whether to enable Forward Secure Sealing (FSS).

                Provides cryptographic authentication of journal files.
              '';
            };

            systemMaxUse = mkOption {
              type = types.nullOr types.str;
              default = "1G";
              example = "500M";
              description = ''
                Maximum disk space the journal may use in /var/log/journal.

                Accepts K, M, G, T suffixes. Also accepts percentage (e.g., "15%").
              '';
            };

            systemKeepFree = mkOption {
              type = types.nullOr types.str;
              default = "10%";
              example = "1G";
              description = ''
                How much disk space to keep free in /var/log/journal.

                Journals will be deleted if less than this amount is free.
              '';
            };

            systemMaxFileSize = mkOption {
              type = types.nullOr types.str;
              default = "100M";
              example = "50M";
              description = ''
                Maximum size of individual journal files in /var/log/journal.

                When this size is reached, a new journal file is created.
              '';
            };

            systemMaxFiles = mkOption {
              type = types.nullOr types.int;
              default = 100;
              description = ''
                Maximum number of journal files to keep.

                Older files are deleted when this limit is reached.
              '';
            };

            runtimeMaxUse = mkOption {
              type = types.nullOr types.str;
              default = "100M";
              example = "200M";
              description = ''
                Maximum disk space the journal may use in /run/log/journal.

                This applies to volatile storage only.
              '';
            };

            runtimeKeepFree = mkOption {
              type = types.nullOr types.str;
              default = "10%";
              example = "100M";
              description = ''
                How much disk space to keep free in /run/log/journal.
              '';
            };

            runtimeMaxFileSize = mkOption {
              type = types.nullOr types.str;
              default = "50M";
              description = ''
                Maximum size of individual journal files in /run/log/journal.
              '';
            };

            runtimeMaxFiles = mkOption {
              type = types.nullOr types.int;
              default = 20;
              description = ''
                Maximum number of volatile journal files to keep.
              '';
            };

            maxRetentionSec = mkOption {
              type = types.nullOr types.int;
              default = null;
              example = 2592000; # 30 days
              description = ''
                Maximum time to store journal entries (in seconds).

                Older entries are deleted. If null, no time-based deletion.
              '';
            };

            maxFileSec = mkOption {
              type = types.nullOr types.int;
              default = 86400; # 1 day
              example = 604800; # 1 week
              description = ''
                Maximum time to store entries in a single file (in seconds).

                After this time, a new file is created.
              '';
            };

            forwardToSyslog = mkOption {
              type = types.nullOr types.bool;
              default = false;
              description = ''
                Whether to forward messages to traditional syslog daemon.

                Requires a syslog daemon to be running.
              '';
            };

            forwardToKMsg = mkOption {
              type = types.nullOr types.bool;
              default = false;
              description = ''
                Whether to forward messages to /dev/kmsg (kernel log).
              '';
            };

            forwardToConsole = mkOption {
              type = types.nullOr types.bool;
              default = false;
              description = ''
                Whether to forward messages to the system console.

                Useful for debugging but can be noisy.
              '';
            };

            rateLimit = mkOption {
              type = types.nullOr (
                types.submodule {
                  options = {
                    intervalSec = mkOption {
                      type = types.int;
                      default = 30;
                      description = "Rate limiting interval in seconds.";
                    };

                    burst = mkOption {
                      type = types.int;
                      default = 10000;
                      description = "Maximum messages per interval.";
                    };
                  };
                }
              );
              default = null;
              example = {
                intervalSec = 30;
                burst = 5000;
              };
              description = ''
                Rate limiting configuration.

                Limits the number of messages accepted per time interval.
              '';
            };

            extraConfig = mkOption {
              type = types.lines;
              default = "";
              example = ''
                MaxLevelStore=info
                MaxLevelSyslog=warning
              '';
              description = ''
                Additional configuration lines for journald.conf.

                See journald.conf(5) for available options.
              '';
            };
          };
        };
        default = { };
        description = "journald-specific configuration.";
      };
    };
  };

  config = mkIf cfg.enable {
    # Note: systemd-journald binary is already built into systemd package

    # Install journald configuration
    environment.etc."systemd/journald.conf" = {
      source = journaldConf;
      mode = "0644";
    };

    # Create required directories
    system.activationScripts.journald = stringAfter [ "etc" ] ''
      # Create journal directories based on storage setting
      ${optionalString (cfg.settings.storage == "persistent" || cfg.settings.storage == "auto") ''
        mkdir -p /var/log/journal
        chmod 755 /var/log/journal

        # Create machine ID subdirectory if machine-id exists
        if [ -f /etc/machine-id ]; then
          MACHINE_ID=$(cat /etc/machine-id)
          mkdir -p /var/log/journal/$MACHINE_ID
          chmod 755 /var/log/journal/$MACHINE_ID
        fi
      ''}

      ${optionalString (cfg.settings.storage == "volatile" || cfg.settings.storage == "auto") ''
        mkdir -p /run/log/journal
        chmod 755 /run/log/journal
      ''}
    '';

    # Add assertions
    assertions = [
      {
        assertion = cfg.enable -> config.systemd.package != null;
        message = "systemd-journald requires systemd to be enabled";
      }
      {
        assertion = cfg.settings.forwardToSyslog == true -> false; # We don't have syslog yet
        message = "forwardToSyslog requires a syslog daemon (not yet available)";
      }
    ];
  };
}
