# systemd-timesyncd service
# Provides network time synchronization
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.timesyncd;

  # Generate timesyncd.conf
  timesyncdConf = pkgs.writeText "timesyncd.conf" ''
    # Generated by ekaos timesyncd module
    [Time]
    ${optionalString (cfg.settings.servers != [ ]) "NTP=${concatStringsSep " " cfg.settings.servers}"}
    ${optionalString (
      cfg.settings.fallbackServers != [ ]
    ) "FallbackNTP=${concatStringsSep " " cfg.settings.fallbackServers}"}
    ${optionalString (
      cfg.settings.rootDistanceMaxSec != null
    ) "RootDistanceMaxSec=${toString cfg.settings.rootDistanceMaxSec}"}
    ${optionalString (
      cfg.settings.pollIntervalMinSec != null
    ) "PollIntervalMinSec=${toString cfg.settings.pollIntervalMinSec}"}
    ${optionalString (
      cfg.settings.pollIntervalMaxSec != null
    ) "PollIntervalMaxSec=${toString cfg.settings.pollIntervalMaxSec}"}
  '';

in

{
  options = {
    services.timesyncd = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to enable systemd-timesyncd for time synchronization.

          systemd-timesyncd is a lightweight SNTP client that synchronizes
          the system clock with remote NTP servers.
        '';
      };

      description = mkOption {
        type = types.str;
        default = "Network Time Synchronization";
        description = "Service description";
      };

      command = mkOption {
        type = types.str;
        internal = true;
        description = "Command to run (set automatically)";
      };

      args = mkOption {
        type = types.listOf types.str;
        internal = true;
        default = [ ];
        description = "Command arguments (set automatically)";
      };

      user = mkOption {
        type = types.str;
        default = "systemd-timesync";
        description = "User to run service as";
      };

      restartPolicy = mkOption {
        type = types.str;
        default = "always";
        description = "Restart policy";
      };

      systemd = mkOption {
        type = types.attrsOf types.anything;
        default = { };
        description = "Systemd-specific options";
      };

      settings = mkOption {
        type = types.submodule {
          options = {
            servers = mkOption {
              type = types.listOf types.str;
              default = [
                "0.nixos.pool.ntp.org"
                "1.nixos.pool.ntp.org"
                "2.nixos.pool.ntp.org"
                "3.nixos.pool.ntp.org"
              ];
              example = [
                "0.pool.ntp.org"
                "1.pool.ntp.org"
                "time.nist.gov"
              ];
              description = ''
                List of NTP servers to use for time synchronization.

                These are tried in order when synchronizing time.
              '';
            };

            fallbackServers = mkOption {
              type = types.listOf types.str;
              default = [
                "0.pool.ntp.org"
                "1.pool.ntp.org"
              ];
              description = ''
                Fallback NTP servers to use if primary servers are unreachable.
              '';
            };

            rootDistanceMaxSec = mkOption {
              type = types.nullOr types.int;
              default = 5;
              description = ''
                Maximum acceptable root distance in seconds.

                Sets the maximum synchronization distance from the reference clock.
              '';
            };

            pollIntervalMinSec = mkOption {
              type = types.nullOr types.int;
              default = 32;
              description = ''
                Minimum poll interval in seconds.

                Minimum time between NTP requests.
              '';
            };

            pollIntervalMaxSec = mkOption {
              type = types.nullOr types.int;
              default = 2048;
              description = ''
                Maximum poll interval in seconds.

                Maximum time between NTP requests when clock is stable.
              '';
            };
          };
        };
        default = { };
        description = "timesyncd-specific configuration.";
      };
    };
  };

  config = mkIf cfg.enable {
    # Note: systemd-timesyncd binary is already built into systemd package

    # Set command and arguments (systemd-timesyncd is started by systemd itself)
    services.timesyncd = {
      command = "${config.systemd.package}/lib/systemd/systemd-timesyncd";
      args = [ ];

      # Systemd-specific configuration
      systemd = {
        description = "Network Time Synchronization";
        wantedBy = [ "sysinit.target" ];
        wants = [ "time-sync.target" ];
        before = [
          "time-sync.target"
          "sysinit.target"
        ];
        after = [ "systemd-remount-fs.service" ];
        conflicts = [ "shutdown.target" ];
        conditionVirtualization = "!container";
        conditionCapability = "CAP_SYS_TIME";
      };
    };

    # Install timesyncd configuration
    environment.etc."systemd/timesyncd.conf" = {
      source = timesyncdConf;
      mode = "0644";
    };

    # Create state directory
    system.activationScripts.timesyncd = stringAfter [ "etc" ] ''
      # Create timesyncd state directory
      mkdir -p /var/lib/systemd/timesync
      chmod 755 /var/lib/systemd/timesync

      # Create timesync user if it doesn't exist
      if ! getent passwd systemd-timesync >/dev/null 2>&1; then
        useradd -r -s /sbin/nologin -d /var/lib/systemd/timesync \
          -c "systemd Time Synchronization" systemd-timesync || true
      fi

      # Set ownership
      chown -R systemd-timesync:systemd-timesync /var/lib/systemd/timesync || true
    '';

    # Add assertions
    assertions = [
      {
        assertion = cfg.enable -> config.systemd.package != null;
        message = "systemd-timesyncd requires systemd to be enabled";
      }
    ];
  };
}
