# Adios port of ekaos/modules/services/timesyncd.nix.
# TODO(adios-cutover): command/args were internal options set by the legacy
# config; they are computed in impl, not user options.
{ types, pkgs, ... }:

{
  options = {
    enable = {
      type = types.bool;
      default = false;
      description = ''
        Whether to enable systemd-timesyncd for time synchronization.

        systemd-timesyncd is a lightweight SNTP client that synchronizes
        the system clock with remote NTP servers.
      '';
    };

    description = {
      type = types.string;
      default = "Network Time Synchronization";
      description = "Service description";
    };

    user = {
      type = types.string;
      default = "systemd-timesync";
      description = "User to run service as";
    };

    restartPolicy = {
      type = types.string;
      default = "always";
      description = "Restart policy";
    };

    systemd = {
      type = types.attrsOf types.any;
      default = { };
      description = "Systemd-specific options";
    };

    settings = {
      options = {
        servers = {
          type = types.listOf types.string;
          default = [
            "0.nixos.pool.ntp.org"
            "1.nixos.pool.ntp.org"
            "2.nixos.pool.ntp.org"
            "3.nixos.pool.ntp.org"
          ];
          description = ''
            List of NTP servers to use for time synchronization.

            These are tried in order when synchronizing time.
          '';
        };

        fallbackServers = {
          type = types.listOf types.string;
          default = [
            "0.pool.ntp.org"
            "1.pool.ntp.org"
          ];
          description = ''
            Fallback NTP servers to use if primary servers are unreachable.
          '';
        };

        rootDistanceMaxSec = {
          type = types.nullOr types.int;
          default = 5;
          description = ''
            Maximum acceptable root distance in seconds.

            Sets the maximum synchronization distance from the reference clock.
          '';
        };

        pollIntervalMinSec = {
          type = types.nullOr types.int;
          default = 32;
          description = ''
            Minimum poll interval in seconds.

            Minimum time between NTP requests.
          '';
        };

        pollIntervalMaxSec = {
          type = types.nullOr types.int;
          default = 2048;
          description = ''
            Maximum poll interval in seconds.

            Maximum time between NTP requests when clock is stable.
          '';
        };
      };
      description = "timesyncd-specific configuration.";
    };
  };

  inputs = {
    # TODO(adios-cutover): verify leaf path once the service-managers batch
    # lands (legacy reads config.systemd.package).
    systemd.from = { root }: root."service-managers".systemd;
  };

  assertions = [
    {
      verify = { options, inputs }: !options.enable || inputs.systemd.package != null;
      explain = { options, inputs }: "systemd-timesyncd requires systemd to be enabled";
    }
  ];

  impl =
    { options, inputs }:
    if !options.enable then
      { }
    else
      let
        s = options.settings;
      in
      {
        services.timesyncd = {
          inherit (options)
            enable
            description
            user
            restartPolicy
            ;
          command = "${inputs.systemd.package}/lib/systemd/systemd-timesyncd";
          args = [ ];
          systemd = {
            description = "Network Time Synchronization";
            wantedBy = [ "sysinit.target" ];
            wants = [ "time-sync.target" ];
            before = [
              "time-sync.target"
              "sysinit.target"
            ];
            after = [ "systemd-remount-fs.service" ];
            conflicts = [ "shutdown.target" ];
            conditionVirtualization = "!container";
            conditionCapability = "CAP_SYS_TIME";
          }
          // options.systemd;
        };

        environment.etc."systemd/timesyncd.conf" = {
          source = pkgs.writeText "timesyncd.conf" ''
            # Generated by ekaos timesyncd module
            [Time]
            ${if (s.servers or [ ]) != [ ] then "NTP=${builtins.concatStringsSep " " s.servers}" else ""}
            ${
              if (s.fallbackServers or [ ]) != [ ] then
                "FallbackNTP=${builtins.concatStringsSep " " s.fallbackServers}"
              else
                ""
            }
            ${
              if (s.rootDistanceMaxSec or null) != null then
                "RootDistanceMaxSec=${toString s.rootDistanceMaxSec}"
              else
                ""
            }
            ${
              if (s.pollIntervalMinSec or null) != null then
                "PollIntervalMinSec=${toString s.pollIntervalMinSec}"
              else
                ""
            }
            ${
              if (s.pollIntervalMaxSec or null) != null then
                "PollIntervalMaxSec=${toString s.pollIntervalMaxSec}"
              else
                ""
            }
          '';
          mode = "0644";
        };

        # TODO(adios-cutover): legacy ordering (after "etc") lost; plain script.
        system.activationScripts.timesyncd = ''
          # Create timesyncd state directory
          mkdir -p /var/lib/systemd/timesync
          chmod 755 /var/lib/systemd/timesync

          # Create timesync user if it doesn't exist
          if ! getent passwd systemd-timesync >/dev/null 2>&1; then
            useradd -r -s /sbin/nologin -d /var/lib/systemd/timesync \
              -c "systemd Time Synchronization" systemd-timesync || true
          fi

          # Set ownership
          chown -R systemd-timesync:systemd-timesync /var/lib/systemd/timesync || true
        '';
      };
}
