{
  lib,
  stdenv,
  fetchFromGitLab,
  fetchpatch,
  buildPackages,
  gettext,
  pkg-config,
  python3,
  # TODO(corepkgs): Port avahi for network scanner discovery
  # avahi,
  # TODO(corepkgs): Port libgphoto2 for camera support
  # libgphoto2,
  libjpeg,
  libpng,
  libtiff,
  libusb1,
  # TODO(corepkgs): Port libv4l for video4linux support
  # libv4l,
  # TODO(corepkgs): Port net-snmp for SNMP scanner support
  # net-snmp,
  curl,
  systemdLibs,
  withSystemd ? lib.meta.availableOn stdenv.hostPlatform systemdLibs,
  libxml2,
  poppler,
  gawk,
  autoconf,
  automake,
  libtool,
  autoconf-archive,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "sane-backends";
  version = "1.4.0";

  src = fetchFromGitLab {
    owner = "sane-project";
    repo = "backends";
    tag = finalAttrs.version;
    hash = "sha256-e7Wjda+CobYatblvVCGkMAO2aWrdSCp7q+qIEGnGDCY=";
  };

  patches = [
    # Fix hangs in tests
    # FIXME: remove in next release
    (fetchpatch {
      url = "https://gitlab.com/sane-project/backends/-/commit/8acc267d5f4049d8438456821137ae56e91baea9.patch";
      hash = "sha256-IyupDeH1MPvEBnGaUzBbCu106Gp7zXxlPGFAaiiINQI=";
    })
    # Fix multipages scanning
    # https://gitlab.com/sane-project/backends/-/merge_requests/883
    (fetchpatch {
      url = "https://gitlab.com/sane-project/backends/-/commit/fbf80b0fc1d262ed40d4b49dd53c14707083ef60.patch";
      hash = "sha256-9KKTr7p1vCgvGr6hFY83K5gbL7Ilm4Uzc86JIxv+ahI=";
      revert = true;
    })
    # Fix build with C23 compilers where false/true are keywords
    (fetchpatch {
      url = "https://gitlab.com/sane-project/backends/-/commit/90815a9f2576c2428287a500cab6caeddb80f9a8.patch";
      hash = "sha256-RwFkjPMGFvk7jXMaEHv/B+mjkAIbMDJma5dJpn/FXqY=";
    })
    (fetchpatch {
      url = "https://gitlab.com/sane-project/backends/-/commit/c9bf95744ae3c32c31202dea3327064c0d121444.patch";
      hash = "sha256-8/dOHp8uOnYHy00jxlMaAHO5oGrljWcVaqmSJMO1uRw=";
    })
  ];

  postPatch = ''
    # Do not create lock dir in install phase
    sed -i '/^install-lockpath:/!b;n;c\       # pass' backend/Makefile.am
  '';

  preConfigure = ''
    # create version files, so that autotools macros can use them:
    # https://gitlab.com/sane-project/backends/-/issues/440
    printf "%s\n" "$version" > .tarball-version
    printf "%s\n" "$version" > .version

    autoreconf -fiv

    # Fixes for cross compilation
    # https://github.com/NixOS/nixpkgs/issues/308283
    patch -p1 -i ${./sane-desc-cross.patch}
  '';

  outputs = [
    "out"
    "doc"
    "man"
  ];

  depsBuildBuild = [ buildPackages.stdenv.cc ];

  nativeBuildInputs = [
    autoconf
    autoconf-archive
    automake
    gettext
    libtool
    pkg-config
    python3
  ];

  buildInputs = [
    libjpeg
    libpng
    libtiff
    libusb1
    curl
    libxml2
    poppler
    gawk
  ]
  ++ lib.optionals stdenv.hostPlatform.isLinux [
    # TODO(corepkgs): Port libieee1284 for parallel port scanner support
    # libieee1284
    # TODO(corepkgs): Port libv4l for video4linux support
    # libv4l
    # TODO(corepkgs): Port net-snmp for SNMP scanner support
    # net-snmp
  ]
  ++ lib.optionals withSystemd [
    systemdLibs
  ];

  enableParallelBuilding = true;

  configureFlags = [
    "--with-lockdir=/var/lock/sane"
    "--with-usb"
  ];

  # Fix GCC 14 build failure: -Warray-bounds in plustek-pp_wrapper.c
  env.NIX_CFLAGS_COMPILE = "-Wno-error=array-bounds";

  # autoconf check for HAVE_MMAP is never set on cross compilation.
  # The pieusb backend fails compilation if HAVE_MMAP is not set.
  buildFlags = lib.optionals (stdenv.hostPlatform != stdenv.buildPlatform) [
    "CFLAGS=-DHAVE_MMAP=${if stdenv.hostPlatform.isLinux then "1" else "0"}"
  ];

  postInstall = ''
    mkdir -p $out/etc/udev/rules.d/ $out/etc/udev/hwdb.d
    ./tools/sane-desc -m udev+hwdb -s doc/descriptions:doc/descriptions-external > $out/etc/udev/rules.d/49-libsane.rules
    ./tools/sane-desc -m udev+hwdb -s doc/descriptions:doc/descriptions-external -m hwdb > $out/etc/udev/hwdb.d/20-sane.hwdb

    # net.conf conflicts with the file generated by service modules
    rm $out/etc/sane.d/net.conf
  '';

  # parallel install creates a bad symlink at $out/lib/sane/libsane.so.1 which prevents finding plugins
  # https://github.com/NixOS/nixpkgs/issues/224569
  enableParallelInstalling = false;

  doInstallCheck = true;

  meta = {
    description = "SANE (Scanner Access Now Easy) backends";
    longDescription = ''
      Collection of open-source SANE backends (device drivers).
      SANE is a universal scanner interface providing standardized access to
      any raster image scanner hardware: flatbed scanners, hand-held scanners,
      video- and still-cameras, frame-grabbers, etc. For a list of supported
      scanners, see http://www.sane-project.org/sane-backends.html.
    '';
    homepage = "http://www.sane-project.org/";
    license = lib.licenses.gpl2Plus;
    platforms = lib.platforms.linux ++ lib.platforms.darwin;
  };
})
