# Adios port of ekaos/modules/boot/modprobe.nix.
# TODO(adios-cutover) notes below mark semantics changed in translation.
{
  types,
  lib,
  pkgs,
  ...
}:

{
  options = {
    # Legacy path: boot.blacklistedKernelModules.
    blacklistedKernelModules = {
      type = types.listOf types.string;
      default = [ ];
      example = [
        "nouveau"
        "pcspkr"
        "snd_pcsp"
      ];
      description = ''
        Kernel modules that should never be loaded automatically.
        These are blacklisted in /etc/modprobe.d/blacklist.conf.
      '';
    };

    # Legacy path: boot.extraModprobeConfig.
    extraModprobeConfig = {
      type = types.string;
      default = "";
      example = ''
        options snd_hda_intel power_save=1
        options iwlwifi power_save=1
      '';
      description = ''
        Extra configuration appended to /etc/modprobe.d/ekaos.conf.
        Used for module options and aliases. See modprobe.d(5).
      '';
    };
  };

  impl =
    { options, ... }:
    lib.merge.attrs.recursively {
      mutators = [
        {
          environment.systemPackages = [ pkgs.kmod ];
          # TODO(adios-cutover): stringAfter [ "etc" ] ordering dropped.
          system.activationScripts.modprobe = ''
            # Set kernel modprobe path
            if [ -w /proc/sys/kernel/modprobe ]; then
              echo ${pkgs.kmod}/bin/modprobe > /proc/sys/kernel/modprobe
            fi
          '';
        }

        (
          if options.blacklistedKernelModules != [ ] || options.extraModprobeConfig != "" then
            {
              environment.etc."modprobe.d/ekaos.conf".text = ''
                # Generated by ekaos modprobe module
                ${builtins.concatStringsSep "\n" (
                  builtins.map (mod: "blacklist ${mod}") options.blacklistedKernelModules
                )}
                ${options.extraModprobeConfig}
              '';
            }
          else
            { }
        )
      ];
    };
}
