# Kernel module loading configuration
# Manages modprobe.d configuration and kernel module blacklisting
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

{
  options = {
    boot.blacklistedKernelModules = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [
        "nouveau"
        "pcspkr"
        "snd_pcsp"
      ];
      description = ''
        Kernel modules that should never be loaded automatically.
        These are blacklisted in /etc/modprobe.d/blacklist.conf.
      '';
    };

    boot.extraModprobeConfig = mkOption {
      type = types.lines;
      default = "";
      example = ''
        options snd_hda_intel power_save=1
        options iwlwifi power_save=1
      '';
      description = ''
        Extra configuration appended to /etc/modprobe.d/ekaos.conf.
        Used for module options and aliases. See modprobe.d(5).
      '';
    };
  };

  config = mkMerge [
    # Always install kmod for modprobe
    {
      environment.systemPackages = [ pkgs.kmod ];
    }

    # Generate modprobe.d config when blacklist or extra config is set
    (mkIf (config.boot.blacklistedKernelModules != [ ] || config.boot.extraModprobeConfig != "") {
      environment.etc."modprobe.d/ekaos.conf".text = ''
        # Generated by ekaos modprobe module
        ${concatMapStringsSep "\n" (mod: "blacklist ${mod}") config.boot.blacklistedKernelModules}
        ${config.boot.extraModprobeConfig}
      '';
    })

    # Point the kernel to our modprobe
    {
      system.activationScripts.modprobe = stringAfter [ "etc" ] ''
        # Set kernel modprobe path
        if [ -w /proc/sys/kernel/modprobe ]; then
          echo ${pkgs.kmod}/bin/modprobe > /proc/sys/kernel/modprobe
        fi
      '';
    }
  ];
}
