# Adios port of ekaos/modules/boot/swraid.nix.
# TODO(adios-cutover) notes below mark semantics changed in translation.
{
  types,
  lib,
  pkgs,
  ...
}:

{
  options = {
    enable = {
      type = types.bool;
      default = false;
      description = ''
        Whether to enable software RAID (mdadm) support.

        When enabled, mdadm tools are available and RAID kernel
        modules are loaded.
      '';
    };

    mdadmConf = {
      type = types.string;
      default = "";
      example = ''
        MAILADDR root
        ARRAY /dev/md0 UUID=12345678:12345678:12345678:12345678
      '';
      description = ''
        Contents of /etc/mdadm.conf.
      '';
    };
  };

  impl =
    { options, ... }:
    if !options.enable then
      { }
    else
      lib.merge.attrs.recursively {
        mutators = [
          {
            environment.systemPackages = [ pkgs.mdadm ];

            boot.kernelModules = [
              "md_mod"
              "raid0"
              "raid1"
              "raid10"
              "raid456"
            ];

            boot.initrd.kernelModules = [
              "md_mod"
              "raid0"
              "raid1"
              "raid10"
              "raid456"
            ];

            # TODO(adios-cutover): stringAfter [ "etc" ] ordering dropped.
            system.activationScripts.swraid = ''
              if [ -e /etc/mdadm.conf ]; then
                echo "Assembling RAID arrays..."
                ${pkgs.mdadm}/bin/mdadm --assemble --scan || true
              fi
            '';
          }

          (
            if options.mdadmConf != "" then
              {
                environment.etc."mdadm.conf".text = ''
                  # Generated by ekaos
                  ${options.mdadmConf}
                '';
              }
            else
              { }
          )
        ];
      };
}
