# Software RAID (mdadm) support
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.boot.swraid;
in

{
  options = {
    boot.swraid = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to enable software RAID (mdadm) support.

          When enabled, mdadm tools are available and RAID kernel
          modules are loaded.
        '';
      };

      mdadmConf = mkOption {
        type = types.lines;
        default = "";
        example = ''
          MAILADDR root
          ARRAY /dev/md0 UUID=12345678:12345678:12345678:12345678
        '';
        description = ''
          Contents of /etc/mdadm.conf.
        '';
      };
    };
  };

  config = mkIf cfg.enable {
    environment.systemPackages = [ pkgs.mdadm ];

    boot.kernelModules = [
      "md_mod"
      "raid0"
      "raid1"
      "raid10"
      "raid456"
    ];

    # Include RAID modules in initrd if enabled
    boot.initrd.kernelModules = [
      "md_mod"
      "raid0"
      "raid1"
      "raid10"
      "raid456"
    ];

    environment.etc."mdadm.conf" = mkIf (cfg.mdadmConf != "") {
      text = ''
        # Generated by ekaos
        ${cfg.mdadmConf}
      '';
    };

    # Assemble arrays at boot
    system.activationScripts.swraid = stringAfter [ "etc" ] ''
      if [ -e /etc/mdadm.conf ]; then
        echo "Assembling RAID arrays..."
        ${pkgs.mdadm}/bin/mdadm --assemble --scan || true
      fi
    '';
  };
}
