"""Declarative configuration for the nixpkgs sync.

Nothing here executes logic; every entry is data consumed by the other modules.
Keeping it separate means a reviewer can audit *what* is synced without reading
*how* it is synced.
"""

# Where generated patches are written, relative to the corepkgs root.
PATCHES_DIR = "patches"

# Where accepted divergence is recorded, relative to the corepkgs root. Both
# directories are gitignored: they are a local review aid, not repo content.
ACCEPTED_DIR = ".sync-accepted"

# Reports live under the patches directory, prefixed so they never collide with
# a generated patch path.
REPORTS_DIR = "_reports"

# Files whose contents are never diffed. A patch inside a patch is unreadable
# and cannot be applied, so these are reported as a one-line note instead.
OPAQUE_SUFFIXES = (".patch", ".diff")

# corepkgs path prefix -> nixpkgs path prefix. Longest prefix wins.
PATH_MAPPINGS = {
    # keep-sorted start
    "build-support": "pkgs/build-support",
    "common-updater": "pkgs/common-updater",
    "perl/buildperlpackage.nix": "pkgs/development/perl-modules/generic",
    "perl/patches": "pkgs/development/perl-modules",
    "perl/perl-packages.nix": "pkgs/top-level/perl-packages.nix",
    "pkgs": "pkgs/by-name",
    "pkgs/automake": "pkgs/development/tools/misc/automake",
    "pkgs/bash": "pkgs/shells/bash",
    "pkgs/binutils": "pkgs/development/tools/misc/binutils",
    "pkgs/boost": "pkgs/development/libraries/boost",
    "pkgs/dotnet": "pkgs/development/compilers/dotnet",
    "pkgs/gcc": "pkgs/development/compilers/gcc",
    "pkgs/glibc": "pkgs/development/libraries/glibc",
    "pkgs/gobject-introspection": "pkgs/development/libraries/gobject-introspection",
    "pkgs/javaPackages/openjdk": "pkgs/development/compilers/openjdk",
    "pkgs/linux": "pkgs/os-specific/linux",
    "pkgs/linux/default.nix": "pkgs/top-level/linux-kernels.nix",
    "pkgs/linux/kernel/kernel-config.nix": "nixos/modules/system/boot/kernel_config.nix",
    "pkgs/linux/pkgs": "pkgs/os-specific/linux",
    "pkgs/llvm": "pkgs/development/compilers/llvm",
    "pkgs/nix": "pkgs/tools/package-management/nix",
    "pkgs/openssh": "pkgs/tools/networking/openssh",
    "pkgs/perl": "pkgs/development/interpreters/perl",
    "pkgs/rust": "pkgs/development/compilers/rust",
    "pkgs/systemd": "pkgs/os-specific/linux/systemd",
    "pkgs/texlive": "pkgs/tools/typesetting/tex/texlive",
    "pkgs/xorg": "pkgs/servers/x11/xorg",
    "python": "pkgs/development/interpreters/python",
    "python/pkgs": "pkgs/development/python-modules",
    "release.nix": "pkgs/top-level/release.nix",
    "stdenv": "pkgs/stdenv",
    "stdenv/config.nix": "pkgs/top-level/config.nix",
    "stdenv/impure.nix": "pkgs/top-level/impure.nix",
    "stdenv/pure.nix": "pkgs/top-level/default.nix",
    "stdenv/release/lib.nix": "pkgs/top-level/release-lib.nix",
    "stdenv/splice.nix": "pkgs/top-level/splice.nix",
    "stdenv/stage.nix": "pkgs/top-level/stage.nix",
    "stdenv/variants.nix": "pkgs/top-level/variants.nix",
    "systems": "lib/systems",
    "unixtools.nix": "pkgs/top-level/unixtools.nix",
    # keep-sorted end
}

# The nixpkgs prefix that uses the by-name layout (two-letter shard directory
# and `package.nix` rather than `default.nix`).
BY_NAME_PREFIX = "pkgs/by-name"

# Relative-path rewrites applied to nixpkgs content. nixpkgs refers to files by
# their location in its own tree; these express the same reference in corepkgs
# terms. Applied in order, so the specific entries must precede the general one.
PATH_REWRITES = [
    (r"\.\./development/perl-modules/generic", "./buildPerlPackage.nix"),
    (r"\.\./development/perl-modules/([^/]+\.patch)", r"./patches/\1"),
    (r"\.\./development/perl-modules", "./patches"),
    (r"\.\./os-specific/linux/", "./"),
]

# Attribute names that corepkgs spells differently from nixpkgs. Applied
# unconditionally: a rename is either correct for this repo or it is not, and
# making it depend on the target file's contents only hides mistakes.
VOCABULARY = [
    (r"\blibX11\b", "libx11"),
    (r"\bdocbook_xsl\b", "docbook-xsl-nons"),
    (r"\bdocbook_xsl_ns\b", "docbook-xsl-ns"),
    (r"\bnixpkgsArgs\b", "pkgsArgs"),
    (r"\bautoconf269\b", "autoconf.v2_69"),
    (r"\bautoconf271\b", "autoconf.v2_71"),
    (r"\bcmakeMinimal\b", "cmake.minimal"),
]

# `meta` bindings dropped from incoming nixpkgs content. corepkgs is curated as
# a set and does not carry these, so importing them would be noise in every
# single patch.
DROPPED_META_BINDINGS = (
    "maintainers",
    "nonTeamMaintainers",
    "teams",
)

# Directories never compared, relative to the corepkgs root.
IGNORE_DIRS = [
    # keep-sorted start
    ".github",
    "config",
    "docs",
    "patches",  # generated by this tool
    "perl",  # too many changes, update manually
    "pkgs-many",
    "pkgs/lndir",  # our minimal implementation
    "scripts",
    "stdenv/cygwin",
    "stdenv/darwin",
    "stdenv/freebsd",
    "stdenv/linux/bootstrap-files",  # lets wait for minimal-bootstrap
    # keep-sorted end
]

# Individual files never compared, matched as exact paths from the corepkgs root.
IGNORE_FILES = [
    # keep-sorted start
    ".gitignore",
    "LICENSE",
    "README.md",
    "default.nix",
    "flake.lock",
    "flake.nix",
    "lib.nix",
    "pins.nix",
    "stdenv/README.md",
    "stdenv/aliases.nix",  # we have our own aliases
    "top-level.nix",
    # keep-sorted end
]

# Under these prefixes every file in a subdirectory is collected into a single
# patch named after that subdirectory, so one package reviews as one patch.
GROUPED_DIRS = [
    # keep-sorted start
    "build-support",
    "common-updater",
    "os-specific/linux",
    "pkgs",
    "systems",
    # keep-sorted end
]
