"""Patch construction.

A generated patch is a plain unified diff from the real corepkgs file to the
normalised nixpkgs file. There is deliberately no post-processing of diff output:
hunk headers come straight from difflib and are therefore correct, and the patch
applies from the corepkgs root with `git apply -p1`.
"""

import difflib
from dataclasses import dataclass
from typing import Optional

from . import normalize

HEADER_PREFIX = "#"


@dataclass(frozen=True)
class Comparison:
    """One corepkgs file measured against its nixpkgs counterpart."""

    path: str
    """corepkgs-relative path, used verbatim in the diff headers."""

    upstream_path: str
    """nixpkgs-relative path this was compared against, for the reader's benefit."""

    diff: Optional[str] = None
    """Unified diff text, or None when the file matches upstream."""

    opaque: bool = False
    """True when the file was not diffed because its contents are a patch."""

    differs: bool = False
    """True when an opaque file's contents differ from upstream."""


def _terminate(line: str) -> str:
    """Give a diff line its trailing newline, flagging a file that lacks one.

    Splitting with `keepends` preserves whether the final line of a file ended
    in a newline. `diff` records that absence with a `\\ No newline` marker, and
    `git apply` needs it to reproduce the file byte-for-byte.
    """
    if line.endswith("\n"):
        return line
    return line + "\n\\ No newline at end of file\n"


def compare(
    path: str,
    upstream_path: str,
    local_text: str,
    upstream_text: str,
    vocabulary: normalize.Vocabulary,
) -> Comparison:
    """Diff one file pair, normalising only the upstream side."""
    normalized = normalize.upstream(upstream_text, vocabulary)
    if normalized == local_text:
        return Comparison(path=path, upstream_path=upstream_path)

    diff = difflib.unified_diff(
        local_text.splitlines(keepends=True),
        normalized.splitlines(keepends=True),
        fromfile=f"a/{path}",
        tofile=f"b/{path}",
    )
    body = "".join(_terminate(line) for line in diff)
    if not body:
        return Comparison(path=path, upstream_path=upstream_path)
    return Comparison(path=path, upstream_path=upstream_path, diff=body)


def compare_opaque(path: str, upstream_path: str, differs: bool) -> Comparison:
    """Record a patch/diff file without diffing it.

    Diffing a patch against a patch yields output no tool can apply and no human
    can read, so the file is reported as a single note instead.
    """
    return Comparison(path=path, upstream_path=upstream_path, opaque=True, differs=differs)


def render(target: str, comparisons: list[Comparison]) -> Optional[str]:
    """Assemble one patch file, or None when nothing diverges.

    Notes about opaque files are collected into a comment header ahead of the
    diff sections, so the appliable part of the file stays contiguous.
    """
    notes = [c for c in comparisons if c.opaque and c.differs]
    diffs = [c for c in comparisons if c.diff]
    if not notes and not diffs:
        return None

    header = [
        f"{HEADER_PREFIX} Generated by scripts/sync-with-nixpkgs -- do not edit.",
        f"{HEADER_PREFIX} Divergence of {target} from nixpkgs.",
    ]
    if notes:
        header.append(HEADER_PREFIX)
        header.append(f"{HEADER_PREFIX} Patch files, replaced by this note rather than diffed:")
        for note in notes:
            header.append(f"{HEADER_PREFIX}   {note.path} <- {note.upstream_path}")
    header.append(HEADER_PREFIX)

    return "\n".join(header) + "\n" + "".join(c.diff for c in diffs)
