# Per-user bash configuration
#
# Extends home.users.<name> with bash-specific options and composes
# a .bashrc from sessionVariables, sessionPath, shellAliases, and
# bash.initExtra.
#
# Usage:
#   home.users.alice.programs.bash = {
#     enable = true;
#     initExtra = ''
#       eval "$(direnv hook bash)"
#       bind '"\e[A": history-search-backward'
#     '';
#     profileExtra = ''
#       export GPG_TTY=$(tty)
#     '';
#   };
{ lib, ... }:

let
  inherit (lib)
    mkOption
    mkEnableOption
    mkIf
    types
    concatStringsSep
    mapAttrsToList
    escapeShellArg
    optional
    optionalString
    literalExpression
    ;

  bashOpts =
    { config, ... }:
    let
      cfg = config.programs.bash;

      # Compose the bashrc from all parts
      bashrcContent = concatStringsSep "\n" (
        [ "# Generated by ekaos home configuration. Do not edit." ]
        ++ [ "" ]

        # Source session variables from ekaos state dir
        ++ [
          ''
            # Source ekaos session variables (PATH, exports, aliases)
            if [ -f "$HOME/.config/ekaos/session-vars.sh" ]; then
              . "$HOME/.config/ekaos/session-vars.sh"
            fi
          ''
        ]

        # History settings
        ++ optional (cfg.historySize != null) "HISTSIZE=${toString cfg.historySize}"
        ++ optional (cfg.historyFileSize != null) "HISTFILESIZE=${toString cfg.historyFileSize}"
        ++ optional (cfg.historyControl != [ ]) "HISTCONTROL=${concatStringsSep ":" cfg.historyControl}"
        ++ optional (cfg.historyIgnore != [ ]) "HISTIGNORE=${concatStringsSep ":" cfg.historyIgnore}"

        # Shell options
        ++ map (opt: "shopt -s ${opt}") cfg.shellOptions

        # initExtra (arbitrary user bash code)
        ++ optional (cfg.initExtra != "") cfg.initExtra
      );

      # Compose the bash_profile
      profileContent = concatStringsSep "\n" (
        [ "# Generated by ekaos home configuration. Do not edit." ]
        ++ [ "" ]

        # Source .bashrc for interactive login shells
        ++ [
          ''
            # Source .bashrc for interactive login shells
            if [ -f "$HOME/.bashrc" ]; then
              . "$HOME/.bashrc"
            fi
          ''
        ]

        # profileExtra (login-only code)
        ++ optional (cfg.profileExtra != "") cfg.profileExtra
      );
    in
    {
      options.programs.bash = {
        enable = mkEnableOption "per-user bash configuration";

        initExtra = mkOption {
          type = types.lines;
          default = "";
          example = ''
            eval "$(direnv hook bash)"
            bind '"\e[A": history-search-backward'
          '';
          description = ''
            Extra commands to run in interactive bash shells.
            Appended to .bashrc after session variables and aliases.
          '';
        };

        profileExtra = mkOption {
          type = types.lines;
          default = "";
          example = ''
            export GPG_TTY=$(tty)
          '';
          description = ''
            Extra commands for login shells. Written to .bash_profile
            after sourcing .bashrc.
          '';
        };

        historySize = mkOption {
          type = types.nullOr types.int;
          default = 10000;
          description = "Number of history entries to keep in memory.";
        };

        historyFileSize = mkOption {
          type = types.nullOr types.int;
          default = 100000;
          description = "Number of history lines to keep on disk.";
        };

        historyControl = mkOption {
          type = types.listOf types.str;
          default = [
            "ignoredups"
            "ignorespace"
          ];
          description = "HISTCONTROL values (colon-separated).";
        };

        historyIgnore = mkOption {
          type = types.listOf types.str;
          default = [ ];
          example = [
            "ls"
            "cd"
            "exit"
          ];
          description = "HISTIGNORE patterns (colon-separated).";
        };

        shellOptions = mkOption {
          type = types.listOf types.str;
          default = [
            "histappend"
            "checkwinsize"
            "globstar"
          ];
          example = [
            "histappend"
            "checkwinsize"
            "globstar"
            "cdspell"
          ];
          description = "Bash shell options to enable via shopt -s.";
        };
      };

      config = mkIf cfg.enable {
        file.".bashrc".text = bashrcContent;
        file.".bash_profile".text = profileContent;
      };
    };
in

{
  options.home.users = mkOption {
    type = types.attrsOf (types.submodule bashOpts);
  };
}
