# Per-user git configuration
#
# Extends home.users.<name> with structured git config options.
# Generates ~/.config/git/config from settings, signing, aliases,
# includes, and lfs options.
#
# Usage:
#   home.users.alice.programs.git = {
#     enable = true;
#     settings = {
#       user.name = "Alice";
#       user.email = "alice@example.com";
#       init.defaultBranch = "main";
#       core.autocrlf = "input";
#       pull.rebase = true;
#     };
#     signing = {
#       key = "0xABCDEF";
#       signByDefault = true;
#     };
#     aliases = {
#       st = "status";
#       co = "checkout";
#       lg = "log --oneline --graph --decorate";
#     };
#     lfs.enable = true;
#   };
{ lib, pkgs, ... }:

let
  inherit (lib)
    mkOption
    mkEnableOption
    mkIf
    mkMerge
    types
    concatStringsSep
    mapAttrsToList
    optionalString
    optional
    literalExpression
    ;

  # Format a git config value
  gitValue =
    v:
    if builtins.isBool v then
      (if v then "true" else "false")
    else if builtins.isInt v then
      toString v
    else
      toString v;

  # Render a single section's key-value pairs. Values that are attrsets
  # become subsections: [section "subsection"]
  renderSection =
    section: values:
    if builtins.isAttrs values then
      let
        # Split into flat values and nested subsections
        flat = lib.filterAttrs (_: v: !builtins.isAttrs v) values;
        nested = lib.filterAttrs (_: builtins.isAttrs) values;
        flatLines =
          if flat != { } then
            [ "[${section}]" ] ++ mapAttrsToList (key: value: "\t${key} = ${gitValue value}") flat
          else
            [ ];
        nestedLines = lib.concatLists (
          mapAttrsToList (
            sub: subValues:
            [ "[${section} \"${sub}\"]" ]
            ++ mapAttrsToList (key: value: "\t${key} = ${gitValue value}") subValues
          ) nested
        );
      in
      concatStringsSep "\n" (flatLines ++ nestedLines)
    else
      "[${section}]\n\t${section} = ${gitValue values}";

  # Convert nested attrs to git INI format
  toGitINI = attrs: concatStringsSep "\n" (mapAttrsToList renderSection attrs) + "\n";

  gitOpts =
    { config, ... }:
    let
      cfg = config.programs.git;

      # Merge all settings sources into a single attrset
      mergedSettings =
        cfg.settings
        // (if cfg.aliases != { } then { alias = cfg.aliases; } else { })
        // (
          if cfg.signing.key != null then
            {
              user = (cfg.settings.user or { }) // {
                signingkey = cfg.signing.key;
              };
              commit =
                (cfg.settings.commit or { }) // (if cfg.signing.signByDefault then { gpgsign = true; } else { });
              tag = (cfg.settings.tag or { }) // (if cfg.signing.signByDefault then { gpgsign = true; } else { });
            }
          else
            { }
        )
        // (
          if cfg.signing.format != null then
            {
              gpg = (cfg.settings.gpg or { }) // {
                format = cfg.signing.format;
              };
            }
          else
            { }
        )
        // (
          if cfg.lfs.enable then
            {
              filter = (cfg.settings.filter or { }) // {
                lfs = {
                  clean = "git-lfs clean -- %f";
                  smudge = "git-lfs smudge -- %f";
                  process = "git-lfs filter-process";
                  required = true;
                };
              };
            }
          else
            { }
        );

      # Resolve include entries: generate file paths for inline contents
      resolvedIncludes = lib.imap0 (
        i: inc:
        if inc.contents != null then
          {
            inherit (inc) condition;
            path = "~/.config/git/include-${toString i}";
            generatedContent = toGitINI inc.contents;
          }
        else
          {
            inherit (inc) condition path;
            generatedContent = null;
          }
      ) cfg.includes;

      # Generate includeIf directives
      includeLines = concatStringsSep "\n" (
        map (
          inc:
          let
            condition = if inc.condition != null then "[includeIf \"${inc.condition}\"]" else "[include]";
          in
          "${condition}\n\tpath = ${inc.path}"
        ) resolvedIncludes
      );

      gitconfigContent =
        "# Generated by ekaos home configuration. Do not edit.\n"
        + toGitINI mergedSettings
        + optionalString (cfg.includes != [ ]) ("\n" + includeLines + "\n");
    in
    {
      options.programs.git = {
        enable = mkEnableOption "per-user git configuration";

        package = mkOption {
          type = types.package;
          default = pkgs.git;
          description = "Git package to install.";
        };

        settings = mkOption {
          type = types.attrsOf (types.attrsOf types.anything);
          default = { };
          example = literalExpression ''
            {
              user.name = "Alice";
              user.email = "alice@example.com";
              init.defaultBranch = "main";
              pull.rebase = true;
            }
          '';
          description = ''
            Git configuration as nested attribute sets.
            Top-level keys are INI section names.
          '';
        };

        signing = {
          key = mkOption {
            type = types.nullOr types.str;
            default = null;
            example = "0xABCDEF01";
            description = "GPG key ID for signing commits and tags.";
          };

          signByDefault = mkOption {
            type = types.bool;
            default = false;
            description = "Whether to sign commits and tags by default.";
          };

          format = mkOption {
            type = types.nullOr (
              types.enum [
                "openpgp"
                "x509"
                "ssh"
              ]
            );
            default = null;
            description = "Signing format (openpgp, x509, or ssh).";
          };
        };

        aliases = mkOption {
          type = types.attrsOf types.str;
          default = { };
          example = literalExpression ''
            {
              st = "status";
              co = "checkout";
              lg = "log --oneline --graph --decorate";
            }
          '';
          description = "Git aliases (convenience over settings.alias).";
        };

        includes = mkOption {
          type = types.listOf (
            types.submodule {
              options = {
                condition = mkOption {
                  type = types.nullOr types.str;
                  default = null;
                  example = "gitdir:~/work/";
                  description = ''
                    Conditional include pattern (e.g. "gitdir:~/work/").
                    If null, generates an unconditional [include] directive.
                  '';
                };

                path = mkOption {
                  type = types.nullOr types.str;
                  default = null;
                  example = "~/.config/git/work-config";
                  description = ''
                    Path to the included git config file.
                    Mutually exclusive with contents.
                  '';
                };

                contents = mkOption {
                  type = types.nullOr (types.attrsOf (types.attrsOf types.anything));
                  default = null;
                  example = literalExpression ''
                    {
                      user = {
                        name = "Work Name";
                        email = "work@example.com";
                      };
                    }
                  '';
                  description = ''
                    Git configuration as nested attribute sets.
                    When set, a config file is generated automatically
                    and included. Mutually exclusive with path.
                  '';
                };
              };
            }
          );
          default = [ ];
          example = literalExpression ''
            [
              {
                condition = "gitdir:~/work/";
                contents = {
                  user = {
                    name = "Work Name";
                    email = "work@example.com";
                  };
                };
              }
            ]
          '';
          description = "Conditional or unconditional git config includes.";
        };

        lfs = {
          enable = mkOption {
            type = types.bool;
            default = false;
            description = "Whether to enable Git LFS.";
          };
        };
      };

      config = mkIf cfg.enable {
        packages = [ cfg.package ] ++ optional cfg.lfs.enable pkgs.git-lfs;
        file = {
          ".config/git/config".text = gitconfigContent;
        }
        // lib.listToAttrs (
          lib.concatMap (
            inc:
            if inc.generatedContent != null then
              [
                (lib.nameValuePair (lib.removePrefix "~/" inc.path) { text = inc.generatedContent; })
              ]
            else
              [ ]
          ) resolvedIncludes
        );
      };
    };
in

{
  options.home.users = mkOption {
    type = types.attrsOf (types.submodule gitOpts);
  };
}
