# Per-user GPG agent configuration
#
# Extends home.users.<name> with GPG agent options.
# Generates ~/.gnupg/gpg-agent.conf and systemd user units for
# socket activation (gpg-agent.service, gpg-agent.socket, and
# optionally gpg-agent-ssh.socket and gpg-agent-extra.socket).
#
# Usage:
#   home.users.alice.programs.gpg-agent = {
#     enable = true;
#     enableSshSupport = true;
#     enableExtraSocket = true;
#     pinentryPackage = pkgs.pinentry-curses;
#     defaultCacheTtl = 3600;
#     maxCacheTtl = 7200;
#   };
{ lib, pkgs, ... }:

let
  inherit (lib)
    mkOption
    mkEnableOption
    mkIf
    mkMerge
    types
    concatStringsSep
    optional
    optionalString
    literalExpression
    ;

  gpgAgentOpts =
    { config, ... }:
    let
      cfg = config.programs.gpg-agent;

      # Resolve pinentry binary name: explicit flavor > meta.mainProgram > "pinentry"
      pinentryBin =
        if cfg.pinentryFlavor != null then cfg.pinentryFlavor
        else cfg.pinentryPackage.meta.mainProgram or "pinentry";

      # Build gpg-agent.conf
      agentConfContent = concatStringsSep "\n" (
        [ "# Generated by ekaos home configuration. Do not edit." ]
        ++ optional (
          cfg.pinentryPackage != null
        ) "pinentry-program ${cfg.pinentryPackage}/bin/${pinentryBin}"
        ++ optional (cfg.defaultCacheTtl != null) "default-cache-ttl ${toString cfg.defaultCacheTtl}"
        ++ optional (
          cfg.defaultCacheTtlSsh != null
        ) "default-cache-ttl-ssh ${toString cfg.defaultCacheTtlSsh}"
        ++ optional (cfg.maxCacheTtl != null) "max-cache-ttl ${toString cfg.maxCacheTtl}"
        ++ optional (cfg.maxCacheTtlSsh != null) "max-cache-ttl-ssh ${toString cfg.maxCacheTtlSsh}"
        ++ optional cfg.enableSshSupport "enable-ssh-support"
        ++ optional cfg.enableExtraSocket "extra-socket /run/user/%U/gnupg/S.gpg-agent.extra"
        ++ optional (cfg.extraConfig != "") cfg.extraConfig
        ++ [ "" ]
      );

      # --- systemd user units ---

      # gpg-agent.service
      serviceUnit = ''
        # Generated by ekaos home configuration. Do not edit.
        [Unit]
        Description=GnuPG cryptographic agent and target daemon
        Documentation=man:gpg-agent(1)
        Requires=gpg-agent.socket
        After=gpg-agent.socket

        [Service]
        Type=simple
        ExecStart=${pkgs.gnupg}/bin/gpg-agent --supervised
        ExecReload=${pkgs.gnupg}/bin/gpgconf --reload gpg-agent
        Restart=on-failure
        Environment=GNUPGHOME=%h/.gnupg

        [Install]
        Also=gpg-agent.socket
      '';

      # gpg-agent.socket (main S.gpg-agent socket)
      socketUnit = ''
        # Generated by ekaos home configuration. Do not edit.
        [Unit]
        Description=GnuPG cryptographic agent and target daemon (socket)
        Documentation=man:gpg-agent(1)

        [Socket]
        ListenStream=%t/gnupg/S.gpg-agent
        FileDescriptorName=std
        SocketMode=0600
        DirectoryMode=0700

        [Install]
        WantedBy=sockets.target
      '';

      # gpg-agent-ssh.socket (SSH agent emulation)
      sshSocketUnit = ''
        # Generated by ekaos home configuration. Do not edit.
        [Unit]
        Description=GnuPG cryptographic agent (ssh-agent emulation)
        Documentation=man:gpg-agent(1)

        [Socket]
        ListenStream=%t/gnupg/S.gpg-agent.ssh
        FileDescriptorName=ssh
        Service=gpg-agent.service
        SocketMode=0600
        DirectoryMode=0700

        [Install]
        WantedBy=sockets.target
      '';

      # gpg-agent-extra.socket (remote access / forwarding)
      extraSocketUnit = ''
        # Generated by ekaos home configuration. Do not edit.
        [Unit]
        Description=GnuPG cryptographic agent (extra socket for forwarding)
        Documentation=man:gpg-agent(1)

        [Socket]
        ListenStream=%t/gnupg/S.gpg-agent.extra
        FileDescriptorName=extra
        Service=gpg-agent.service
        SocketMode=0600
        DirectoryMode=0700

        [Install]
        WantedBy=sockets.target
      '';
    in
    {
      options.programs.gpg-agent = {
        enable = mkEnableOption "GPG agent user configuration";

        pinentryPackage = mkOption {
          type = types.nullOr types.package;
          default = null;
          example = literalExpression "pkgs.pinentry-curses";
          description = "Pinentry package for passphrase prompts.";
        };

        pinentryFlavor = mkOption {
          type = types.nullOr types.str;
          default = null;
          example = "pinentry-curses";
          description = ''
            Binary name within the pinentry package.
            Common values: pinentry, pinentry-curses, pinentry-gtk-2, pinentry-qt.
            When null, auto-detected from pinentryPackage.meta.mainProgram
            or defaults to "pinentry".
          '';
        };

        enableSshSupport = mkOption {
          type = types.bool;
          default = false;
          description = "Whether to enable SSH agent emulation.";
        };

        enableExtraSocket = mkOption {
          type = types.bool;
          default = false;
          description = ''
            Whether to enable the extra socket for GPG agent forwarding.
            This creates a separate socket (S.gpg-agent.extra) useful for
            forwarding the agent to remote machines.
          '';
        };

        defaultCacheTtl = mkOption {
          type = types.nullOr types.int;
          default = null;
          example = 3600;
          description = "Time in seconds a cached passphrase is valid (default: 600).";
        };

        defaultCacheTtlSsh = mkOption {
          type = types.nullOr types.int;
          default = null;
          example = 3600;
          description = "Time in seconds a cached SSH passphrase is valid.";
        };

        maxCacheTtl = mkOption {
          type = types.nullOr types.int;
          default = null;
          example = 7200;
          description = "Maximum time in seconds a passphrase can be cached.";
        };

        maxCacheTtlSsh = mkOption {
          type = types.nullOr types.int;
          default = null;
          example = 7200;
          description = "Maximum time in seconds an SSH passphrase can be cached.";
        };

        extraConfig = mkOption {
          type = types.lines;
          default = "";
          description = "Additional lines for gpg-agent.conf.";
        };
      };

      config = mkIf cfg.enable (mkMerge [
        # Always: packages, gpg-agent.conf, service unit, main socket unit
        {
          packages = [ pkgs.gnupg ] ++ optional (cfg.pinentryPackage != null) cfg.pinentryPackage;
          file.".gnupg/gpg-agent.conf".text = agentConfContent;
          file.".config/systemd/user/gpg-agent.service".text = serviceUnit;
          file.".config/systemd/user/gpg-agent.socket".text = socketUnit;
        }

        # Conditionally: SSH agent socket
        (mkIf cfg.enableSshSupport {
          file.".config/systemd/user/gpg-agent-ssh.socket".text = sshSocketUnit;
        })

        # Conditionally: extra socket for forwarding
        (mkIf cfg.enableExtraSocket {
          file.".config/systemd/user/gpg-agent-extra.socket".text = extraSocketUnit;
        })
      ]);
    };
in

{
  options.home.users = mkOption {
    type = types.attrsOf (types.submodule gpgAgentOpts);
  };
}
