# Per-user GPG agent configuration
#
# Extends home.users.<name> with GPG agent options.
# Generates ~/.gnupg/gpg-agent.conf and optionally a systemd user unit.
#
# Usage:
#   home.users.alice.programs.gpg-agent = {
#     enable = true;
#     enableSshSupport = true;
#     pinentryPackage = pkgs.pinentry-curses;
#     defaultCacheTtl = 3600;
#     maxCacheTtl = 7200;
#   };
{ lib, pkgs, ... }:

let
  inherit (lib)
    mkOption
    mkEnableOption
    mkIf
    types
    concatStringsSep
    optional
    optionalString
    literalExpression
    ;

  gpgAgentOpts =
    { config, ... }:
    let
      cfg = config.programs.gpg-agent;

      # Build gpg-agent.conf
      agentConfContent = concatStringsSep "\n" (
        [ "# Generated by ekaos home configuration. Do not edit." ]
        ++ optional (
          cfg.pinentryPackage != null
        ) "pinentry-program ${cfg.pinentryPackage}/bin/${cfg.pinentryFlavor}"
        ++ optional (cfg.defaultCacheTtl != null) "default-cache-ttl ${toString cfg.defaultCacheTtl}"
        ++ optional (
          cfg.defaultCacheTtlSsh != null
        ) "default-cache-ttl-ssh ${toString cfg.defaultCacheTtlSsh}"
        ++ optional (cfg.maxCacheTtl != null) "max-cache-ttl ${toString cfg.maxCacheTtl}"
        ++ optional (cfg.maxCacheTtlSsh != null) "max-cache-ttl-ssh ${toString cfg.maxCacheTtlSsh}"
        ++ optional cfg.enableSshSupport "enable-ssh-support"
        ++ optional (cfg.extraConfig != "") cfg.extraConfig
        ++ [ "" ]
      );
    in
    {
      options.programs.gpg-agent = {
        enable = mkEnableOption "GPG agent user configuration";

        pinentryPackage = mkOption {
          type = types.nullOr types.package;
          default = null;
          example = literalExpression "pkgs.pinentry-curses";
          description = "Pinentry package for passphrase prompts.";
        };

        pinentryFlavor = mkOption {
          type = types.str;
          default = "pinentry";
          example = "pinentry-curses";
          description = ''
            Binary name within the pinentry package.
            Common values: pinentry, pinentry-curses, pinentry-gtk-2, pinentry-qt.
          '';
        };

        enableSshSupport = mkOption {
          type = types.bool;
          default = false;
          description = "Whether to enable SSH agent emulation.";
        };

        defaultCacheTtl = mkOption {
          type = types.nullOr types.int;
          default = null;
          example = 3600;
          description = "Time in seconds a cached passphrase is valid (default: 600).";
        };

        defaultCacheTtlSsh = mkOption {
          type = types.nullOr types.int;
          default = null;
          example = 3600;
          description = "Time in seconds a cached SSH passphrase is valid.";
        };

        maxCacheTtl = mkOption {
          type = types.nullOr types.int;
          default = null;
          example = 7200;
          description = "Maximum time in seconds a passphrase can be cached.";
        };

        maxCacheTtlSsh = mkOption {
          type = types.nullOr types.int;
          default = null;
          example = 7200;
          description = "Maximum time in seconds an SSH passphrase can be cached.";
        };

        extraConfig = mkOption {
          type = types.lines;
          default = "";
          description = "Additional lines for gpg-agent.conf.";
        };
      };

      config = mkIf cfg.enable {
        packages = [ pkgs.gnupg ] ++ optional (cfg.pinentryPackage != null) cfg.pinentryPackage;
        file.".gnupg/gpg-agent.conf".text = agentConfContent;
      };
    };
in

{
  options.home.users = mkOption {
    type = types.attrsOf (types.submodule gpgAgentOpts);
  };
}
