# Adios port of ekaos/modules/networking/dns-zones.nix.
#
# Tree path: networking/dns-zones is parent.networking."dns-zones".
# Reads port-contract hostnames via inputs.ports
# (parent.networking."port-contracts").
# TODO(adios-cutover): writes to environment.etc / system.activationScripts
# target the global namespace; the tree must merge this impl fragment with
# fragments from all other modules (no global fixpoint in adios).
# TODO(adios-cutover): per-zone ttl default (legacy: cfg.defaultTTL) is now
# applied via `or` fallback in impl; attrsOf-submodule validation lost
# (zones is types.attrsOf types.attrs).
{ types, ... }:

let
  splitDot = s: builtins.filter builtins.isString (builtins.split "[.]" s);
  drop =
    n: xs:
    if n <= 0 then
      xs
    else if xs == [ ] then
      [ ]
    else
      drop (n - 1) (builtins.tail xs);
  unique = xs: builtins.foldl' (acc: x: if builtins.elem x acc then acc else acc ++ [ x ]) [ ] xs;
  groupBy =
    keyFn: list:
    builtins.foldl' (
      acc: x:
      let
        k = keyFn x;
      in
      acc // { ${k} = (acc.${k} or [ ]) ++ [ x ]; }
    ) { } list;
  mapAttrsToList = f: attrs: builtins.map (n: f n attrs.${n}) (builtins.attrNames attrs);
in

{
  options = {
    enable = {
      type = types.bool;
      default = false;
      description = ''
        Whether to enable DNS zone file generation from port contracts.
        Zone files are written to /etc/dns/zones/ and can be consumed
        by any DNS server (unbound, bind, etc.).
      '';
    };

    defaultTTL = {
      type = types.int;
      default = 3600;
      description = "Default TTL in seconds for DNS records.";
    };

    zones = {
      type = types.attrsOf types.attrs;
      default = { };
      description = ''
        Per-domain zone configuration. Domains are auto-discovered
        from port contracts with hostnames, but can be customized here.
        Each entry may set ttl, address, serial, extraRecords.
      '';
    };

    zoneDir = {
      type = types.string;
      default = "/etc/dns/zones";
      description = "Directory where zone files are written.";
    };

    forwardZones = {
      type = types.attrsOf types.string;
      default = { };
      example = {
        "fleet.internal" = "10.100.0.1";
      };
      description = ''
        Zones to forward to an upstream resolver instead of serving locally.
        Maps zone names to the IP address of the upstream DNS server.
        Useful for delegating fleet service discovery zones to ekafleet's
        built-in DNS authority.
      '';
    };
  };

  inputs = {
    ports.from = { parent }: parent."port-contracts";
  };

  assertions = [
    {
      verify = { options, inputs }: options.defaultTTL > 0;
      explain = { options, inputs }: "defaultTTL must be positive, got ${toString options.defaultTTL}";
    }
  ];

  impl =
    { options, inputs }:
    let
      portsByHostname = inputs.ports.byHostname or { };

      # Extract unique domains from hostnames (e.g., "app.example.com" -> "example.com")
      getDomain =
        hostname:
        let
          parts = splitDot hostname;
          len = builtins.length parts;
        in
        if len >= 2 then builtins.concatStringsSep "." (drop (len - 2) parts) else hostname;

      # Group hostnames by their parent domain
      allHostnames = builtins.attrNames portsByHostname;
      domainMap = groupBy getDomain allHostnames;

      # Merge auto-discovered domains with manually declared zones
      allDomains = unique ((builtins.attrNames domainMap) ++ (builtins.attrNames options.zones));

      # Generate a zone file for a domain
      mkZoneFile =
        domain:
        let
          zoneCfg = options.zones.${domain} or { };
          hostnames = domainMap.${domain} or [ ];
          ttl = zoneCfg.ttl or options.defaultTTL;
          listenAddr = zoneCfg.address or "127.0.0.1";
          serial = zoneCfg.serial or "1";
          extraRecords = zoneCfg.extraRecords or "";

          # Generate A records for each hostname
          aRecords = builtins.concatStringsSep "\n" (
            builtins.map (
              hostname:
              let
                parts = splitDot hostname;
                domParts = splitDot domain;
                subParts = drop (builtins.length domParts) parts;
                subdomain = if subParts == [ ] then "@" else builtins.concatStringsSep "." subParts;
              in
              "${subdomain}  IN  A  ${listenAddr}"
            ) hostnames
          );
        in
        ''
          ; Zone file for ${domain}
          ; Auto-generated by ekaos dns-zones module
          $TTL ${toString ttl}
          @  IN  SOA  ns1.${domain}. admin.${domain}. (
                        ${serial}    ; Serial
                        3600         ; Refresh
                        900          ; Retry
                        604800       ; Expire
                        86400 )      ; Minimum TTL

          @  IN  NS  ns1.${domain}.
          ns1  IN  A  ${listenAddr}

          ${aRecords}

          ${extraRecords}
        '';
    in
    if !options.enable then
      { }
    else
      {
        # Generate zone files in /etc/dns/zones/
        environment.etc =
          builtins.listToAttrs (
            builtins.map (domain: {
              name = "dns/zones/${domain}.zone";
              value = {
                text = mkZoneFile domain;
              };
            }) allDomains
          )
          # Generate forward zone configuration
          // (
            if options.forwardZones != { } then
              {
                "dns/forward-zones.conf".text =
                  builtins.concatStringsSep "\n" (mapAttrsToList (zone: addr: "${zone} ${addr}") options.forwardZones)
                  + "\n";
              }
            else
              { }
          );

        # Create zone directory
        system.activationScripts.dns-zones = {
          deps = [ "etc" ];
          text = ''
            mkdir -p ${options.zoneDir}
          '';
        };
      };
}
