# DNS zone generation module
# Auto-generates DNS zone files from port contracts with hostnames
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.networking.dns;
  portsByHostname = config.networking.ports.byHostname or { };

  # Extract unique domains from hostnames (e.g., "app.example.com" -> "example.com")
  getDomain =
    hostname:
    let
      parts = splitString "." hostname;
      len = length parts;
    in
    if len >= 2 then concatStringsSep "." (drop (len - 2) parts) else hostname;

  # Group hostnames by their parent domain
  allHostnames = attrNames portsByHostname;
  domainMap = groupBy getDomain allHostnames;

  # Merge auto-discovered domains with manually declared zones
  allDomains = unique ((attrNames domainMap) ++ (attrNames cfg.zones));

  # Generate a zone file for a domain
  mkZoneFile =
    domain:
    let
      zoneCfg = cfg.zones.${domain} or { };
      hostnames = domainMap.${domain} or [ ];
      ttl = zoneCfg.ttl or cfg.defaultTTL;
      listenAddr = zoneCfg.address or "127.0.0.1";
      serial = zoneCfg.serial or "1";
      extraRecords = zoneCfg.extraRecords or "";

      # Generate A records for each hostname
      aRecords = concatMapStringsSep "\n" (
        hostname:
        let
          # Get the subdomain part (e.g., "app" from "app.example.com")
          parts = splitString "." hostname;
          domParts = splitString "." domain;
          subParts = take (length parts - length domParts) parts;
          subdomain = if subParts == [ ] then "@" else concatStringsSep "." subParts;
        in
        "${subdomain}  IN  A  ${listenAddr}"
      ) hostnames;
    in
    ''
      ; Zone file for ${domain}
      ; Auto-generated by ekaos dns-zones module
      $TTL ${toString ttl}
      @  IN  SOA  ns1.${domain}. admin.${domain}. (
                    ${serial}    ; Serial
                    3600         ; Refresh
                    900          ; Retry
                    604800       ; Expire
                    86400 )      ; Minimum TTL

      @  IN  NS  ns1.${domain}.
      ns1  IN  A  ${listenAddr}

      ${aRecords}

      ${extraRecords}
    '';

  zoneSubmodule = {
    options = {
      ttl = mkOption {
        type = types.ints.positive;
        default = cfg.defaultTTL;
        description = "Default TTL for records in this zone.";
      };

      address = mkOption {
        type = types.str;
        default = "127.0.0.1";
        description = "IP address for auto-generated A records.";
      };

      serial = mkOption {
        type = types.str;
        default = "1";
        description = "SOA serial number. Increment on changes.";
      };

      extraRecords = mkOption {
        type = types.lines;
        default = "";
        example = ''
          mail  IN  MX  10  mail.example.com.
          mail  IN  A   192.168.1.10
        '';
        description = "Additional DNS records to include in the zone file.";
      };
    };
  };

in

{
  options.networking.dns = {
    enable = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Whether to enable DNS zone file generation from port contracts.
        Zone files are written to /etc/dns/zones/ and can be consumed
        by any DNS server (unbound, bind, etc.).
      '';
    };

    defaultTTL = mkOption {
      type = types.ints.positive;
      default = 3600;
      description = "Default TTL in seconds for DNS records.";
    };

    zones = mkOption {
      type = types.attrsOf (types.submodule zoneSubmodule);
      default = { };
      description = ''
        Per-domain zone configuration. Domains are auto-discovered
        from port contracts with hostnames, but can be customized here.
      '';
    };

    zoneDir = mkOption {
      type = types.str;
      default = "/etc/dns/zones";
      description = "Directory where zone files are written.";
    };

    forwardZones = mkOption {
      type = types.attrsOf types.str;
      default = { };
      example = {
        "fleet.internal" = "10.100.0.1";
      };
      description = ''
        Zones to forward to an upstream resolver instead of serving locally.
        Maps zone names to the IP address of the upstream DNS server.
        Useful for delegating fleet service discovery zones to ekafleet's
        built-in DNS authority.
      '';
    };
  };

  config = mkIf cfg.enable {
    # Generate zone files in /etc/dns/zones/
    environment.etc = listToAttrs (
      map (
        domain:
        nameValuePair "dns/zones/${domain}.zone" {
          text = mkZoneFile domain;
        }
      ) allDomains
    )
    # Generate forward zone configuration
    // optionalAttrs (cfg.forwardZones != { }) {
      "dns/forward-zones.conf".text = concatStringsSep "\n" (
        mapAttrsToList (
          zone: addr: "${zone} ${addr}"
        ) cfg.forwardZones
      ) + "\n";
    };

    # Create zone directory
    system.activationScripts.dns-zones = stringAfter [ "etc" ] ''
      mkdir -p ${cfg.zoneDir}
    '';
  };
}
