# nftables ruleset management
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.networking.nftables;
in

{
  options = {
    networking.nftables = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to use nftables as the firewall backend.

          When enabled, the nftables ruleset is loaded at boot.
          This is an alternative to iptables-based firewall management.
        '';
      };

      ruleset = mkOption {
        type = types.lines;
        default = "";
        example = ''
          table inet filter {
            chain input {
              type filter hook input priority 0; policy drop;
              ct state established,related accept
              iif lo accept
              tcp dport { 22, 80, 443 } accept
            }
            chain forward {
              type filter hook forward priority 0; policy drop;
            }
            chain output {
              type filter hook output priority 0; policy accept;
            }
          }
        '';
        description = ''
          The nftables ruleset to load.

          When set, this replaces the full firewall configuration.
          Use networking.firewall for a higher-level interface.
        '';
      };

      rulesetFile = mkOption {
        type = types.nullOr types.path;
        default = null;
        description = "Path to an nftables ruleset file to load instead of ruleset.";
      };

      flushRuleset = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to flush the existing ruleset before loading.";
      };

      checkRuleset = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to validate the ruleset at build time.";
      };

      tables = mkOption {
        type = types.attrsOf (
          types.submodule {
            options = {
              family = mkOption {
                type = types.enum [
                  "ip"
                  "ip6"
                  "inet"
                  "arp"
                  "bridge"
                  "netdev"
                ];
                description = "Address family for this table.";
              };

              content = mkOption {
                type = types.lines;
                description = "nftables rules inside this table.";
              };
            };
          }
        );
        default = { };
        description = "Named nftables tables with their content.";
      };
    };
  };

  config = mkIf cfg.enable {
    environment.systemPackages = [ pkgs.nftables ];

    environment.etc."nftables.conf".text =
      let
        tablesContent = concatStringsSep "\n" (
          mapAttrsToList (name: table: ''
            table ${table.family} ${name} {
              ${table.content}
            }
          '') cfg.tables
        );

        rulesetContent =
          if cfg.rulesetFile != null then
            "include \"${cfg.rulesetFile}\""
          else
            ''
              ${optionalString cfg.flushRuleset "flush ruleset"}
              ${cfg.ruleset}
              ${tablesContent}
            '';
      in
      ''
        #!/usr/bin/env nft -f
        # Generated by ekaos nftables module
        ${rulesetContent}
      '';

    system.activationScripts.nftables = stringAfter [ "etc" ] ''
      echo "Loading nftables ruleset..."
      ${pkgs.nftables}/bin/nft -f /etc/nftables.conf || true
    '';
  };
}
