# Adios port of ekaos/modules/config/home.nix.
# TODO(adios-cutover) notes below mark semantics changed in translation.
#
# Per-user home configuration: declarative dotfiles, packages, environment
# variables, shell aliases, and per-user activation scripts.
#
# Usage in ekaos system configuration:
#   users.users.alice = {
#     packages = [ pkgs.git pkgs.vim ];
#     sessionVariables.EDITOR = "vim";
#     home.file.".bashrc".text = "PS1='$ '";
#   };
{ types, pkgs, ... }:

let
  filterAttrs =
    pred: set:
    builtins.listToAttrs (
      builtins.map (n: {
        name = n;
        value = set.${n};
      }) (builtins.filter (n: pred n set.${n}) (builtins.attrNames set))
    );

  optionalString = cond: s: if cond then s else "";

  concatMapStringsSep =
    sep: f: xs:
    builtins.concatStringsSep sep (builtins.map f xs);

  mapAttrsToList = f: set: builtins.map (n: f n set.${n}) (builtins.attrNames set);

  escapeShellArg = s: "'${builtins.replaceStrings [ "'" ] [ "'\\''" ] (toString s)}'";

  # Topologically sort activation scripts (same algorithm as system activation)
  sortActivationScripts =
    scripts:
    let
      scriptNames = builtins.attrNames scripts;
      sort =
        remaining: sorted:
        if remaining == [ ] then
          sorted
        else
          let
            ready = builtins.filter (
              name:
              let
                deps = scripts.${name}.deps or [ ];
                unsatisfied = builtins.filter (d: builtins.elem d remaining) deps;
              in
              unsatisfied == [ ]
            ) remaining;
            newRemaining = builtins.filter (name: !(builtins.elem name ready)) remaining;
          in
          if ready == [ ] then
            throw "Circular dependency in home activation scripts: ${toString remaining}"
          else
            sort newRemaining (sorted ++ ready);
    in
    sort scriptNames [ ];

  # Check if a user has any home configuration
  hasHomeConfig =
    userCfg:
    userCfg.packages or [ ] != [ ]
    || userCfg.home.file or { } != { }
    || userCfg.sessionVariables or { } != { }
    || userCfg.sessionPath or [ ] != [ ]
    || userCfg.shellAliases or { } != { }
    || userCfg.home.activation or { } != { };

  # Build the home-files derivation for a user
  mkHomeFiles =
    userName: userCfg:
    let
      enabledFiles = builtins.filter (f: f.enable) (builtins.attrValues userCfg.home.file);
    in
    pkgs.runCommand "home-files-${userName}"
      {
        preferLocalBuild = true;
      }
      ''
        mkdir -p $out

        ${concatMapStringsSep "\n" (
          file:
          let
            source =
              if file.source != null then
                file.source
              else if file.text != null then
                let
                  textFile = pkgs.writeText (builtins.baseNameOf file.target) file.text;
                in
                if file.executable then
                  pkgs.runCommand (builtins.baseNameOf file.target) { } ''
                    cp ${textFile} $out
                    chmod +x $out
                  ''
                else
                  textFile
              else
                throw "home.file.${file.target} has neither source nor text";
          in
          ''
            mkdir -p $out/$(dirname ${escapeShellArg file.target})
            ln -s ${source} $out/${escapeShellArg file.target}
          ''
        ) enabledFiles}
      '';

  # Build the per-user package environment
  mkHomePath =
    userName: userCfg:
    pkgs.buildEnv {
      name = "home-path-${userName}";
      paths = userCfg.packages;
      pathsToLink = [
        "/bin"
        "/sbin"
        "/lib"
        "/share"
      ];
      ignoreCollisions = true;
    };

  # Generate session-vars.sh for a user
  mkSessionVars =
    userName: userCfg:
    let
      pathEntries =
        (if (userCfg.packages != [ ]) then [ "$HOME/.ekaos-profile/bin" ] else [ ]) ++ userCfg.sessionPath;

      pathPrefix =
        if pathEntries != [ ] then
          ''export PATH="${builtins.concatStringsSep ":" pathEntries}:$PATH"''
        else
          "";

      envVars = builtins.concatStringsSep "\n" (
        mapAttrsToList (
          name: value: "export ${name}=${escapeShellArg (toString value)}"
        ) userCfg.sessionVariables
      );

      aliases = builtins.concatStringsSep "\n" (
        mapAttrsToList (name: value: "alias ${name}=${escapeShellArg value}") userCfg.shellAliases
      );
    in
    pkgs.writeText "session-vars-${userName}.sh" ''
      # Generated by ekaos home configuration. Do not edit.
      ${pathPrefix}
      ${envVars}
      ${aliases}
    '';

  # Build the manifest (JSON list of managed file targets)
  mkManifest =
    userName: userCfg:
    let
      enabledFiles = builtins.filter (f: f.enable) (builtins.attrValues userCfg.home.file);
      targets = builtins.map (f: f.target) enabledFiles;
    in
    pkgs.writeText "home-files-manifest-${userName}" (builtins.toJSON targets);

  # Build the activation package for a single user
  mkHomeActivationPackage =
    userName: userCfg:
    let
      homeFiles = mkHomeFiles userName userCfg;
      homePath = mkHomePath userName userCfg;
      sessionVars = mkSessionVars userName userCfg;
      manifest = mkManifest userName userCfg;

      sortedScripts = sortActivationScripts userCfg.home.activation;
      activationBodies = concatMapStringsSep "\n" (
        name:
        let
          script = userCfg.home.activation.${name};
        in
        ''
          # Home activation: ${name}
          ${script.text}
        ''
      ) sortedScripts;
    in
    pkgs.runCommand "home-${userName}"
      {
        preferLocalBuild = true;
        allowSubstitutes = false;
      }
      ''
        mkdir -p $out

        ln -s ${homeFiles} $out/home-files
        ln -s ${homePath} $out/home-path
        cp ${sessionVars} $out/session-vars.sh
        cp ${manifest} $out/home-files-manifest

        cat > $out/activate <<'ACTIVATE'
        #!${pkgs.runtimeShell}
        set -e

        EKAOS_STATE_DIR="$HOME/.config/ekaos"
        EKAOS_GEN_DIR="$EKAOS_STATE_DIR/generations"
        MANIFEST_FILE="$EKAOS_STATE_DIR/home-files-manifest"
        THIS="$(cd "$(dirname "$0")" && pwd)"

        echo "ekaos home: activating for $(whoami)..."

        # Create state directories
        mkdir -p "$EKAOS_STATE_DIR"
        mkdir -p "$EKAOS_GEN_DIR"

        # Update profile symlink
        if [ -d "$THIS/home-path" ] || [ -L "$THIS/home-path" ]; then
          ln -sfn "$(readlink -f "$THIS/home-path")" "$HOME/.ekaos-profile"
          echo "  Updated ~/.ekaos-profile"
        fi

        # Remove stale symlinks from previous manifest
        if [ -f "$MANIFEST_FILE" ]; then
          for old_target in $(${pkgs.jq}/bin/jq -r '.[]' "$MANIFEST_FILE" 2>/dev/null); do
            target_path="$HOME/$old_target"
            if [ -L "$target_path" ]; then
              rm -f "$target_path"
            fi
          done
        fi

        # Create new symlinks from home-files into HOME
        if [ -d "$THIS/home-files" ]; then
          cd "$THIS/home-files"
          find . -type l | while IFS= read -r link; do
            rel="''${link#./}"
            mkdir -p "$HOME/$(dirname "$rel")"

            dest="$HOME/$rel"
            if [ -e "$dest" ] && [ ! -L "$dest" ]; then
              echo "  WARNING: $rel exists and is not a symlink, backing up"
              mv "$dest" "$dest.ekaos-backup"
            fi

            ln -sfn "$(readlink -f "$link")" "$dest"
          done
          echo "  Linked home files"
        fi

        # Write new manifest
        cp "$THIS/home-files-manifest" "$MANIFEST_FILE"

        # Install session-vars.sh
        cp "$THIS/session-vars.sh" "$EKAOS_STATE_DIR/session-vars.sh"
        echo "  Installed session-vars.sh"

        # Run user activation scripts
        ${activationBodies}

        # Record generation
        gen_num=1
        latest=$(ls -1 "$EKAOS_GEN_DIR" 2>/dev/null | sort -n | tail -1)
        if [ -n "$latest" ]; then
          gen_num=$((latest + 1))
        fi
        ln -sfn "$THIS" "$EKAOS_GEN_DIR/$gen_num"
        ln -sfn "$THIS" "$EKAOS_STATE_DIR/current-home"
        echo "  Generation $gen_num activated"

        echo "ekaos home: activation complete."
        ACTIVATE
        chmod +x $out/activate

        substituteInPlace $out/activate \
          --replace '#!${pkgs.runtimeShell}' '#!${pkgs.runtimeShell}'
      '';

  # Build the combined home derivation for all users with home config
  mkCombinedHome =
    usersWithHome:
    pkgs.runCommand "ekaos-home"
      {
        preferLocalBuild = true;
        allowSubstitutes = false;
      }
      ''
        mkdir -p $out/users

        ${builtins.concatStringsSep "\n" (
          mapAttrsToList (userName: userCfg: ''
            ln -s ${userCfg.home.activationPackage} $out/users/${userName}
          '') usersWithHome
        )}

        # Write a top-level activate script that activates all users
        cat > $out/activate <<'ACTIVATE'
        #!${pkgs.runtimeShell}
        set -e
        echo "ekaos home: activating all user homes..."
        ${builtins.concatStringsSep "\n" (
          mapAttrsToList (userName: userCfg: ''
            echo "  Activating home for ${userName}..."
            su - ${userName} -c "${userCfg.home.activationPackage}/activate" 2>&1 || \
              echo "  WARNING: home activation failed for ${userName}"
          '') usersWithHome
        )}
        echo "ekaos home: all activations complete."
        ACTIVATE
        chmod +x $out/activate
      '';
in

{
  options = {
    users = {
      # TODO(adios-cutover): submodule validation lost. Legacy extended each
      # users.users entry with home.file (attrsOf submodule:
      # enable/target/source/text/executable), home.stateVersion,
      # home.activation (attrsOf submodule: deps/text, topologically
      # sorted), home.activationPackage (computed via mkIf hasHomeConfig),
      # packages, sessionVariables, sessionPath, shellAliases.
      # TODO(adios-cutover): home.activationPackage was computed per-user by
      # the legacy module; adios consumers must provide it explicitly
      # (e.g. via mkHomeActivationPackage-equivalent) or impl lookups below
      # fail at eval.
      type = types.attrsOf types.attrs;
      default = { };
      description = ''
        User account configuration, extended with per-user home management
        (home.file, home.activation, packages, sessionVariables,
        sessionPath, shellAliases).
      '';
    };

    buildHome = {
      type = types.nullOr types.derivation;
      default = null;
      description = ''
        Combined home activation package for all configured users.

        Contains per-user activation packages under users/<name>/ and
        a top-level activate script that runs all of them.

        Build with: nix-build -A config.system.build.home
      '';
    };
  };

  impl =
    { options, ... }:
    let
      # All users that have home configuration
      usersWithHome = filterAttrs (_: userCfg: hasHomeConfig userCfg) options.users;

      # Combined home derivation containing all user activation packages
      combinedHome = mkCombinedHome usersWithHome;
    in
    {
      system.build.home = combinedHome;

      # System activation script that activates home configs during boot/switch
      system.activationScripts.home = {
        deps = [ "users" ];
        text =
          if usersWithHome != { } then
            ''
              echo "Activating per-user home configurations..."
              ${builtins.concatStringsSep "\n" (
                mapAttrsToList (userName: userCfg: ''
                  echo "  Activating home for ${userName}..."
                  su - ${userName} -c "${userCfg.home.activationPackage}/activate" 2>&1 || \
                    echo "  WARNING: home activation failed for ${userName}"
                '') usersWithHome
              )}
            ''
          else
            ''
              # No users with home configuration
            '';
      };
    };
}
