# Nix daemon configuration
# Generates /etc/nix/nix.conf
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.nix;

  # Format a nix.conf value
  formatValue =
    v:
    if isBool v then
      (if v then "true" else "false")
    else if isList v then
      concatStringsSep " " (map toString v)
    else
      toString v;

  # Generate nix.conf from settings
  nixConf = concatStringsSep "\n" (
    mapAttrsToList (name: value: "${name} = ${formatValue value}") cfg.settings
  );

  # Generate nix-path setting
  nixPathConf = optionalString (cfg.nixPath != [ ]) (
    "nix-path = ${concatStringsSep ":" cfg.nixPath}"
  );

in

{
  options.nix = {
    package = mkOption {
      type = types.package;
      default = pkgs.nix;
      defaultText = literalExpression "pkgs.nix";
      description = ''
        The Nix package to use for the daemon and CLI tools.

        All modules should reference config.nix.package instead of pkgs.nix.
      '';
    };

    settings = mkOption {
      type = types.attrsOf (
        types.oneOf [
          types.bool
          types.int
          types.str
          types.path
          (types.listOf types.str)
        ]
      );
      default = { };
      example = literalExpression ''
        {
          max-jobs = 4;
          cores = 0;
          sandbox = true;
          auto-optimise-store = true;
          substituters = [ "https://cache.nixos.org" ];
          trusted-public-keys = [ "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" ];
        }
      '';
      description = ''
        Nix daemon settings written to /etc/nix/nix.conf.
        See nix.conf(5) for available options.
      '';
    };

    extraOptions = mkOption {
      type = types.lines;
      default = "";
      example = ''
        keep-outputs = true
        keep-derivations = true
      '';
      description = ''
        Additional text appended verbatim to /etc/nix/nix.conf.

        Use this for options not covered by nix.settings.
      '';
    };

    nixPath = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [
        "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos"
        "/nix/var/nix/profiles/per-user/root/channels"
      ];
      description = ''
        Default Nix expression search path entries.

        Rendered as the nix-path setting in nix.conf.
      '';
    };

    nrBuildUsers = mkOption {
      type = types.int;
      default = 32;
      description = ''
        Number of nixbld user accounts to create for secure concurrent builds.

        Each parallel build runs as a separate nixbld user.
      '';
    };

    gc = {
      automatic = mkOption {
        type = types.bool;
        default = false;
        description = "Whether to run nix garbage collection automatically.";
      };

      dates = mkOption {
        type = types.str;
        default = "weekly";
        example = "03:15";
        description = ''
          Schedule for automatic garbage collection.

          Accepts calendar specs like "daily", "weekly", "monthly",
          or systemd OnCalendar syntax like "03:15", "Mon..Fri 02:00".
        '';
      };

      options = mkOption {
        type = types.str;
        default = "--delete-older-than 30d";
        example = "--max-freed 1G";
        description = "Options passed to nix-collect-garbage.";
      };

      persistent = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to catch up on missed GC runs after sleep/shutdown.";
      };

      randomizedDelay = mkOption {
        type = types.nullOr types.int;
        default = null;
        example = 1800;
        description = "Random delay in seconds before GC to prevent thundering herd.";
      };
    };

    optimise = {
      automatic = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to automatically optimise the Nix store (deduplicate via hard links).
        '';
      };

      dates = mkOption {
        type = types.str;
        default = "03:45";
        example = "weekly";
        description = "Schedule for automatic store optimization (calendar spec).";
      };

      persistent = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to catch up on missed optimise runs.";
      };
    };

    channel = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to enable the default Nix channel.";
      };
    };
  };

  config = {
    # Default sane settings
    nix.settings = {
      max-jobs = mkDefault "auto";
      cores = mkDefault 0;
      sandbox = mkDefault true;
      experimental-features = mkDefault "nix-command flakes";
    };

    # Generate /etc/nix/nix.conf
    environment.etc."nix/nix.conf".text = ''
      # Generated by ekaos nix-daemon module
      ${nixConf}
      ${nixPathConf}
      ${optionalString (cfg.extraOptions != "") ''

        # Extra options
        ${cfg.extraOptions}
      ''}
    '';

    # Create nix directories and build users
    system.activationScripts.nix-daemon = stringAfter [ "etc" ] ''
      mkdir -p /etc/nix
      mkdir -p /nix/var/nix/profiles/per-user
      mkdir -p /nix/var/nix/gcroots/per-user

      # Ensure nixbld group exists and create build users
      ${optionalString (cfg.nrBuildUsers > 0) ''
        for i in $(seq 1 ${toString cfg.nrBuildUsers}); do
          if ! id "nixbld$i" >/dev/null 2>&1; then
            echo "Build user nixbld$i should be created by user management"
          fi
        done
      ''}
    '';

    # Build users
    users.groups.nixbld = mkIf (cfg.nrBuildUsers > 0) {
      gid = 30000;
      members = genList (i: "nixbld${toString (i + 1)}") cfg.nrBuildUsers;
    };

    users.users = mkIf (cfg.nrBuildUsers > 0) (
      listToAttrs (
        genList (
          i:
          let
            n = i + 1;
          in
          nameValuePair "nixbld${toString n}" {
            uid = 30000 + n;
            group = "nixbld";
            description = "Nix build user ${toString n}";
            isSystemUser = true;
            home = "/var/empty";
            shell = "/run/current-system/sw/bin/nologin";
          }
        ) cfg.nrBuildUsers
      )
    );

    # Automatic GC via timers
    timers.nix-gc = mkIf cfg.gc.automatic {
      enable = true;
      description = "Nix garbage collection";
      schedule.calendar = cfg.gc.dates;
      schedule.persistent = cfg.gc.persistent;
      schedule.randomDelay = cfg.gc.randomizedDelay;
      script = "${cfg.package}/bin/nix-collect-garbage ${cfg.gc.options}";
      user = "root";
    };

    # Automatic store optimization via timers
    timers.nix-optimise = mkIf cfg.optimise.automatic {
      enable = true;
      description = "Nix store optimization";
      schedule.calendar = cfg.optimise.dates;
      schedule.persistent = cfg.optimise.persistent;
      script = "${cfg.package}/bin/nix store optimise";
      user = "root";
    };
  };
}
