# Nix daemon configuration
# Generates /etc/nix/nix.conf
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.nix;

  # Format a nix.conf value
  formatValue =
    v:
    if isBool v then
      (if v then "true" else "false")
    else if isList v then
      concatStringsSep " " (map toString v)
    else
      toString v;

  # Generate nix.conf from settings
  nixConf = concatStringsSep "\n" (
    mapAttrsToList (name: value: "${name} = ${formatValue value}") cfg.settings
  );

in

{
  options.nix = {
    settings = mkOption {
      type = types.attrsOf (
        types.oneOf [
          types.bool
          types.int
          types.str
          types.path
          (types.listOf types.str)
        ]
      );
      default = { };
      example = literalExpression ''
        {
          max-jobs = 4;
          cores = 0;
          sandbox = true;
          auto-optimise-store = true;
          substituters = [ "https://cache.nixos.org" ];
          trusted-public-keys = [ "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" ];
        }
      '';
      description = ''
        Nix daemon settings written to /etc/nix/nix.conf.
        See nix.conf(5) for available options.
      '';
    };

    gc = {
      automatic = mkOption {
        type = types.bool;
        default = false;
        description = "Whether to run nix garbage collection automatically.";
      };

      schedule = mkOption {
        type = types.str;
        default = "weekly";
        example = "daily";
        description = "How often to run automatic garbage collection (cron-style or systemd calendar).";
      };

      options = mkOption {
        type = types.str;
        default = "--delete-older-than 30d";
        example = "--max-freed 1G";
        description = "Options passed to nix-collect-garbage.";
      };
    };

    channel = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to enable the default Nix channel.";
      };
    };
  };

  config = {
    # Default sane settings
    nix.settings = {
      max-jobs = mkDefault "auto";
      cores = mkDefault 0;
      sandbox = mkDefault true;
      experimental-features = mkDefault "nix-command flakes";
    };

    # Generate /etc/nix/nix.conf
    environment.etc."nix/nix.conf".text = ''
      # Generated by ekaos nix-daemon module
      ${nixConf}
      ${optionalString (cfg.gc.automatic) ''

        # GC is managed by a separate timer/cron job
      ''}
    '';

    # Create nix directories
    system.activationScripts.nix-daemon = stringAfter [ "etc" ] ''
      mkdir -p /etc/nix
      mkdir -p /nix/var/nix/profiles/per-user
      mkdir -p /nix/var/nix/gcroots/per-user
    '';

    # Set up automatic GC via cron if enabled
    services.crond.systemCronJobs = mkIf cfg.gc.automatic (mkAfter ''
      # Nix garbage collection
      0 3 * * ${
        if cfg.gc.schedule == "daily" then
          "*"
        else if cfg.gc.schedule == "weekly" then
          "0"
        else
          "0"
      } root ${pkgs.nix}/bin/nix-collect-garbage ${cfg.gc.options}
    '');
  };
}
