# Adios port of ekaos/modules/hardware/facter/default.nix.
# TODO(adios-cutover) notes below mark semantics changed in translation.
#
# NOTE: this file defines its own options (enable/report/reportPath) in
# addition to legacy `imports`, so per spec it is ported normally
# (options-only) rather than aggregator-dropped.
# TODO(adios-cutover): legacy `imports` of the 27 facter child modules
# dropped; covered by tree nodes parent.hardware.facter.<child>.
{ types, ... }:

{
  options = {
    enable = {
      type = types.bool;
      defaultFunc = { options, ... }: options.report != { };
      description = ''
        Whether to enable automatic hardware configuration using a
        report generated by nixos-facter.

        To generate a report, run as root:
          nix-shell -p nixos-facter --run nixos-facter > facter.json

        Then set hardware.facter.reportPath = ./facter.json in your config.
      '';
    };

    report = {
      type = types.attrsOf types.any;
      defaultFunc =
        { options, ... }:
        if options.reportPath == null then
          { }
        else
          builtins.fromJSON (builtins.readFile options.reportPath);
      description = "Hardware report data generated by nixos-facter.";
    };

    reportPath = {
      type = types.nullOr types.pathLike;
      default = null;
      description = ''
        Path to a hardware report generated by nixos-facter.

        To generate a report, run the following as root:
          nix-shell -p nixos-facter --run nixos-facter > facter.json
      '';
    };
  };

  impl = { ... }: { };
}
