# Translate structured tmpfiles rules to shell script
# Used by runit, launchd, and BSD rc.d platforms
{ lib, pkgs }:

let
  inherit (lib) concatMapStringsSep optionalString;

  # Convert a structured rule to shell commands
  ruleToShellCommands =
    rule:
    if rule.type == "directory" then
      ''
        mkdir -p ${rule.path}
        chmod ${rule.mode} ${rule.path}
        chown ${rule.user}:${rule.group} ${rule.path}
      ''
    else if rule.type == "file" then
      ''
        ${optionalString (rule.content != null) ''
          if [ ! -f ${rule.path} ]; then
            echo ${lib.escapeShellArg rule.content} > ${rule.path}
          fi
        ''}
        ${optionalString (rule.content == null) ''
          touch ${rule.path}
        ''}
        chmod ${rule.mode} ${rule.path}
        chown ${rule.user}:${rule.group} ${rule.path}
      ''
    else if rule.type == "symlink" then
      ''
        ln -sf ${rule.target} ${rule.path}
      ''
    else if rule.type == "remove" then
      ''
        rm -rf ${rule.path} 2>/dev/null || true
      ''
    else if rule.type == "recursive-permissions" then
      ''
        if [ -e ${rule.path} ]; then
          chmod -R ${rule.mode} ${rule.path}
          chown -R ${rule.user}:${rule.group} ${rule.path}
        fi
      ''
    else
      "# Unknown rule type: ${rule.type}";

in
{
  # Generate a shell script from tmpfiles rules
  toShellScript =
    name: rules:
    pkgs.writeShellScript "${name}-tmpfiles" ''
      # Generated by ekaos tmpfiles translator
      # Ensure paths exist with correct ownership and permissions
      ${concatMapStringsSep "\n" ruleToShellCommands rules}
    '';

  # Generate shell commands as text (for embedding in preStart etc.)
  toShellCommands = rules: concatMapStringsSep "\n" ruleToShellCommands rules;
}
