{
  stdenv,
  lib,
  elixir,
  erlang,
  hex,
  git,
  rebar,
  rebar3,
  findutils,
  makeWrapper,
  coreutils,
  gnused,
  gnugrep,
  gawk,
  mixBuildDirHook,
}:

lib.extendMkDerivation {
  constructDrv = stdenv.mkDerivation;

  excludeDrvArgNames = [
    "compileFlags"
    "erlangCompilerOptions"
    "mixNixDeps"
  ];

  extendDrvArgs =
    finalAttrs:
    {
      pname,
      version,
      src,
      nativeBuildInputs ? [ ],
      buildInputs ? [ ],
      meta ? { },
      enableDebugInfo ? false,
      mixEnv ? "prod",
      mixTarget ? "host",
      compileFlags ? [ ],
      mixReleaseName ? "",
      escriptBinName ? null,

      erlangCompilerOptions ? [ ],
      erlangDeterministicBuilds ? true,

      # Mix dependencies provided as a fixed output derivation
      mixFodDeps ? null,

      # Mix dependencies generated by mix2nix
      mixNixDeps ? { },

      # Remove releases/COOKIE
      removeCookie ? true,

      stripDebug ? false,

      ...
    }@attrs:
    assert mixNixDeps != { } -> mixFodDeps == null;
    assert stripDebug -> !enableDebugInfo;
    assert escriptBinName != null -> mixReleaseName == "";
    {
      nativeBuildInputs =
        nativeBuildInputs
        ++ [
          erlang
          elixir
          hex
          git
          mixBuildDirHook
        ]
        ++ (builtins.attrValues mixNixDeps)
        ++ [
          findutils
          makeWrapper
        ];

      buildInputs = buildInputs ++ lib.optionals (escriptBinName != null) [ erlang ];

      __darwinAllowLocalNetworking = true;

      env = {
        MIX_ENV = mixEnv;
        MIX_TARGET = mixTarget;
        MIX_BUILD_PREFIX = (if mixTarget == "host" then "" else "${mixTarget}_") + "${mixEnv}";
        MIX_DEBUG = if enableDebugInfo then 1 else 0;
        HEX_OFFLINE = 1;

        DEBUG = if enableDebugInfo then 1 else 0; # for Rebar3 compilation
        MIX_REBAR = "${rebar}/bin/rebar";
        MIX_REBAR3 = "${rebar3}/bin/rebar3";

        ERL_COMPILER_OPTIONS =
          let
            options = erlangCompilerOptions ++ lib.optionals erlangDeterministicBuilds [ "deterministic" ];
          in
          "[${lib.concatStringsSep "," options}]";

        LANG = if stdenv.hostPlatform.isLinux then "C.UTF-8" else "C";
        LC_CTYPE = if stdenv.hostPlatform.isLinux then "C.UTF-8" else "UTF-8";
      }
      // (attrs.env or { });

      postUnpack = ''
        # Mix and Hex
        export MIX_HOME="$TEMPDIR/mix"
        export HEX_HOME="$TEMPDIR/hex"

        # Rebar
        export REBAR_GLOBAL_CONFIG_DIR="$TEMPDIR/rebar3"
        export REBAR_CACHE_DIR="$TEMPDIR/rebar3.cache"

        ${lib.optionalString (mixFodDeps != null) ''
          # Compilation of the dependencies will require that the dependency path is
          # writable, thus a copy to the $TEMPDIR is inevitable here.
          export MIX_DEPS_PATH="$TEMPDIR/deps"
          cp --no-preserve=mode -R "${mixFodDeps}" "$MIX_DEPS_PATH"
        ''}
      ''
      + (attrs.postUnpack or "");

      configurePhase =
        attrs.configurePhase or ''
          runHook preConfigure

          mix deps.compile --no-deps-check --skip-umbrella-children

          ${lib.optionalString (mixNixDeps != { }) ''
            mkdir -p deps

            ${lib.concatMapAttrsStringSep "\n" (name: dep: ''
              dep_path="deps/${name}"
              if [ -d "${dep}/src" ]; then
                ln -sv ${dep}/src $dep_path
              fi
            '') mixNixDeps}
          ''}

          ${lib.optionalString (mixFodDeps != null) ''
            ln -s "$MIX_DEPS_PATH" ./deps
          ''}

          runHook postConfigure
        '';

      buildPhase =
        attrs.buildPhase or ''
          runHook preBuild

          mix compile --no-deps-check ${lib.concatStringsSep " " compileFlags}

          ${lib.optionalString (escriptBinName != null) ''
            mix escript.build --no-deps-check
          ''}

          runHook postBuild
        '';

      installPhase =
        attrs.installPhase or ''
          runHook preInstall

          ${
            if (escriptBinName != null) then
              ''
                mkdir -p $out/bin
                cp ${escriptBinName} $out/bin
              ''
            else
              ''
                mix release ${mixReleaseName} --no-deps-check --path "$out"
              ''
          }

          runHook postInstall
        '';

      postFixup = ''
        echo "removing files for Microsoft Windows"
        rm -f "$out"/bin/*.bat

        echo "wrapping programs in $out/bin with their runtime deps"
        for f in $(find $out/bin/ -type f -executable); do
          wrapProgram "$f" \
            --prefix PATH : ${
              lib.makeBinPath [
                coreutils
                gnused
                gnugrep
                gawk
              ]
            }
        done
      ''
      + lib.optionalString removeCookie ''
        if [ -e $out/releases/COOKIE ]; then
          echo "removing $out/releases/COOKIE"
          rm $out/releases/COOKIE
        fi
      ''
      + ''
        if [ -e $out/erts-* ]; then
          # ERTS is included in the release — remove references to erlang to reduce
          # closure size. Note: bbe and ripgrep are used in nixpkgs for binary
          # substitution but are not yet available here; only plain-text references
          # are cleaned up for now.
          for file in $(grep -rl "${erlang}/lib/erlang" "$out" --include='*.sh' --include='*.config' --include='*.script' 2>/dev/null || true); do
            echo "removing references to erlang in $file"
            substituteInPlace "$file" --replace "${erlang}/lib/erlang" "$out"
          done
        fi
      ''
      + lib.optionalString stripDebug ''
        erl -noinput -eval 'lists:foreach(fun(F) -> io:format("Stripping ~p.~n", [F]), beam_lib:strip(F) end, filelib:wildcard("'"$out"'/**/*.beam"))' -s init stop
      '';
    };
}
