{
  version,
  src-hash,
  withCMake ? true,
  ...
}:

{
  lib,
  stdenv,
  fetchurl,
  updateAutotoolsGnuConfigScriptsHook,
  cmake,

  # sensitive downstream packages
  curl,
  grpc, # consumes cmake config
}:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

stdenv.mkDerivation (finalAttrs: {
  pname = "c-ares";
  inherit version;

  src = fetchurl {
    # Note: tag name varies in some versions, e.g. v1.30.0, c-ares-1_17_0.
    url = "https://github.com/c-ares/c-ares/releases/download/v${finalAttrs.version}/c-ares-${finalAttrs.version}.tar.gz";
    hash = src-hash;
  };

  outputs = [
    "out"
    "dev"
    "man"
  ];

  nativeBuildInputs = [
    updateAutotoolsGnuConfigScriptsHook
  ]
  ++ lib.optionals withCMake [
    cmake.minimal
    cmake.configurePhaseHook
  ];

  cmakeFlags =
    [ ]
    ++ lib.optionals stdenv.hostPlatform.isStatic [
      "-DCARES_SHARED=OFF"
      "-DCARES_STATIC=ON"
    ];

  enableParallelBuilding = true;

  doCheck = false;

  passthru.tests = {
    inherit grpc;
    curl = (curl.override { c-aresSupport = true; }).tests.withCheck;
    unit = finalAttrs.finalPackage.overrideAttrs { doCheck = true; };
  };

  preFixup = lib.optionalString withCMake ''
    substituteInPlace $out/lib/pkgconfig/libcares.pc --replace-fail \''${prefix}/ ""
  '';

  meta = {
    description = "C library for asynchronous DNS requests";
    homepage = "https://c-ares.haxx.se";
    changelog = "https://c-ares.org/changelog.html#${
      lib.replaceStrings [ "." ] [ "_" ] finalAttrs.version
    }";
    license = lib.licenses.mit;
    platforms = lib.platforms.all;
  };
})
