# System-wide tmux configuration
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.programs.tmux;

  tmuxConf = pkgs.writeText "tmux.conf" ''
    # Generated by ekaos tmux module
    set -g default-terminal "${cfg.terminal}"
    set -g history-limit ${toString cfg.historyLimit}
    set -g base-index ${toString cfg.baseIndex}
    set -g escape-time ${toString cfg.escapeTime}
    ${optionalString (cfg.keyMode != null) "set -g mode-keys ${cfg.keyMode}"}
    ${optionalString (cfg.shortcut != "b") ''
      unbind C-b
      set -g prefix C-${cfg.shortcut}
      bind C-${cfg.shortcut} send-prefix
    ''}
    ${optionalString cfg.clock24 "set -g clock-mode-style 24"}
    ${optionalString cfg.mouse "set -g mouse on"}
    ${optionalString cfg.secureSocket ''
      set-environment -g TMUX_TMPDIR "/run/tmux"
    ''}
    ${cfg.extraConfig}
  '';

in

{
  options.programs.tmux = {
    enable = mkOption {
      type = types.bool;
      default = false;
      description = "Whether to install and configure tmux system-wide.";
    };

    package = mkOption {
      type = types.package;
      default = pkgs.tmux;
      description = "tmux package to use.";
    };

    terminal = mkOption {
      type = types.str;
      default = "screen-256color";
      description = "Default terminal type.";
    };

    historyLimit = mkOption {
      type = types.ints.positive;
      default = 10000;
      description = "Maximum number of lines in scrollback buffer.";
    };

    baseIndex = mkOption {
      type = types.ints.unsigned;
      default = 0;
      description = "Base index for windows and panes.";
    };

    escapeTime = mkOption {
      type = types.ints.unsigned;
      default = 500;
      description = "Time in milliseconds to wait after an escape key press.";
    };

    keyMode = mkOption {
      type = types.nullOr (
        types.enum [
          "emacs"
          "vi"
        ]
      );
      default = null;
      description = "Key binding mode. null uses tmux default (emacs).";
    };

    shortcut = mkOption {
      type = types.str;
      default = "b";
      example = "a";
      description = "Prefix key (used as Ctrl+<shortcut>).";
    };

    clock24 = mkOption {
      type = types.bool;
      default = false;
      description = "Whether to use 24-hour clock.";
    };

    mouse = mkOption {
      type = types.bool;
      default = false;
      description = "Whether to enable mouse support.";
    };

    secureSocket = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Whether to store tmux sockets under /run (which is more secure
        than the default /tmp).
      '';
    };

    plugins = mkOption {
      type = types.listOf types.package;
      default = [ ];
      description = "tmux plugins to install.";
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = "Extra configuration appended to /etc/tmux.conf.";
    };
  };

  config = mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ] ++ cfg.plugins;

    environment.etc."tmux.conf".source = tmuxConf;

    # Create secure socket directory
    system.activationScripts.tmux = mkIf cfg.secureSocket (
      stringAfter [ "etc" ] ''
        mkdir -p /run/tmux
        chmod 1777 /run/tmux
      ''
    );
  };
}
