# Raw adios tree entry point (no fragment merging).
#
# For building systems, use ../eval-config.nix (or ../default.nix) instead,
# which merges every module's impl output into a config attrset.
#
# Usage:
#
# ```nix
# let
#   tree = import ./ekaos/adios { inherit adios pkgs; };
# in
# {
#   kernel = tree.modules.boot.modules.kernel { kernelParams = [ "quiet" ]; };
#   getty = tree.modules.services.modules.getty { ttyCount = 4; };
# }
# ```
#
# `adios` is the `lladaios` flake input. `pkgs` is threaded through to
# modules that need it (destructured as `{ types, lib, pkgs, ... }:` where
# `lib` is adios.lib with the merge helpers).
# Tree layout is generated by ./gen-tree.py into ./modules-tree.nix from
# ../modules/ — re-run it after adding/removing modules.
{ adios, pkgs ? null }:

(adios {
  modules = import ./modules-tree.nix { inherit adios pkgs; };
}) { }
