#!/usr/bin/env python3
"""Generate ekaos/adios/modules-tree.nix from ekaos/modules/.

Walks all *.nix files under ekaos/modules/ (minus EXCLUDES) and builds a
nested adios `modules` attrset mirroring the directory structure:

  modules/boot/kernel.nix            -> modules.boot.modules.kernel
  modules/networking.nix             -> modules.networking
  modules/hardware/facter/cpu.nix    -> modules.hardware.modules.facter.modules.cpu
  modules/<dir>/default.nix          -> own content of the <dir> node
  modules/<stem>.nix + <stem>/ dir   -> file becomes own content of <stem> node
                                       (e.g. networking.nix + networking/)

A node's own content (if any) is merged with its children via
adios.lib.inject. Namespace nodes without their own file get no options/impl.

Usage: python3 gen-tree.py   (run from ekaos/adios/)
Writes: modules-tree.nix
"""

import re
from pathlib import Path

HERE = Path(__file__).parent
MODULES = HERE.parent / "modules"
OUT = HERE / "modules-tree.nix"

# Verbatim-copied non-module files (package builders, plain helpers).
# These are importable relatively but must NOT become tree nodes.
EXCLUDES = {
    "security/wrappers/wrapper.nix",
}


def attr(name: str) -> str:
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_']*", name):
        return name
    return '"' + name.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    files = sorted(
        p.relative_to(MODULES).as_posix()
        for p in MODULES.rglob("*.nix")
        if p.relative_to(MODULES).as_posix() not in EXCLUDES
    )
    if not files:
        raise SystemExit("no modules found under %s" % MODULES)

    # nodes: dirname-tuple -> {"own": relpath|None, "children": set(stem)}
    nodes: dict[tuple, dict] = {}

    def node(path: tuple) -> dict:
        return nodes.setdefault(path, {"own": None, "children": set()})

    node(())
    for rel in files:
        parts = Path(rel).parts
        parent = parts[:-1]
        for i in range(1, len(parent) + 1):
            node(parent[:i])
            node(parent[: i - 1])["children"].add(parent[i - 1])
        if parts[-1] == "default.nix":
            node(parent)["own"] = rel
        else:
            stem = parts[-1][: -len(".nix")]
            if (MODULES.joinpath(*parent, stem)).is_dir():
                # file + same-named dir: file is the node's own content
                node(parent + (stem,))["own"] = rel
            else:
                node(parent)["children"].add(stem)
                node(parent + (stem,))

    lines: list[str] = []
    lines.append("# GENERATED by gen-tree.py — do not edit.")
    lines.append("# Mirrors ekaos/modules/ as a nested adios modules tree.")
    lines.append("{ adios, pkgs }:")
    lines.append("let")
    lines.append("  args = adios // { inherit pkgs; };")
    lines.append("in")
    lines.append("{")

    def emit_node(path: tuple, indent: int) -> None:
        n = node(path)
        pad = "  " * indent
        if n["own"] is not None and not n["children"]:
            lines.append(f"{pad}(import ../modules/{n['own']} args)")
            return
        lines.append(f"{pad}(adios.lib.inject [")
        if n["own"] is not None:
            lines.append(f"{pad}  (import ../modules/{n['own']} args)")
        else:
            lines.append(f"{pad}  {{ }}")
        lines.append(f"{pad}  {{ modules = {{")
        for child in sorted(n["children"]):
            child_path = path + (child,)
            c = node(child_path)
            cpad = "  " * (indent + 2)
            if c["own"] is None and not c["children"]:
                rel = "/".join([*path, child]) + ".nix"
                lines.append(f"{cpad}{attr(child)} = (import ../modules/{rel} args);")
            else:
                lines.append(f"{cpad}{attr(child)} =")
                emit_node(child_path, indent + 3)
                lines[-1] += ";"
        lines.append(f"{pad}  }}; }}")
        lines.append(f"{pad}])")

    for child in sorted(node(() )["children"]):
        child_path = (child,)
        c = node(child_path)
        if c["own"] is None and not c["children"]:
            lines.append(f"  {attr(child)} = (import ../modules/{child}.nix args);")
        else:
            lines.append(f"  {attr(child)} =")
            emit_node(child_path, 2)
            lines[-1] += ";"
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(files)} modules)")


if __name__ == "__main__":
    main()
