# GENERATED by gen-tree.py — do not edit.
# Mirrors ekaos/modules/ as a nested adios modules tree.
{ adios, pkgs }:
let
  args = adios // { inherit pkgs; };
in
{
  boot =
    (adios.lib.inject [
      { }
      { modules = {
        binfmt = (import ../modules/boot/binfmt.nix args);
        bootspec = (import ../modules/boot/bootspec.nix args);
        containers = (import ../modules/boot/containers.nix args);
        "crash-dump" = (import ../modules/boot/crash-dump.nix args);
        "grow-partition" = (import ../modules/boot/grow-partition.nix args);
        initrd = (import ../modules/boot/initrd.nix args);
        kernel = (import ../modules/boot/kernel.nix args);
        kexec = (import ../modules/boot/kexec.nix args);
        modprobe = (import ../modules/boot/modprobe.nix args);
        plymouth = (import ../modules/boot/plymouth.nix args);
        "stage-2" = (import ../modules/boot/stage-2.nix args);
        swraid = (import ../modules/boot/swraid.nix args);
        "systemd-boot" = (import ../modules/boot/systemd-boot.nix args);
        zfs = (import ../modules/boot/zfs.nix args);
        zswap = (import ../modules/boot/zswap.nix args);
      }; }
    ]);
  config =
    (adios.lib.inject [
      { }
      { modules = {
        coredump = (import ../modules/config/coredump.nix args);
        fonts = (import ../modules/config/fonts.nix args);
        home = (import ../modules/config/home.nix args);
        "kernel-profile" = (import ../modules/config/kernel-profile.nix args);
        locale = (import ../modules/config/locale.nix args);
        "nix-daemon" = (import ../modules/config/nix-daemon.nix args);
        nixpkgs = (import ../modules/config/nixpkgs.nix args);
        nsswitch = (import ../modules/config/nsswitch.nix args);
        power = (import ../modules/config/power.nix args);
        "shell-environment" = (import ../modules/config/shell-environment.nix args);
        sysctl = (import ../modules/config/sysctl.nix args);
        "systemd-units" = (import ../modules/config/systemd-units.nix args);
        "user-services" = (import ../modules/config/user-services.nix args);
        "users-groups" = (import ../modules/config/users-groups.nix args);
        xdg =
          (adios.lib.inject [
            { }
            { modules = {
              autostart = (import ../modules/config/xdg/autostart.nix args);
              icons = (import ../modules/config/xdg/icons.nix args);
              menus = (import ../modules/config/xdg/menus.nix args);
              mime = (import ../modules/config/xdg/mime.nix args);
              portal = (import ../modules/config/xdg/portal.nix args);
              sounds = (import ../modules/config/xdg/sounds.nix args);
              "terminal-exec" = (import ../modules/config/xdg/terminal-exec.nix args);
            }; }
          ]);
      }; }
    ]);
  hardware =
    (adios.lib.inject [
      { }
      { modules = {
        cpu = (import ../modules/hardware/cpu.nix args);
        facter =
          (adios.lib.inject [
            (import ../modules/hardware/facter/default.nix args)
            { modules = {
              audio = (import ../modules/hardware/facter/audio.nix args);
              bluetooth = (import ../modules/hardware/facter/bluetooth.nix args);
              "bluetooth-stack" = (import ../modules/hardware/facter/bluetooth-stack.nix args);
              boot = (import ../modules/hardware/facter/boot.nix args);
              camera = (import ../modules/hardware/facter/camera.nix args);
              cpu = (import ../modules/hardware/facter/cpu.nix args);
              disk = (import ../modules/hardware/facter/disk.nix args);
              fingerprint = (import ../modules/hardware/facter/fingerprint.nix args);
              firmware = (import ../modules/hardware/facter/firmware.nix args);
              "firmware-split" = (import ../modules/hardware/facter/firmware-split.nix args);
              fwupd = (import ../modules/hardware/facter/fwupd.nix args);
              gaming = (import ../modules/hardware/facter/gaming.nix args);
              gpu = (import ../modules/hardware/facter/gpu.nix args);
              graphics = (import ../modules/hardware/facter/graphics.nix args);
              keyboard = (import ../modules/hardware/facter/keyboard.nix args);
              laptop = (import ../modules/hardware/facter/laptop.nix args);
              lib = (import ../modules/hardware/facter/lib.nix args);
              networking = (import ../modules/hardware/facter/networking.nix args);
              nvidia = (import ../modules/hardware/facter/nvidia.nix args);
              power = (import ../modules/hardware/facter/power.nix args);
              printing = (import ../modules/hardware/facter/printing.nix args);
              scanner = (import ../modules/hardware/facter/scanner.nix args);
              system = (import ../modules/hardware/facter/system.nix args);
              thermal = (import ../modules/hardware/facter/thermal.nix args);
              thunderbolt = (import ../modules/hardware/facter/thunderbolt.nix args);
              touchscreen = (import ../modules/hardware/facter/touchscreen.nix args);
              trackpoint = (import ../modules/hardware/facter/trackpoint.nix args);
              virtualisation = (import ../modules/hardware/facter/virtualisation.nix args);
            }; }
          ]);
        firmware = (import ../modules/hardware/firmware.nix args);
        ipu6 = (import ../modules/hardware/ipu6.nix args);
        ipu7 = (import ../modules/hardware/ipu7.nix args);
        nvidia = (import ../modules/hardware/nvidia.nix args);
        sensor =
          (adios.lib.inject [
            { }
            { modules = {
              iio = (import ../modules/hardware/sensor/iio.nix args);
            }; }
          ]);
        trackpoint = (import ../modules/hardware/trackpoint.nix args);
      }; }
    ]);
  installer =
    (adios.lib.inject [
      { }
      { modules = {
        "hardware-profile" = (import ../modules/installer/hardware-profile.nix args);
        "installation-cd-base" = (import ../modules/installer/installation-cd-base.nix args);
        "iso-image" = (import ../modules/installer/iso-image.nix args);
      }; }
    ]);
  languages =
    (adios.lib.inject [
      { }
      { modules = {
        bun = (import ../modules/languages/bun.nix args);
        c = (import ../modules/languages/c.nix args);
        clojure = (import ../modules/languages/clojure.nix args);
        cplusplus = (import ../modules/languages/cplusplus.nix args);
        crystal = (import ../modules/languages/crystal.nix args);
        cue = (import ../modules/languages/cue.nix args);
        deno = (import ../modules/languages/deno.nix args);
        dotnet = (import ../modules/languages/dotnet.nix args);
        elixir = (import ../modules/languages/elixir.nix args);
        erlang = (import ../modules/languages/erlang.nix args);
        fortran = (import ../modules/languages/fortran.nix args);
        gawk = (import ../modules/languages/gawk.nix args);
        gleam = (import ../modules/languages/gleam.nix args);
        go = (import ../modules/languages/go.nix args);
        guile = (import ../modules/languages/guile.nix args);
        hare = (import ../modules/languages/hare.nix args);
        haskell = (import ../modules/languages/haskell.nix args);
        idris = (import ../modules/languages/idris.nix args);
        java = (import ../modules/languages/java.nix args);
        javascript = (import ../modules/languages/javascript.nix args);
        jsonnet = (import ../modules/languages/jsonnet.nix args);
        julia = (import ../modules/languages/julia.nix args);
        kotlin = (import ../modules/languages/kotlin.nix args);
        lean = (import ../modules/languages/lean.nix args);
        lib = (import ../modules/languages/lib.nix args);
        lobster = (import ../modules/languages/lobster.nix args);
        lua = (import ../modules/languages/lua.nix args);
        nim = (import ../modules/languages/nim.nix args);
        nix = (import ../modules/languages/nix.nix args);
        nodejs = (import ../modules/languages/nodejs.nix args);
        ocaml = (import ../modules/languages/ocaml.nix args);
        odin = (import ../modules/languages/odin.nix args);
        opentofu = (import ../modules/languages/opentofu.nix args);
        perl = (import ../modules/languages/perl.nix args);
        php = (import ../modules/languages/php.nix args);
        pkl = (import ../modules/languages/pkl.nix args);
        purescript = (import ../modules/languages/purescript.nix args);
        python = (import ../modules/languages/python.nix args);
        "r-lang" = (import ../modules/languages/r-lang.nix args);
        racket = (import ../modules/languages/racket.nix args);
        raku = (import ../modules/languages/raku.nix args);
        ruby = (import ../modules/languages/ruby.nix args);
        rust = (import ../modules/languages/rust.nix args);
        scala = (import ../modules/languages/scala.nix args);
        shell = (import ../modules/languages/shell.nix args);
        sml = (import ../modules/languages/sml.nix args);
        solidity = (import ../modules/languages/solidity.nix args);
        tcl = (import ../modules/languages/tcl.nix args);
        terraform = (import ../modules/languages/terraform.nix args);
        texlive = (import ../modules/languages/texlive.nix args);
        typescript = (import ../modules/languages/typescript.nix args);
        typst = (import ../modules/languages/typst.nix args);
        unison = (import ../modules/languages/unison.nix args);
        vala = (import ../modules/languages/vala.nix args);
        vlang = (import ../modules/languages/vlang.nix args);
        zig = (import ../modules/languages/zig.nix args);
      }; }
    ]);
  misc =
    (adios.lib.inject [
      { }
      { modules = {
        assertions = (import ../modules/misc/assertions.nix args);
        defaults = (import ../modules/misc/defaults.nix args);
      }; }
    ]);
  monitoring =
    (adios.lib.inject [
      { }
      { modules = {
        "prometheus-scrape" = (import ../modules/monitoring/prometheus-scrape.nix args);
      }; }
    ]);
  "network-interfaces" = (import ../modules/network-interfaces.nix args);
  networking =
    (adios.lib.inject [
      (import ../modules/networking.nix args)
      { modules = {
        "dns-zones" = (import ../modules/networking/dns-zones.nix args);
        firewall = (import ../modules/networking/firewall.nix args);
        iproute2 = (import ../modules/networking/iproute2.nix args);
        nat = (import ../modules/networking/nat.nix args);
        nftables = (import ../modules/networking/nftables.nix args);
        "port-contracts" = (import ../modules/networking/port-contracts.nix args);
        wireguard = (import ../modules/networking/wireguard.nix args);
      }; }
    ]);
  programs =
    (adios.lib.inject [
      { }
      { modules = {
        git = (import ../modules/programs/git.nix args);
      }; }
    ]);
  security =
    (adios.lib.inject [
      { }
      { modules = {
        acme = (import ../modules/security/acme.nix args);
        audit = (import ../modules/security/audit.nix args);
        hardening = (import ../modules/security/hardening.nix args);
        pam = (import ../modules/security/pam.nix args);
        sudo = (import ../modules/security/sudo.nix args);
        wrappers =
          (import ../modules/security/wrappers/default.nix args);
      }; }
    ]);
  "service-managers" =
    (adios.lib.inject [
      { }
      { modules = {
        launchd = (import ../modules/service-managers/launchd.nix args);
        rcd = (import ../modules/service-managers/rcd.nix args);
        runit = (import ../modules/service-managers/runit.nix args);
        systemd = (import ../modules/service-managers/systemd.nix args);
      }; }
    ]);
  services =
    (adios.lib.inject [
      (import ../modules/services.nix args)
      { modules = {
        crond = (import ../modules/services/crond.nix args);
        databases =
          (adios.lib.inject [
            { }
            { modules = {
              postgresql = (import ../modules/services/databases/postgresql.nix args);
              redis = (import ../modules/services/databases/redis.nix args);
            }; }
          ]);
        dbus = (import ../modules/services/dbus.nix args);
        earlyoom = (import ../modules/services/earlyoom.nix args);
        fstrim = (import ../modules/services/fstrim.nix args);
        getty = (import ../modules/services/getty.nix args);
        hardware =
          (adios.lib.inject [
            { }
            { modules = {
              bolt = (import ../modules/services/hardware/bolt.nix args);
              fprintd = (import ../modules/services/hardware/fprintd.nix args);
              fwupd = (import ../modules/services/hardware/fwupd.nix args);
              "power-profiles-daemon" = (import ../modules/services/hardware/power-profiles-daemon.nix args);
              thermald = (import ../modules/services/hardware/thermald.nix args);
              udev = (import ../modules/services/hardware/udev.nix args);
            }; }
          ]);
        journald = (import ../modules/services/journald.nix args);
        monitoring =
          (adios.lib.inject [
            { }
            { modules = {
              prometheus = (import ../modules/services/monitoring/prometheus.nix args);
            }; }
          ]);
        networking =
          (adios.lib.inject [
            { }
            { modules = {
              bind = (import ../modules/services/networking/bind.nix args);
              dhcpcd = (import ../modules/services/networking/dhcpcd.nix args);
              dnsmasq = (import ../modules/services/networking/dnsmasq.nix args);
              modemmanager = (import ../modules/services/networking/modemmanager.nix args);
              networkmanager = (import ../modules/services/networking/networkmanager.nix args);
              nginx = (import ../modules/services/networking/nginx.nix args);
              pppd = (import ../modules/services/networking/pppd.nix args);
              "reverse-proxy" = (import ../modules/services/networking/reverse-proxy.nix args);
              sshd = (import ../modules/services/networking/sshd.nix args);
              unbound = (import ../modules/services/networking/unbound.nix args);
            }; }
          ]);
        "queued-build-hook" = (import ../modules/services/queued-build-hook.nix args);
        resolved = (import ../modules/services/resolved.nix args);
        stubs = (import ../modules/services/stubs.nix args);
        timesyncd = (import ../modules/services/timesyncd.nix args);
      }; }
    ]);
  system =
    (adios.lib.inject [
      { }
      { modules = {
        activation = (import ../modules/system/activation.nix args);
        etc = (import ../modules/system/etc.nix args);
        logind = (import ../modules/system/logind.nix args);
        "package-manifest" = (import ../modules/system/package-manifest.nix args);
        toplevel = (import ../modules/system/toplevel.nix args);
      }; }
    ]);
  tasks =
    (adios.lib.inject [
      { }
      { modules = {
        filesystems = (import ../modules/tasks/filesystems.nix args);
        swap = (import ../modules/tasks/swap.nix args);
        timers = (import ../modules/tasks/timers.nix args);
        tmpfiles = (import ../modules/tasks/tmpfiles.nix args);
      }; }
    ]);
  virtualisation =
    (adios.lib.inject [
      { }
      { modules = {
        containers = (import ../modules/virtualisation/containers.nix args);
        docker = (import ../modules/virtualisation/docker.nix args);
        libvirtd = (import ../modules/virtualisation/libvirtd.nix args);
        podman = (import ../modules/virtualisation/podman.nix args);
        "qemu-guest-agent" = (import ../modules/virtualisation/qemu-guest-agent.nix args);
        "qemu-vm" = (import ../modules/virtualisation/qemu-vm.nix args);
      }; }
    ]);
}
