# Networking configuration
# Handles basic network settings like hostname, domain, DNS
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.networking;

in

{
  options = {
    networking.hostName = mkOption {
      type = types.str;
      default = "ekaos";
      example = "myserver";
      description = ''
        The hostname of the system.

        This will be used to set /etc/hostname and will be included in /etc/hosts.
      '';
    };

    networking.domain = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "example.com";
      description = ''
        The domain name of the system.

        If set, the fully qualified domain name (FQDN) will be hostname.domain.
      '';
    };

    networking.nameservers = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [
        "8.8.8.8"
        "8.8.4.4"
      ];
      description = ''
        List of nameservers to use for DNS resolution.

        These will be written to /etc/resolv.conf.
      '';
    };

    networking.search = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [
        "example.com"
        "local"
      ];
      description = ''
        List of search domains for DNS resolution.
      '';
    };

    networking.extraHosts = mkOption {
      type = types.lines;
      default = "";
      example = ''
        192.168.1.100 server1.example.com server1
        192.168.1.101 server2.example.com server2
      '';
      description = ''
        Additional entries to add to /etc/hosts.
      '';
    };

    networking.useDHCP = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Whether to use DHCP for network configuration.

        When true, enables automatic network configuration via DHCP.
        When false, you must configure interfaces manually.
      '';
    };

    networking.defaultGateway = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "192.168.1.1";
      description = ''
        The default gateway for IPv4 traffic.

        Only used when useDHCP is false.
      '';
    };

    networking.defaultGateway6 = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "fe80::1";
      description = ''
        The default gateway for IPv6 traffic.

        Only used when useDHCP is false.
      '';
    };
  };

  config = {
    # hostname and hosts are already configured in etc.nix,
    # but we ensure they use our values
    environment.etc."hostname".text = mkForce cfg.hostName;

    environment.etc."hosts".text = mkForce (
      let
        fqdn = if cfg.domain != null then "${cfg.hostName}.${cfg.domain}" else cfg.hostName;
      in
      ''
        # Generated by ekaos networking module
        127.0.0.1 localhost
        ::1 localhost
        127.0.1.1 ${fqdn} ${cfg.hostName}

        ${cfg.extraHosts}
      ''
    );

    # Generate resolv.conf
    environment.etc."resolv.conf" = mkIf (cfg.nameservers != [ ]) {
      text = ''
        # Generated by ekaos networking module
        ${optionalString (cfg.search != [ ]) "search ${concatStringsSep " " cfg.search}"}
        ${concatMapStringsSep "\n" (ns: "nameserver ${ns}") cfg.nameservers}
      '';
    };

    # Add networking utilities
    environment.systemPackages = with pkgs; [
      iproute2
      iputils
      net-tools
    ];

    # Set hostname during activation
    system.activationScripts.hostname = stringAfter [ "etc" ] ''
      # Set system hostname
      echo "Setting hostname to ${cfg.hostName}..."
      ${pkgs.net-tools}/bin/hostname "${cfg.hostName}"
    '';
  };
}
