# Networking configuration
# Handles basic network settings like hostname, domain, DNS
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.networking;

in

{
  options = {
    networking.hostName = mkOption {
      type = types.str;
      default = "ekaos";
      example = "myserver";
      description = ''
        The hostname of the system.

        This will be used to set /etc/hostname and will be included in /etc/hosts.
      '';
    };

    networking.domain = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "example.com";
      description = ''
        The domain name of the system.

        If set, the fully qualified domain name (FQDN) will be hostname.domain.
      '';
    };

    networking.nameservers = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [
        "8.8.8.8"
        "8.8.4.4"
      ];
      description = ''
        List of nameservers to use for DNS resolution.

        These will be written to /etc/resolv.conf.
      '';
    };

    networking.search = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [
        "example.com"
        "local"
      ];
      description = ''
        List of search domains for DNS resolution.
      '';
    };

    networking.resolvconf = {
      extraOptions = mkOption {
        type = types.listOf types.str;
        default = [ ];
        example = [ "single-request" "edns0" ];
        description = ''
          Options to append to the resolv.conf options line.
          See resolv.conf(5) for available options.
        '';
      };

      dnsSingleRequest = mkOption {
        type = types.bool;
        default = false;
        description = "Whether to use single-request option to avoid some AAAA lookup issues.";
      };

      dnsExtensionMechanism = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to enable EDNS0 extension mechanism.";
      };
    };

    networking.extraHosts = mkOption {
      type = types.lines;
      default = "";
      example = ''
        192.168.1.100 server1.example.com server1
        192.168.1.101 server2.example.com server2
      '';
      description = ''
        Additional entries to add to /etc/hosts.
      '';
    };

    networking.enableIPv6 = mkOption {
      type = types.bool;
      default = true;
      description = "Whether to enable IPv6 support.";
    };

    networking.proxy = {
      default = mkOption {
        type = types.nullOr types.str;
        default = null;
        example = "http://proxy.example.com:8080";
        description = ''
          Default proxy URL used for HTTP, HTTPS, and FTP.
          Sets the http_proxy, https_proxy, and ftp_proxy environment variables.
        '';
      };

      noProxy = mkOption {
        type = types.nullOr types.str;
        default = null;
        example = "127.0.0.1,localhost,.example.com";
        description = "Comma-separated list of domains/IPs that bypass the proxy.";
      };

      httpProxy = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "HTTP proxy URL. Overrides networking.proxy.default for HTTP.";
      };

      httpsProxy = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "HTTPS proxy URL. Overrides networking.proxy.default for HTTPS.";
      };
    };

    networking.useDHCP = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Whether to use DHCP for network configuration.

        When true, enables automatic network configuration via DHCP.
        When false, you must configure interfaces manually.
      '';
    };

    networking.defaultGateway = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "192.168.1.1";
      description = ''
        The default gateway for IPv4 traffic.

        Only used when useDHCP is false.
      '';
    };

    networking.defaultGateway6 = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "fe80::1";
      description = ''
        The default gateway for IPv6 traffic.

        Only used when useDHCP is false.
      '';
    };
  };

  config = {
    # hostname and hosts are already configured in etc.nix,
    # but we ensure they use our values
    environment.etc."hostname".text = mkForce cfg.hostName;

    environment.etc."hosts".text = mkForce (
      let
        fqdn = if cfg.domain != null then "${cfg.hostName}.${cfg.domain}" else cfg.hostName;
      in
      ''
        # Generated by ekaos networking module
        127.0.0.1 localhost
        ::1 localhost
        127.0.1.1 ${fqdn} ${cfg.hostName}

        ${cfg.extraHosts}
      ''
    );

    # Generate resolv.conf
    environment.etc."resolv.conf" = mkIf (cfg.nameservers != [ ]) {
      text =
        let
          resolvOptions =
            cfg.resolvconf.extraOptions
            ++ optional cfg.resolvconf.dnsSingleRequest "single-request"
            ++ optional cfg.resolvconf.dnsExtensionMechanism "edns0";
        in
        ''
          # Generated by ekaos networking module
          ${optionalString (cfg.search != [ ]) "search ${concatStringsSep " " cfg.search}"}
          ${concatMapStringsSep "\n" (ns: "nameserver ${ns}") cfg.nameservers}
          ${optionalString (resolvOptions != [ ]) "options ${concatStringsSep " " resolvOptions}"}
        '';
    };

    # Disable IPv6 via sysctl if requested
    boot.kernel.sysctl = mkIf (!cfg.enableIPv6) {
      "net.ipv6.conf.all.disable_ipv6" = true;
      "net.ipv6.conf.default.disable_ipv6" = true;
    };

    # Set proxy environment variables
    environment.variables = mkMerge [
      (mkIf (cfg.proxy.default != null || cfg.proxy.httpProxy != null) {
        http_proxy = cfg.proxy.httpProxy or cfg.proxy.default;
      })
      (mkIf (cfg.proxy.default != null || cfg.proxy.httpsProxy != null) {
        https_proxy = cfg.proxy.httpsProxy or cfg.proxy.default;
      })
      (mkIf (cfg.proxy.noProxy != null) {
        no_proxy = cfg.proxy.noProxy;
      })
    ];

    # Add networking utilities
    environment.systemPackages = with pkgs; [
      iproute2
      iputils
      net-tools
    ];

    # Set hostname during activation
    system.activationScripts.hostname = stringAfter [ "etc" ] ''
      # Set system hostname
      echo "Setting hostname to ${cfg.hostName}..."
      ${pkgs.net-tools}/bin/hostname "${cfg.hostName}"
    '';
  };
}
