# BIND DNS authoritative server
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.bind;
  dnsCfg = config.networking.dns;

  # Generate zone configuration blocks
  zoneConfigs = concatStringsSep "\n" (
    mapAttrsToList (name: zone: ''
      zone "${name}" {
        type ${zone.type};
        file "${zone.file}";
        ${optionalString (zone.masters != [ ]) ''
          masters { ${concatStringsSep "; " zone.masters}; };
        ''}
        ${optionalString (zone.allowQuery != null) ''
          allow-query { ${zone.allowQuery}; };
        ''}
        ${optionalString (zone.allowTransfer != null) ''
          allow-transfer { ${zone.allowTransfer}; };
        ''}
        ${zone.extraConfig}
      };
    '') cfg.settings.zones
  );

  # Generate named.conf
  namedConf = pkgs.writeText "named.conf" ''
    # Generated by ekaos bind module

    options {
      directory "${cfg.directory}";
      listen-on port ${toString cfg.settings.port} { ${concatStringsSep "; " cfg.settings.listenOn}; };
      ${optionalString (cfg.settings.listenOnV6 != [ ]) ''
        listen-on-v6 port ${toString cfg.settings.port} { ${concatStringsSep "; " cfg.settings.listenOnV6}; };
      ''}
      ${optionalString (cfg.settings.forwarders != [ ]) ''
        forwarders { ${concatStringsSep "; " cfg.settings.forwarders}; };
        forward ${cfg.settings.forward};
      ''}
      ${optionalString (cfg.settings.allowQuery != null) ''
        allow-query { ${cfg.settings.allowQuery}; };
      ''}
      ${optionalString (cfg.settings.allowRecursion != null) ''
        allow-recursion { ${cfg.settings.allowRecursion}; };
      ''}
      dnssec-validation ${if cfg.settings.dnssecValidation then "auto" else "no"};
      recursion ${if cfg.settings.recursion then "yes" else "no"};
      ${cfg.settings.extraOptions}
    };

    logging {
      channel default_log {
        stderr;
        severity ${cfg.settings.logSeverity};
        print-time yes;
        print-category yes;
      };
      category default { default_log; };
    };

    ${zoneConfigs}

    ${cfg.settings.extraConfig}
  '';

  # Auto-generate zone configs from dns-zones module
  autoZones = optionalAttrs (dnsCfg.enable or false) (
    listToAttrs (
      map (
        domain:
        nameValuePair domain {
          type = "master";
          file = "${dnsCfg.zoneDir}/${domain}.zone";
          masters = [ ];
          allowQuery = null;
          allowTransfer = null;
          extraConfig = "";
        }
      ) (attrNames (dnsCfg.zones or { }))
    )
  );

in

{
  options.services.bind = {
    enable = mkOption {
      type = types.bool;
      default = false;
      description = "Whether to enable the BIND DNS server.";
    };

    description = mkOption {
      type = types.str;
      default = "BIND DNS Server";
      description = "Service description.";
    };

    command = mkOption {
      type = types.nullOr types.str;
      internal = true;
      default = null;
      description = "Command to run (set automatically).";
    };

    args = mkOption {
      type = types.listOf types.str;
      internal = true;
      default = [ ];
      description = "Command arguments (set automatically).";
    };

    user = mkOption {
      type = types.str;
      default = "named";
      description = "User to run BIND as.";
    };

    restartPolicy = mkOption {
      type = types.str;
      default = "always";
      description = "Restart policy.";
    };

    systemd = mkOption {
      type = types.attrsOf types.anything;
      default = { };
      description = "Systemd-specific options.";
    };

    ports = mkOption {
      type = types.attrsOf types.anything;
      default = { };
      description = "Port contracts for this service.";
    };

    package = mkOption {
      type = types.package;
      default = pkgs.bind;
      description = "BIND package to use.";
    };

    directory = mkOption {
      type = types.str;
      default = "/run/named";
      description = "Working directory for BIND.";
    };

    settings = mkOption {
      type = types.submodule {
        options = {
          port = mkOption {
            type = types.port;
            default = 53;
            description = "Port for BIND to listen on.";
          };

          listenOn = mkOption {
            type = types.listOf types.str;
            default = [ "any" ];
            example = [
              "127.0.0.1"
              "192.168.1.1"
            ];
            description = "IPv4 addresses to listen on.";
          };

          listenOnV6 = mkOption {
            type = types.listOf types.str;
            default = [ ];
            example = [ "any" ];
            description = "IPv6 addresses to listen on.";
          };

          forwarders = mkOption {
            type = types.listOf types.str;
            default = [ ];
            example = [
              "8.8.8.8"
              "8.8.4.4"
            ];
            description = "Upstream DNS servers for forwarding.";
          };

          forward = mkOption {
            type = types.enum [
              "first"
              "only"
            ];
            default = "first";
            description = ''
              Forwarding behavior.
              - first: Try forwarders first, then resolve recursively
              - only: Only use forwarders
            '';
          };

          recursion = mkOption {
            type = types.bool;
            default = false;
            description = ''
              Whether to enable recursive queries.
              Disable for authoritative-only servers.
            '';
          };

          allowQuery = mkOption {
            type = types.nullOr types.str;
            default = null;
            example = "any";
            description = "ACL for who can query this server. null uses BIND default.";
          };

          allowRecursion = mkOption {
            type = types.nullOr types.str;
            default = null;
            example = "localhost; 10.0.0.0/8";
            description = "ACL for who can make recursive queries.";
          };

          dnssecValidation = mkOption {
            type = types.bool;
            default = true;
            description = "Whether to enable DNSSEC validation.";
          };

          logSeverity = mkOption {
            type = types.enum [
              "critical"
              "error"
              "warning"
              "notice"
              "info"
              "debug"
              "dynamic"
            ];
            default = "info";
            description = "Logging severity level.";
          };

          zones = mkOption {
            type = types.attrsOf (
              types.submodule {
                options = {
                  type = mkOption {
                    type = types.enum [
                      "master"
                      "slave"
                      "forward"
                      "hint"
                    ];
                    default = "master";
                    description = "Zone type.";
                  };

                  file = mkOption {
                    type = types.str;
                    description = "Path to the zone file.";
                  };

                  masters = mkOption {
                    type = types.listOf types.str;
                    default = [ ];
                    description = "Master server addresses (for slave zones).";
                  };

                  allowQuery = mkOption {
                    type = types.nullOr types.str;
                    default = null;
                    description = "Per-zone query ACL.";
                  };

                  allowTransfer = mkOption {
                    type = types.nullOr types.str;
                    default = null;
                    description = "Per-zone transfer ACL.";
                  };

                  extraConfig = mkOption {
                    type = types.lines;
                    default = "";
                    description = "Extra zone configuration.";
                  };
                };
              }
            );
            default = { };
            description = "DNS zones to serve.";
          };

          extraOptions = mkOption {
            type = types.lines;
            default = "";
            description = "Extra options for the options block.";
          };

          extraConfig = mkOption {
            type = types.lines;
            default = "";
            description = "Extra configuration appended to named.conf.";
          };
        };
      };
      default = { };
      description = "BIND configuration.";
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = !(config.services.unbound.enable or false);
        message = "services.bind and services.unbound cannot both be enabled (port 53 conflict).";
      }
    ];

    # Merge auto-discovered zones from dns-zones module
    services.bind.settings.zones = autoZones;

    # Define the BIND service
    services.bind = {
      command = "${cfg.package}/bin/named";
      args = [
        "-f" # foreground
        "-c"
        "${namedConf}"
        "-u"
        cfg.user
      ];
      user = "root"; # named drops privileges itself after binding port 53
      restartPolicy = "always";

      ports.dns = {
        port = cfg.settings.port;
        protocol = "udp";
        transport = "udp";
        internal = cfg.settings.listenOn == [ "127.0.0.1" ];
        openFirewall = cfg.settings.listenOn != [ "127.0.0.1" ];
      };

      systemd = {
        after = [ "network.target" ];
        wantedBy = [ "multi-user.target" ];
      };
    };

    # Create named user and group
    users.users.${cfg.user} = {
      isSystemUser = true;
      group = cfg.user;
      description = "BIND DNS server user";
    };
    users.groups.${cfg.user} = { };

    # Install configuration
    environment.etc."bind/named.conf".source = namedConf;

    # Add BIND tools to system packages
    environment.systemPackages = [ cfg.package ];

    # Initialize directories
    system.activationScripts.bind = stringAfter [ "etc" "users" ] ''
      mkdir -p ${cfg.directory}
      chown ${cfg.user}:${cfg.user} ${cfg.directory}
      chmod 750 ${cfg.directory}

      # Generate rndc key if not present
      if [ ! -f /etc/bind/rndc.key ]; then
        ${cfg.package}/bin/rndc-confgen -a -c /etc/bind/rndc.key -u ${cfg.user} 2>/dev/null || true
      fi
    '';
  };
}
