# Adios port of ekaos/modules/services/networking/dhcpcd.nix.
# TODO(adios-cutover): command/args were internal options set by the legacy
# config; they are computed in impl, not user options.
{ types, pkgs, ... }:

{
  options = {
    enable = {
      type = types.bool;
      default = false;
      description = ''
        Whether to enable dhcpcd for automatic network configuration.

        This should be explicitly enabled when DHCP configuration is needed.
      '';
    };

    description = {
      type = types.string;
      default = "DHCP Client Daemon";
      description = "Service description";
    };

    user = {
      type = types.string;
      default = "root";
      description = "User to run service as";
    };

    restartPolicy = {
      type = types.string;
      default = "always";
      description = "Restart policy";
    };

    systemd = {
      type = types.attrsOf types.any;
      default = { };
      description = "Systemd-specific options";
    };

    package = {
      type = types.derivation;
      default = pkgs.dhcpcd;
      description = "dhcpcd package to use.";
    };

    settings = {
      options = {
        allowRoutes = {
          type = types.bool;
          default = true;
          description = ''
            Whether to allow dhcpcd to install default routes.

            When true, dhcpcd can set the default gateway.
            When false, routing must be configured manually.
          '';
        };

        extraConfig = {
          type = types.string;
          default = "";
          description = ''
            Extra configuration to append to dhcpcd.conf.

            See dhcpcd.conf(5) for available options.
          '';
        };
      };
      description = "dhcpcd-specific configuration";
    };
  };

  impl =
    { options, ... }:
    if !options.enable then
      { }
    else
      let
        s = options.settings;
        dhcpcdConf = pkgs.writeText "dhcpcd.conf" ''
          # Generated by ekaos dhcpcd module

          # Inform the DHCP server of our hostname for DDNS
          hostname

          # Use the same DUID + IAID as DHCPv6 for DHCPv4 ClientID as per RFC4361
          duid

          # Persist interface configuration when dhcpcd exits
          persistent

          # Rapid commit support (RFC 4039)
          option rapid_commit

          # A list of options to request from the DHCP server
          option domain_name_servers, domain_name, domain_search, host_name
          option classless_static_routes
          option interface_mtu

          # Most distributions have NTP support
          option ntp_servers

          # Respect the network MTU
          option interface_mtu

          # A ServerID is required by RFC2131
          require dhcp_server_identifier

          # Generate Stable Private IPv6 Addresses instead of hardware based ones
          slaac private

          # Don't install any default routes
          # We'll let the system handle routing
          ${if !(s.allowRoutes or true) then "nogateway" else ""}

          # Wait for IP address before forking to background
          waitip

          ${s.extraConfig or ""}
        '';
      in
      {
        services.dhcpcd = {
          inherit (options)
            enable
            description
            user
            restartPolicy
            ;
          command = "${options.package}/bin/dhcpcd";
          args = [
            "--config"
            "${dhcpcdConf}"
            "--nobackground"
          ];
          systemd = {
            after = [ "network-pre.target" ];
            before = [ "network.target" ];
            wantedBy = [ "multi-user.target" ];
          }
          // options.systemd;
        };

        environment.etc."dhcpcd.conf".source = dhcpcdConf;

        environment.systemPackages = [ options.package ];

        # TODO(adios-cutover): legacy ordering (after "etc") lost; plain script.
        system.activationScripts.dhcpcd = ''
          # Create dhcpcd state directory
          mkdir -p /var/lib/dhcpcd
          mkdir -p /var/db/dhcpcd
        '';
      };
}
