# DHCP client daemon (dhcpcd)
# Provides automatic network configuration via DHCP
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.dhcpcd;
  netCfg = config.networking;

  # dhcpcd configuration file
  dhcpcdConf = pkgs.writeText "dhcpcd.conf" ''
    # Generated by ekaos dhcpcd module

    # Inform the DHCP server of our hostname for DDNS
    hostname

    # Use the same DUID + IAID as DHCPv6 for DHCPv4 ClientID as per RFC4361
    duid

    # Persist interface configuration when dhcpcd exits
    persistent

    # Rapid commit support (RFC 4039)
    option rapid_commit

    # A list of options to request from the DHCP server
    option domain_name_servers, domain_name, domain_search, host_name
    option classless_static_routes
    option interface_mtu

    # Most distributions have NTP support
    option ntp_servers

    # Respect the network MTU
    option interface_mtu

    # A ServerID is required by RFC2131
    require dhcp_server_identifier

    # Generate Stable Private IPv6 Addresses instead of hardware based ones
    slaac private

    # Don't install any default routes
    # We'll let the system handle routing
    ${optionalString (!cfg.settings.allowRoutes) "nogateway"}

    # Wait for IP address before forking to background
    waitip

    ${cfg.settings.extraConfig}
  '';

in

{
  options = {
    services.dhcpcd = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to enable dhcpcd for automatic network configuration.

          This should be explicitly enabled when DHCP configuration is needed.
        '';
      };

      description = mkOption {
        type = types.str;
        default = "DHCP Client Daemon";
        description = "Service description";
      };

      command = mkOption {
        type = types.str;
        internal = true;
        description = "Command to run (set automatically)";
      };

      args = mkOption {
        type = types.listOf types.str;
        internal = true;
        default = [];
        description = "Command arguments (set automatically)";
      };

      user = mkOption {
        type = types.str;
        default = "root";
        description = "User to run service as";
      };

      restartPolicy = mkOption {
        type = types.str;
        default = "always";
        description = "Restart policy";
      };

      systemd = mkOption {
        type = types.attrsOf types.anything;
        default = {};
        description = "Systemd-specific options";
      };

      settings = mkOption {
        type = types.submodule {
          options = {
            allowRoutes = mkOption {
              type = types.bool;
              default = true;
              description = ''
                Whether to allow dhcpcd to install default routes.

                When true, dhcpcd can set the default gateway.
                When false, routing must be configured manually.
              '';
            };

            extraConfig = mkOption {
              type = types.lines;
              default = "";
              example = ''
                # Use a specific DNS server
                static domain_name_servers=8.8.8.8 8.8.4.4
              '';
              description = ''
                Extra configuration to append to dhcpcd.conf.

                See dhcpcd.conf(5) for available options.
              '';
            };
          };
        };
        default = {};
        description = "dhcpcd-specific configuration";
      };
    };
  };

  config = mkIf cfg.enable {
    # Define the dhcpcd service using cross-platform interface
    services.dhcpcd = {
      command = "${pkgs.dhcpcd}/bin/dhcpcd";
      args = [ "--config" "${dhcpcdConf}" "--nobackground" ];
      user = "root";
      restartPolicy = "always";

      # Systemd-specific options
      systemd = {
        after = [ "network-pre.target" ];
        before = [ "network.target" ];
        wantedBy = [ "multi-user.target" ];
      };
    };

    # Install dhcpcd configuration
    environment.etc."dhcpcd.conf".source = dhcpcdConf;

    # Add dhcpcd to system packages
    environment.systemPackages = [ pkgs.dhcpcd ];

    # Create required directories
    system.activationScripts.dhcpcd = stringAfter [ "etc" ] ''
      # Create dhcpcd state directory
      mkdir -p /var/lib/dhcpcd
      mkdir -p /var/db/dhcpcd
    '';
  };
}
