# Adios port of ekaos/modules/services/networking/dnsmasq.nix.
# TODO(adios-cutover): command/args were internal options set by the legacy
# config; they are computed in impl, not user options.
{ types, pkgs, ... }:

{
  options = {
    enable = {
      type = types.bool;
      default = false;
      description = ''
        Whether to run dnsmasq as a DNS/DHCP server.
      '';
    };

    description = {
      type = types.string;
      default = "dnsmasq DNS/DHCP Server";
      description = "Service description.";
    };

    user = {
      type = types.string;
      default = "dnsmasq";
      description = "User to run service as.";
    };

    restartPolicy = {
      type = types.string;
      default = "on-failure";
      description = "Restart policy.";
    };

    systemd = {
      type = types.attrsOf types.any;
      default = { };
      description = "Systemd-specific options.";
    };

    package = {
      type = types.derivation;
      default = pkgs.dnsmasq;
      description = "The dnsmasq package to use.";
    };

    settings = {
      options = {
        resolveLocalQueries = {
          type = types.bool;
          default = true;
          description = ''
            Whether dnsmasq should resolve local queries
            (i.e. add 127.0.0.1 to /etc/resolv.conf).
          '';
        };

        servers = {
          type = types.listOf types.string;
          default = [ ];
          description = "Upstream DNS servers.";
        };

        addresses = {
          type = types.listOf types.string;
          default = [ ];
          description = "Address overrides in dnsmasq format.";
        };

        interfaces = {
          type = types.listOf types.string;
          default = [ ];
          description = "Interfaces to listen on. Empty means all interfaces.";
        };

        exceptInterfaces = {
          type = types.listOf types.string;
          default = [ ];
          description = "Interfaces to exclude from listening.";
        };

        dhcpRanges = {
          type = types.listOf types.string;
          default = [ ];
          description = "DHCP ranges in dnsmasq format.";
        };

        port = {
          type = types.nullOr types.int;
          default = null;
          description = "DNS port. Null means default (53). Set to 0 to disable DNS.";
        };

        domainNeeded = {
          type = types.bool;
          default = false;
          description = "Never forward plain names (without a dot or domain part).";
        };

        bogusPriv = {
          type = types.bool;
          default = false;
          description = "Never forward addresses in the non-routed address spaces.";
        };

        dnssec = {
          type = types.bool;
          default = false;
          description = "Whether to enable DNSSEC validation.";
        };

        filterWin2k = {
          type = types.bool;
          default = false;
          description = "Filter useless Windows-originated DNS requests.";
        };

        extraConfig = {
          type = types.string;
          default = "";
          description = ''
            Extra configuration to append to dnsmasq.conf.
            See dnsmasq(8) for available options.
          '';
        };
      };
      description = "dnsmasq-specific configuration.";
    };
  };

  assertions = [
    {
      verify =
        { options }:
        (options.settings.port or null) == null
        || ((options.settings.port or 0) >= 0 && (options.settings.port or 0) <= 65535);
      explain = { options }: "dnsmasq port must be 0-65535, got ${toString (options.settings.port or 0)}";
    }
  ];

  impl =
    { options, ... }:
    if !options.enable then
      { }
    else
      let
        s = options.settings;
        stateDir = "/var/lib/dnsmasq";

        dnsmasqConf = pkgs.writeText "dnsmasq.conf" ''
          # Generated by ekaos dnsmasq module
          dhcp-leasefile=${stateDir}/dnsmasq.leases

          ${
            if (s.resolveLocalQueries or true) then
              ''
                conf-file=/etc/dnsmasq-conf.conf
                resolv-file=/etc/dnsmasq-resolv.conf
              ''
            else
              ""
          }

          ${if (s.domainNeeded or false) then "domain-needed" else ""}
          ${if (s.bogusPriv or false) then "bogus-priv" else ""}
          ${if (s.dnssec or false) then "dnssec" else ""}
          ${if (s.filterWin2k or false) then "filterwin2k" else ""}

          ${if (s.port or null) != null then "port=${toString s.port}" else ""}

          ${builtins.concatStringsSep "\n" (builtins.map (x: "server=${x}") (s.servers or [ ]))}
          ${builtins.concatStringsSep "\n" (builtins.map (x: "address=${x}") (s.addresses or [ ]))}
          ${builtins.concatStringsSep "\n" (builtins.map (x: "interface=${x}") (s.interfaces or [ ]))}
          ${builtins.concatStringsSep "\n" (
            builtins.map (x: "except-interface=${x}") (s.exceptInterfaces or [ ])
          )}
          ${builtins.concatStringsSep "\n" (builtins.map (x: "dhcp-range=${x}") (s.dhcpRanges or [ ]))}

          ${s.extraConfig or ""}
        '';
      in
      {
        services.dnsmasq = {
          inherit (options) enable description restartPolicy;
          # Starts as root, drops to the dnsmasq user.
          user = "root";
          command = "${options.package}/bin/dnsmasq";
          args = [
            "-k"
            "--enable-dbus"
            "--user=${options.user}"
            "-C"
            "${dnsmasqConf}"
          ];
          systemd = {
            after = [ "network.target" ];
            wantedBy = [ "multi-user.target" ];
            serviceConfig = {
              PrivateTmp = true;
              ProtectSystem = true;
              ProtectHome = true;
            };
          }
          // options.systemd;
        };

        services.dbus.packages = [ options.package ];

        environment.systemPackages = [ options.package ];

        users.users.dnsmasq = {
          isSystemUser = true;
          group = "dnsmasq";
          description = "dnsmasq daemon user";
        };
        users.groups.dnsmasq = { };

        # TODO(adios-cutover): legacy ordering (after "etc") lost; plain script.
        system.activationScripts.dnsmasq = ''
          mkdir -m 755 -p ${stateDir}
          touch ${stateDir}/dnsmasq.leases
          chown -R dnsmasq:dnsmasq ${stateDir}
          ${if (s.resolveLocalQueries or true) then "touch /etc/dnsmasq-{conf,resolv}.conf" else ""}
        '';
      };
}
