# dnsmasq service module
# Provides DNS, DHCP and TFTP server for small networks
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.dnsmasq;
  stateDir = "/var/lib/dnsmasq";

  dnsmasqConf = pkgs.writeText "dnsmasq.conf" ''
    # Generated by ekaos dnsmasq module
    dhcp-leasefile=${stateDir}/dnsmasq.leases

    ${optionalString cfg.settings.resolveLocalQueries ''
      conf-file=/etc/dnsmasq-conf.conf
      resolv-file=/etc/dnsmasq-resolv.conf
    ''}

    ${optionalString cfg.settings.domainNeeded "domain-needed"}
    ${optionalString cfg.settings.bogusPriv "bogus-priv"}
    ${optionalString cfg.settings.dnssec "dnssec"}
    ${optionalString cfg.settings.filterWin2k "filterwin2k"}

    ${optionalString (cfg.settings.port != null) "port=${toString cfg.settings.port}"}

    ${concatMapStringsSep "\n" (s: "server=${s}") cfg.settings.servers}
    ${concatMapStringsSep "\n" (r: "address=${r}") cfg.settings.addresses}
    ${concatMapStringsSep "\n" (i: "interface=${i}") cfg.settings.interfaces}
    ${concatMapStringsSep "\n" (i: "except-interface=${i}") cfg.settings.exceptInterfaces}
    ${concatMapStringsSep "\n" (r: "dhcp-range=${r}") cfg.settings.dhcpRanges}

    ${cfg.settings.extraConfig}
  '';
in

{
  options = {
    services.dnsmasq = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to run dnsmasq as a DNS/DHCP server.
        '';
      };

      description = mkOption {
        type = types.str;
        default = "dnsmasq DNS/DHCP Server";
        description = "Service description.";
      };

      command = mkOption {
        type = types.str;
        internal = true;
        description = "Command to run (set automatically).";
      };

      args = mkOption {
        type = types.listOf types.str;
        internal = true;
        default = [ ];
        description = "Command arguments (set automatically).";
      };

      user = mkOption {
        type = types.str;
        default = "dnsmasq";
        description = "User to run service as.";
      };

      restartPolicy = mkOption {
        type = types.str;
        default = "on-failure";
        description = "Restart policy.";
      };

      systemd = mkOption {
        type = types.attrsOf types.anything;
        default = { };
        description = "Systemd-specific options.";
      };

      package = mkOption {
        type = types.package;
        default = pkgs.dnsmasq;
        defaultText = literalExpression "pkgs.dnsmasq";
        description = "The dnsmasq package to use.";
      };

      settings = mkOption {
        type = types.submodule {
          options = {
            resolveLocalQueries = mkOption {
              type = types.bool;
              default = true;
              description = ''
                Whether dnsmasq should resolve local queries
                (i.e. add 127.0.0.1 to /etc/resolv.conf).
              '';
            };

            servers = mkOption {
              type = types.listOf types.str;
              default = [ ];
              example = [
                "8.8.8.8"
                "8.8.4.4"
              ];
              description = "Upstream DNS servers.";
            };

            addresses = mkOption {
              type = types.listOf types.str;
              default = [ ];
              example = [ "/example.local/192.168.1.1" ];
              description = "Address overrides in dnsmasq format.";
            };

            interfaces = mkOption {
              type = types.listOf types.str;
              default = [ ];
              example = [
                "eth0"
                "wlan0"
              ];
              description = "Interfaces to listen on. Empty means all interfaces.";
            };

            exceptInterfaces = mkOption {
              type = types.listOf types.str;
              default = [ ];
              example = [ "lo" ];
              description = "Interfaces to exclude from listening.";
            };

            dhcpRanges = mkOption {
              type = types.listOf types.str;
              default = [ ];
              example = [ "192.168.0.50,192.168.0.150,12h" ];
              description = "DHCP ranges in dnsmasq format.";
            };

            port = mkOption {
              type = types.nullOr types.port;
              default = null;
              description = "DNS port. Null means default (53). Set to 0 to disable DNS.";
            };

            domainNeeded = mkOption {
              type = types.bool;
              default = false;
              description = "Never forward plain names (without a dot or domain part).";
            };

            bogusPriv = mkOption {
              type = types.bool;
              default = false;
              description = "Never forward addresses in the non-routed address spaces.";
            };

            dnssec = mkOption {
              type = types.bool;
              default = false;
              description = "Whether to enable DNSSEC validation.";
            };

            filterWin2k = mkOption {
              type = types.bool;
              default = false;
              description = "Filter useless Windows-originated DNS requests.";
            };

            extraConfig = mkOption {
              type = types.lines;
              default = "";
              description = ''
                Extra configuration to append to dnsmasq.conf.
                See dnsmasq(8) for available options.
              '';
            };
          };
        };
        default = { };
        description = "dnsmasq-specific configuration.";
      };
    };
  };

  config = mkIf cfg.enable {
    services.dnsmasq = {
      command = "${cfg.package}/bin/dnsmasq";
      args = [
        "-k"
        "--enable-dbus"
        "--user=${cfg.user}"
        "-C"
        "${dnsmasqConf}"
      ];
      user = "root"; # starts as root, drops to dnsmasq user
      restartPolicy = cfg.restartPolicy;

      systemd = {
        after = [ "network.target" ];
        wantedBy = [ "multi-user.target" ];
        serviceConfig = {
          PrivateTmp = true;
          ProtectSystem = true;
          ProtectHome = true;
        };
      };
    };

    services.dbus.packages = [ cfg.package ];

    environment.systemPackages = [ cfg.package ];

    users.users.dnsmasq = {
      isSystemUser = true;
      group = "dnsmasq";
      description = "dnsmasq daemon user";
    };
    users.groups.dnsmasq = { };

    system.activationScripts.dnsmasq = stringAfter [ "etc" ] ''
      mkdir -m 755 -p ${stateDir}
      touch ${stateDir}/dnsmasq.leases
      chown -R dnsmasq:dnsmasq ${stateDir}
      ${optionalString cfg.settings.resolveLocalQueries "touch /etc/dnsmasq-{conf,resolv}.conf"}
    '';
  };
}
