# OpenSSH daemon (sshd)
# Provides secure remote shell access
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.openssh;
  userCfg = config.users;

  # Generate sshd_config
  sshdConfig = pkgs.writeText "sshd_config" ''
    # Generated by ekaos openssh module

    # Listening
    Port ${toString cfg.settings.ports}
    ${optionalString (cfg.settings.listenAddresses != [ ]) (
      concatMapStringsSep "\n" (addr: "ListenAddress ${addr}") cfg.settings.listenAddresses
    )}

    # Host keys
    ${concatMapStringsSep "\n" (key: "HostKey ${key}") cfg.settings.hostKeys}

    # Logging
    SyslogFacility AUTH
    LogLevel ${cfg.settings.logLevel}

    # Authentication
    PermitRootLogin ${cfg.settings.permitRootLogin}
    PasswordAuthentication ${if cfg.settings.passwordAuthentication then "yes" else "no"}
    PubkeyAuthentication yes
    ChallengeResponseAuthentication no
    UsePAM yes

    # Security
    X11Forwarding ${if cfg.settings.x11Forwarding then "yes" else "no"}
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem sftp ${pkgs.openssh}/libexec/sftp-server

    # Performance
    UseDNS no

    ${cfg.settings.extraConfig}
  '';

  # Default host key paths
  defaultHostKeys = [
    "/etc/ssh/ssh_host_rsa_key"
    "/etc/ssh/ssh_host_ed25519_key"
  ];

in

{
  options = {
    services.openssh = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to enable the OpenSSH secure shell daemon.

          This allows secure remote login and file transfer.
        '';
      };

      description = mkOption {
        type = types.str;
        default = "OpenSSH Daemon";
        description = "Service description";
      };

      command = mkOption {
        type = types.str;
        internal = true;
        description = "Command to run (set automatically)";
      };

      args = mkOption {
        type = types.listOf types.str;
        internal = true;
        default = [ ];
        description = "Command arguments (set automatically)";
      };

      user = mkOption {
        type = types.str;
        default = "root";
        description = "User to run service as";
      };

      restartPolicy = mkOption {
        type = types.str;
        default = "always";
        description = "Restart policy";
      };

      systemd = mkOption {
        type = types.attrsOf types.anything;
        default = { };
        description = "Systemd-specific options";
      };

      settings = mkOption {
        type = types.submodule {
          options = {
            ports = mkOption {
              type = types.port;
              default = 22;
              description = ''
                Port for sshd to listen on.
              '';
            };

            listenAddresses = mkOption {
              type = types.listOf types.str;
              default = [ ];
              example = [
                "0.0.0.0"
                "[::]"
              ];
              description = ''
                List of addresses for sshd to listen on.

                If empty, listens on all interfaces.
              '';
            };

            permitRootLogin = mkOption {
              type = types.enum [
                "yes"
                "no"
                "prohibit-password"
                "forced-commands-only"
              ];
              default = "prohibit-password";
              description = ''
                Whether root can login via SSH.

                - "yes": Root can login with password
                - "no": Root cannot login at all
                - "prohibit-password": Root can only use key-based auth
                - "forced-commands-only": Root can only run forced commands
              '';
            };

            passwordAuthentication = mkOption {
              type = types.bool;
              default = true;
              description = ''
                Whether to allow password-based authentication.

                Set to false to require key-based authentication only.
              '';
            };

            x11Forwarding = mkOption {
              type = types.bool;
              default = false;
              description = ''
                Whether to allow X11 forwarding.
              '';
            };

            logLevel = mkOption {
              type = types.enum [
                "QUIET"
                "FATAL"
                "ERROR"
                "INFO"
                "VERBOSE"
                "DEBUG"
                "DEBUG1"
                "DEBUG2"
                "DEBUG3"
              ];
              default = "INFO";
              description = ''
                Logging verbosity level.
              '';
            };

            hostKeys = mkOption {
              type = types.listOf types.path;
              default = defaultHostKeys;
              description = ''
                List of paths to host key files.

                These keys identify the server to clients.
              '';
            };

            extraConfig = mkOption {
              type = types.lines;
              default = "";
              example = ''
                AllowUsers alice bob
                MaxAuthTries 3
              '';
              description = ''
                Extra configuration to append to sshd_config.

                See sshd_config(5) for available options.
              '';
            };
          };
        };
        default = { };
        description = "OpenSSH-specific configuration";
      };
    };
  };

  config = mkIf cfg.enable {
    # Define the openssh service using cross-platform interface
    services.openssh = {
      command = "${pkgs.openssh}/bin/sshd";
      args = [
        "-D"
        "-f"
        "${sshdConfig}"
      ];
      user = "root";
      restartPolicy = "always";

      # Systemd-specific options
      systemd = {
        after = [ "network.target" ];
        wantedBy = [ "multi-user.target" ];
      };
    };

    # Install sshd configuration
    environment.etc."ssh/sshd_config".source = sshdConfig;

    # Add openssh to system packages
    environment.systemPackages = [ pkgs.openssh ];

    # Add PAM configuration for sshd
    environment.etc."pam.d/sshd".text = ''
      # PAM configuration for sshd
      auth      substack     password-auth
      auth      include      postlogin
      account   required     pam_nologin.so
      account   include      password-auth
      password  include      password-auth
      session   required     pam_loginuid.so
      session   optional     pam_keyinit.so force revoke
      session   optional     pam_motd.so
      session   include      password-auth
      session   include      postlogin
    '';

    # Basic PAM includes
    environment.etc."pam.d/password-auth".text = ''
      auth      required    pam_env.so
      auth      sufficient  pam_unix.so try_first_pass nullok
      auth      required    pam_deny.so

      account   required    pam_unix.so

      password  required    pam_unix.so try_first_pass nullok sha512 shadow
      password  required    pam_deny.so

      session   required    pam_limits.so
      session   required    pam_unix.so
      session   optional    pam_umask.so
    '';

    environment.etc."pam.d/postlogin".text = ''
      session   optional    pam_motd.so
      session   optional    pam_lastlog.so silent
    '';

    # Create SSH directories and generate host keys
    system.activationScripts.sshd = stringAfter [ "etc" "users" ] ''
      # Create SSH directories
      mkdir -p /etc/ssh
      mkdir -p /var/empty
      chmod 755 /etc/ssh
      chmod 711 /var/empty

      # Generate host keys if they don't exist
      ${concatMapStringsSep "\n" (
        keyPath:
        let
          keyType =
            if hasSuffix "_rsa_key" keyPath then
              "rsa"
            else if hasSuffix "_ed25519_key" keyPath then
              "ed25519"
            else if hasSuffix "_ecdsa_key" keyPath then
              "ecdsa"
            else
              "rsa";
        in
        ''
          if [ ! -f "${keyPath}" ]; then
            echo "Generating SSH ${keyType} host key..."
            # Set USER and HOME to work around NSS issues during disk image builds
            USER=root HOME=/root ${pkgs.openssh}/bin/ssh-keygen -t ${keyType} -f "${keyPath}" -N "" -q || true
            # Verify the key was created even if ssh-keygen complained
            if [ -f "${keyPath}" ]; then
              chmod 600 "${keyPath}"
              chmod 644 "${keyPath}.pub"
            fi
          fi
        ''
      ) cfg.settings.hostKeys}

    '';
  };
}
