# OpenSSH daemon (sshd)
# Provides secure remote shell access
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.openssh;
  userCfg = config.users;

  # Generate sshd_config
  sshdConfig = pkgs.writeText "sshd_config" ''
    # Generated by ekaos openssh module

    # Listening
    Port ${toString cfg.ports}
    ${optionalString (cfg.listenAddresses != [])
      (concatMapStringsSep "\n" (addr: "ListenAddress ${addr}") cfg.listenAddresses)}

    # Host keys
    ${concatMapStringsSep "\n" (key: "HostKey ${key}") cfg.hostKeys}

    # Logging
    SyslogFacility AUTH
    LogLevel ${cfg.logLevel}

    # Authentication
    PermitRootLogin ${cfg.permitRootLogin}
    PasswordAuthentication ${if cfg.passwordAuthentication then "yes" else "no"}
    PubkeyAuthentication yes
    ChallengeResponseAuthentication no
    UsePAM yes

    # Security
    X11Forwarding ${if cfg.x11Forwarding then "yes" else "no"}
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem sftp ${pkgs.openssh}/libexec/sftp-server

    # Performance
    UseDNS no

    ${cfg.extraConfig}
  '';

  # Default host key paths
  defaultHostKeys = [
    "/etc/ssh/ssh_host_rsa_key"
    "/etc/ssh/ssh_host_ed25519_key"
  ];

in

{
  options = {
    services.openssh = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to enable the OpenSSH secure shell daemon.

          This allows secure remote login and file transfer.
        '';
      };

      ports = mkOption {
        type = types.port;
        default = 22;
        description = ''
          Port for sshd to listen on.
        '';
      };

      listenAddresses = mkOption {
        type = types.listOf types.str;
        default = [];
        example = [ "0.0.0.0" "[::]" ];
        description = ''
          List of addresses for sshd to listen on.

          If empty, listens on all interfaces.
        '';
      };

      permitRootLogin = mkOption {
        type = types.enum [ "yes" "no" "prohibit-password" "forced-commands-only" ];
        default = "prohibit-password";
        description = ''
          Whether root can login via SSH.

          - "yes": Root can login with password
          - "no": Root cannot login at all
          - "prohibit-password": Root can only use key-based auth
          - "forced-commands-only": Root can only run forced commands
        '';
      };

      passwordAuthentication = mkOption {
        type = types.bool;
        default = true;
        description = ''
          Whether to allow password-based authentication.

          Set to false to require key-based authentication only.
        '';
      };

      x11Forwarding = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to allow X11 forwarding.
        '';
      };

      logLevel = mkOption {
        type = types.enum [ "QUIET" "FATAL" "ERROR" "INFO" "VERBOSE" "DEBUG" "DEBUG1" "DEBUG2" "DEBUG3" ];
        default = "INFO";
        description = ''
          Logging verbosity level.
        '';
      };

      hostKeys = mkOption {
        type = types.listOf types.path;
        default = defaultHostKeys;
        description = ''
          List of paths to host key files.

          These keys identify the server to clients.
        '';
      };

      extraConfig = mkOption {
        type = types.lines;
        default = "";
        example = ''
          AllowUsers alice bob
          MaxAuthTries 3
        '';
        description = ''
          Extra configuration to append to sshd_config.

          See sshd_config(5) for available options.
        '';
      };
    };
  };

  config = mkIf cfg.enable {
    # Install sshd configuration
    environment.etc."ssh/sshd_config".source = sshdConfig;

    # Add openssh to system packages
    environment.systemPackages = [ pkgs.openssh ];

    # Create sshd service
    systemd.services.sshd = {
      enable = true;
      description = "OpenSSH Daemon";
      command = "${pkgs.openssh}/bin/sshd -D -f ${sshdConfig}";
      user = "root";
      restartPolicy = "always";
    };

    # Add PAM configuration for sshd
    environment.etc."pam.d/sshd".text = ''
      # PAM configuration for sshd
      auth      substack     password-auth
      auth      include      postlogin
      account   required     pam_nologin.so
      account   include      password-auth
      password  include      password-auth
      session   required     pam_loginuid.so
      session   optional     pam_keyinit.so force revoke
      session   optional     pam_motd.so
      session   include      password-auth
      session   include      postlogin
    '';

    # Basic PAM includes
    environment.etc."pam.d/password-auth".text = ''
      auth      required    pam_env.so
      auth      sufficient  pam_unix.so try_first_pass nullok
      auth      required    pam_deny.so

      account   required    pam_unix.so

      password  required    pam_unix.so try_first_pass nullok sha512 shadow
      password  required    pam_deny.so

      session   required    pam_limits.so
      session   required    pam_unix.so
      session   optional    pam_umask.so
    '';

    environment.etc."pam.d/postlogin".text = ''
      session   optional    pam_motd.so
      session   optional    pam_lastlog.so silent
    '';

    # Create SSH directories and generate host keys
    system.activationScripts.sshd = stringAfter [ "etc" "users" ] ''
      # Create SSH directories
      mkdir -p /etc/ssh
      mkdir -p /var/empty
      chmod 755 /etc/ssh
      chmod 711 /var/empty

      # Generate host keys if they don't exist
      ${concatMapStringsSep "\n" (keyPath:
        let
          keyType = if hasSuffix "_rsa_key" keyPath then "rsa"
                    else if hasSuffix "_ed25519_key" keyPath then "ed25519"
                    else if hasSuffix "_ecdsa_key" keyPath then "ecdsa"
                    else "rsa";
        in ''
          if [ ! -f "${keyPath}" ]; then
            echo "Generating SSH ${keyType} host key..."
            ${pkgs.openssh}/bin/ssh-keygen -t ${keyType} -f "${keyPath}" -N "" -q
            chmod 600 "${keyPath}"
            chmod 644 "${keyPath}.pub"
          fi
        ''
      ) cfg.hostKeys}

      # Create .ssh directories for users
      ${concatMapStringsSep "\n" (user:
        optionalString (user.openssh.authorizedKeys.keys != [] || user.openssh.authorizedKeys.keyFiles != []) ''
          mkdir -p "${user.home}/.ssh"
          chmod 700 "${user.home}/.ssh"

          # Generate authorized_keys file
          cat > "${user.home}/.ssh/authorized_keys" << 'EOF'
${concatStringsSep "\n" user.openssh.authorizedKeys.keys}
EOF
          ${concatMapStringsSep "\n" (file: "cat ${file} >> ${user.home}/.ssh/authorized_keys") user.openssh.authorizedKeys.keyFiles}

          chmod 600 "${user.home}/.ssh/authorized_keys"
          chown -R ${user.name}:${user.group} "${user.home}/.ssh"
        ''
      ) (attrValues userCfg.users)}
    '';
  };
}
