# Redis in-memory data store
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.redis;

  mkValueString =
    value:
    if value == true then
      "yes"
    else if value == false then
      "no"
    else
      toString value;

  # Generate redis.conf
  redisConf = pkgs.writeText "redis.conf" ''
    # Generated by ekaos redis module

    # Network
    bind ${cfg.settings.bind}
    port ${toString cfg.settings.port}
    ${optionalString (cfg.settings.unixSocket != null) ''
      unixsocket ${cfg.settings.unixSocket}
      unixsocketperm ${toString cfg.settings.unixSocketPerm}
    ''}

    # General
    daemonize no
    loglevel ${cfg.settings.logLevel}
    logfile ""
    syslog-enabled yes
    databases ${toString cfg.settings.databases}
    maxclients ${toString cfg.settings.maxClients}

    # Memory
    ${optionalString (cfg.settings.maxMemory != null) ''
      maxmemory ${cfg.settings.maxMemory}
      maxmemory-policy ${cfg.settings.maxMemoryPolicy}
    ''}

    # RDB Persistence
    ${
      if cfg.settings.save == [ ] then
        ''save ""''
      else
        concatMapStringsSep "\n" (
          s: "save ${toString (elemAt s 0)} ${toString (elemAt s 1)}"
        ) cfg.settings.save
    }
    dbfilename dump.rdb
    dir ${cfg.dataDir}

    # AOF Persistence
    appendonly ${mkValueString cfg.settings.appendOnly}
    appendfsync ${cfg.settings.appendFsync}

    # Slow log
    slowlog-log-slower-than ${toString cfg.settings.slowLogSlowerThan}
    slowlog-max-len ${toString cfg.settings.slowLogMaxLen}

    ${cfg.settings.extraConfig}
  '';

in

{
  options.services.redis = {
    enable = mkOption {
      type = types.bool;
      default = false;
      description = "Whether to enable the Redis in-memory data store.";
    };

    description = mkOption {
      type = types.str;
      default = "Redis Server";
      description = "Service description.";
    };

    command = mkOption {
      type = types.str;
      internal = true;
      description = "Command to run (set automatically).";
    };

    args = mkOption {
      type = types.listOf types.str;
      internal = true;
      default = [ ];
      description = "Command arguments (set automatically).";
    };

    user = mkOption {
      type = types.str;
      default = "redis";
      description = "User to run Redis as.";
    };

    restartPolicy = mkOption {
      type = types.str;
      default = "always";
      description = "Restart policy.";
    };

    systemd = mkOption {
      type = types.attrsOf types.anything;
      default = { };
      description = "Systemd-specific options.";
    };

    ports = mkOption {
      type = types.attrsOf (
        types.submodule (import ../../../../services/lib/types.nix { inherit lib; }).portContract
      );
      default = { };
      description = "Port contracts for this service.";
    };

    package = mkOption {
      type = types.package;
      default = pkgs.redis;
      description = "Redis package to use.";
    };

    dataDir = mkOption {
      type = types.str;
      default = "/var/lib/redis";
      description = "Data directory for Redis persistence.";
    };

    settings = mkOption {
      type = types.submodule {
        options = {
          port = mkOption {
            type = types.port;
            default = 6379;
            description = "TCP port for Redis to listen on. Set to 0 to disable TCP.";
          };

          bind = mkOption {
            type = types.str;
            default = "127.0.0.1";
            example = "0.0.0.0";
            description = ''
              Interface to bind to.
              Use "0.0.0.0" to listen on all interfaces.
            '';
          };

          unixSocket = mkOption {
            type = types.nullOr types.str;
            default = "/run/redis/redis.sock";
            description = "Path to Unix socket. null disables Unix socket.";
          };

          unixSocketPerm = mkOption {
            type = types.int;
            default = 660;
            description = "Permissions for the Unix socket.";
          };

          maxMemory = mkOption {
            type = types.nullOr types.str;
            default = null;
            example = "256mb";
            description = ''
              Maximum memory Redis will use. null means no limit.
              Supports suffixes: kb, mb, gb.
            '';
          };

          maxMemoryPolicy = mkOption {
            type = types.enum [
              "volatile-lru"
              "allkeys-lru"
              "volatile-lfu"
              "allkeys-lfu"
              "volatile-random"
              "allkeys-random"
              "volatile-ttl"
              "noeviction"
            ];
            default = "noeviction";
            description = "Eviction policy when maxMemory is reached.";
          };

          databases = mkOption {
            type = types.int;
            default = 16;
            description = "Number of databases.";
          };

          maxClients = mkOption {
            type = types.int;
            default = 10000;
            description = "Maximum number of connected clients.";
          };

          logLevel = mkOption {
            type = types.enum [
              "debug"
              "verbose"
              "notice"
              "warning"
            ];
            default = "notice";
            description = "Server verbosity level.";
          };

          save = mkOption {
            type = types.listOf (types.listOf types.int);
            default = [
              [
                900
                1
              ]
              [
                300
                10
              ]
              [
                60
                10000
              ]
            ];
            description = ''
              RDB persistence schedule. Each element is [seconds changes].
              Set to empty list to disable RDB persistence.
            '';
            example = [
              [
                3600
                1
              ]
              [
                300
                100
              ]
            ];
          };

          appendOnly = mkOption {
            type = types.bool;
            default = false;
            description = "Whether to enable append-only file (AOF) persistence.";
          };

          appendFsync = mkOption {
            type = types.enum [
              "always"
              "everysec"
              "no"
            ];
            default = "everysec";
            description = "How often to fsync the AOF log.";
          };

          requirePassFile = mkOption {
            type = types.nullOr types.path;
            default = null;
            example = "/run/secrets/redis-password";
            description = ''
              Path to file containing the Redis password.
              The file is read at service startup and the password is injected
              into the runtime configuration, avoiding storage in the nix store.
            '';
          };

          slowLogSlowerThan = mkOption {
            type = types.int;
            default = 10000;
            description = "Log queries slower than this many microseconds.";
          };

          slowLogMaxLen = mkOption {
            type = types.int;
            default = 128;
            description = "Maximum number of slow log entries.";
          };

          extraConfig = mkOption {
            type = types.lines;
            default = "";
            description = "Extra configuration appended to redis.conf.";
          };
        };
      };
      default = { };
      description = "Redis configuration.";
    };
  };

  config = mkIf cfg.enable {
    # Define the Redis service
    services.redis = {
      command = "${cfg.package}/bin/${cfg.package.serverBin or "redis-server"}";
      args = [ "/var/lib/redis/redis.conf" ];
      restartPolicy = "always";

      ports = mkIf (cfg.settings.port != 0) {
        redis = {
          port = cfg.settings.port;
          protocol = "tcp";
          transport = "tcp";
          internal = cfg.settings.bind == "127.0.0.1";
          openFirewall = cfg.settings.bind != "127.0.0.1";
        };
      };

      systemd = {
        after = [
          "network.target"
          "local-fs.target"
        ];
        wantedBy = [ "multi-user.target" ];
      };
    };

    # Create redis user and group
    users.users.${cfg.user} = {
      isSystemUser = true;
      home = cfg.dataDir;
      group = cfg.user;
      description = "Redis server user";
    };
    users.groups.${cfg.user} = { };

    # Add redis-cli to system packages
    environment.systemPackages = [ cfg.package ];

    # Initialize data directory and runtime configuration
    system.activationScripts.redis = stringAfter [ "etc" "users" ] ''
      # Create data directory
      mkdir -p ${cfg.dataDir}
      chown ${cfg.user}:${cfg.user} ${cfg.dataDir}
      chmod 700 ${cfg.dataDir}

      # Create runtime directory
      mkdir -p /run/redis
      chown ${cfg.user}:${cfg.user} /run/redis
      chmod 750 /run/redis

      # Generate runtime config (includes password from file if configured)
      cp ${redisConf} ${cfg.dataDir}/redis.conf
      ${optionalString (cfg.settings.requirePassFile != null) ''
        if [ -f ${cfg.settings.requirePassFile} ]; then
          echo "requirepass $(cat ${cfg.settings.requirePassFile})" >> ${cfg.dataDir}/redis.conf
        fi
      ''}
      chown ${cfg.user}:${cfg.user} ${cfg.dataDir}/redis.conf
      chmod 600 ${cfg.dataDir}/redis.conf
    '';
  };
}
