# PAM (Pluggable Authentication Modules) configuration
# Provides authentication services for the system
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.security.pam;

  # PAM service type definition
  pamServiceOpts = {
    name,
    config,
    ...
  }:
  {
    options = {
      name = mkOption {
        type = types.str;
        description = "Name of the PAM service.";
      };

      text = mkOption {
        type = types.nullOr types.lines;
        default = null;
        description = "PAM service configuration as text. If null, a default config will be generated.";
      };

      unixAuth = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to enable standard UNIX authentication (pam_unix.so).";
      };

      allowNullPassword = mkOption {
        type = types.bool;
        default = false;
        description = "Whether to allow null (empty) passwords.";
      };
    };

    config = {
      name = mkDefault name;
    };
  };

  # Generate PAM service file content
  mkPamService = service:
    if service.text != null then
      service.text
    else
      ''
        # PAM configuration for ${service.name}
        # Generated by ekaos

        # Authentication
        auth      required    pam_env.so
        auth      ${if service.allowNullPassword then "sufficient" else "required"}  pam_unix.so ${
          optionalString (!service.allowNullPassword) "nullok"
        }
        auth      required    pam_deny.so

        # Account management
        account   required    pam_unix.so

        # Password management
        password  required    pam_unix.so sha512 shadow

        # Session management
        session   required    pam_unix.so
        session   required    pam_limits.so
        session   optional    pam_systemd.so
      '';

  # Get all PAM services as /etc files
  pamEtcFiles = listToAttrs (
    map (
      serviceName:
      let
        service = cfg.services.${serviceName};
      in
      nameValuePair "pam.d/${serviceName}" {
        text = mkPamService service;
        mode = "0644";
      }
    ) (attrNames cfg.services)
  );

in

{
  options = {
    security.pam.services = mkOption {
      type = types.attrsOf (types.submodule pamServiceOpts);
      default = { };
      description = ''
        PAM service configuration.

        Each attribute defines a PAM service configuration file in /etc/pam.d/.
      '';
      example = literalExpression ''
        {
          sshd = {
            unixAuth = true;
          };
        }
      '';
    };

    security.pam.enableShadow = mkOption {
      type = types.bool;
      default = true;
      description = "Whether to enable shadow password support.";
    };
  };

  config = {
    # Define essential PAM services
    security.pam.services = {
      # System login (getty)
      login = {
        text = ''
          # PAM configuration for login
          auth      required    pam_securetty.so
          auth      requisite   pam_nologin.so
          auth      required    pam_env.so
          auth      required    pam_unix.so nullok
          auth      required    pam_deny.so

          account   required    pam_unix.so
          account   required    pam_nologin.so

          password  required    pam_unix.so sha512 shadow

          session   required    pam_unix.so
          session   required    pam_limits.so
          session   optional    pam_systemd.so
          session   optional    pam_lastlog.so
        '';
      };

      # su command
      su = {
        text = ''
          # PAM configuration for su
          auth      sufficient  pam_rootok.so
          auth      required    pam_unix.so nullok
          auth      required    pam_deny.so

          account   required    pam_unix.so

          password  required    pam_unix.so sha512 shadow

          session   required    pam_unix.so
          session   required    pam_limits.so
          session   optional    pam_systemd.so
        '';
      };

      # systemd user sessions
      systemd-user = {
        text = ''
          # PAM configuration for systemd user sessions
          account   required    pam_unix.so

          session   required    pam_unix.so
          session   required    pam_limits.so
          session   optional    pam_systemd.so
        '';
      };

      # other - default/fallback service
      other = {
        text = ''
          # PAM configuration for other (default)
          auth      required    pam_deny.so
          account   required    pam_deny.so
          password  required    pam_deny.so
          session   required    pam_deny.so
        '';
      };
    };

    # Create /etc/pam.d directory and files
    environment.etc = pamEtcFiles // {
      # Create /etc/securetty for pam_securetty
      securetty.text = ''
        # Secure terminals for root login
        console
        tty1
        tty2
        tty3
        tty4
        tty5
        tty6
        ttyS0
        ttyS1
      '';

      # Create /etc/security/limits.conf for pam_limits
      "security/limits.conf".text = ''
        # /etc/security/limits.conf
        #
        #<domain>      <type>  <item>         <value>
        #

        *               soft    core            0
        *               hard    nofile          1048576
        root            hard    nofile          1048576
      '';

      # Create /etc/nologin.txt (message shown when login is disabled)
      "nologin.txt".text = ''
        System is booting up. Login is temporarily disabled.
      '';
    };

    # Add linux-pam package for PAM libraries
    environment.systemPackages = [ pkgs.linux-pam ];
  };
}
