# Adios port of ekaos/modules/security/pam.nix.
# TODO(adios-cutover) notes below mark semantics changed in translation.
{ types, pkgs, ... }:

{
  options = {
    services = {
      # TODO(adios-cutover): submodule validation lost (legacy
      # `pamServiceOpts` submodule with name/text/unixAuth/allowNullPassword,
      # including its `config.name = mkDefault name` default).
      type = types.attrsOf types.attrs;
      default = { };
      description = ''
        PAM service configuration.

        Each attribute defines a PAM service configuration file in /etc/pam.d/.
      '';
      example = {
        sshd = {
          unixAuth = true;
        };
      };
    };

    enableShadow = {
      type = types.bool;
      default = true;
      description = "Whether to enable shadow password support.";
    };

    loginLimits = {
      # TODO(adios-cutover): submodule validation lost (legacy list of
      # submodules with domain/type/item/value).
      type = types.listOf types.attrs;
      default = [ ];
      example = [
        {
          domain = "*";
          type = "soft";
          item = "nofile";
          value = 65536;
        }
        {
          domain = "*";
          type = "hard";
          item = "nofile";
          value = 1048576;
        }
      ];
      description = ''
        Resource limits for PAM login sessions.

        Defines /etc/security/limits.conf entries.
      '';
    };
  };

  impl =
    { options, ... }:
    let
      # Generate PAM service file content
      mkPamService =
        service:
        if service.text or null != null then
          service.text
        else
          ''
            # PAM configuration for ${service.name or "unknown"}
            # Generated by ekaos

            # Authentication
            auth      required    pam_env.so
            auth      ${if service.allowNullPassword or false then "sufficient" else "required"}  pam_unix.so ${
              if !(service.allowNullPassword or false) then "nullok" else ""
            }
            auth      required    pam_deny.so

            # Account management
            account   required    pam_unix.so

            # Password management
            password  required    pam_unix.so sha512 shadow

            # Session management
            session   required    pam_unix.so
            session   required    pam_limits.so
            session   optional    pam_systemd.so
          '';

      # Get all PAM services as /etc files
      pamEtcFiles = builtins.listToAttrs (
        builtins.map (
          serviceName:
          let
            service = options.services.${serviceName};
          in
          {
            name = "pam.d/${serviceName}";
            value = {
              text = mkPamService service;
              mode = "0644";
            };
          }
        ) (builtins.attrNames options.services)
      );
    in
    {
      # Define essential PAM services
      security.pam.services = {
        # System login (getty)
        login = {
          text = ''
            # PAM configuration for login
            auth      required    pam_securetty.so
            auth      requisite   pam_nologin.so
            auth      required    pam_env.so
            auth      required    pam_unix.so nullok
            auth      required    pam_deny.so

            account   required    pam_unix.so
            account   required    pam_nologin.so

            password  required    pam_unix.so sha512 shadow

            session   required    pam_unix.so
            session   required    pam_limits.so
            session   optional    pam_systemd.so
            session   optional    pam_lastlog.so
          '';
        };

        # su command
        su = {
          text = ''
            # PAM configuration for su
            auth      sufficient  pam_rootok.so
            auth      required    pam_unix.so nullok
            auth      required    pam_deny.so

            account   required    pam_unix.so

            password  required    pam_unix.so sha512 shadow

            session   required    pam_unix.so
            session   required    pam_limits.so
            session   optional    pam_systemd.so
          '';
        };

        # systemd user sessions
        systemd-user = {
          text = ''
            # PAM configuration for systemd user sessions
            account   required    pam_unix.so

            session   required    pam_unix.so
            session   required    pam_limits.so
            session   optional    pam_systemd.so
          '';
        };

        # other - default/fallback service
        other = {
          text = ''
            # PAM configuration for other (default)
            auth      required    pam_deny.so
            account   required    pam_deny.so
            password  required    pam_deny.so
            session   required    pam_deny.so
          '';
        };
      };

      # Create /etc/pam.d directory and files
      environment.etc = pamEtcFiles // {
        # Create /etc/securetty for pam_securetty
        securetty.text = ''
          # Secure terminals for root login
          console
          tty1
          tty2
          tty3
          tty4
          tty5
          tty6
          ttyS0
          ttyS1
        '';

        # Create /etc/security/limits.conf for pam_limits
        "security/limits.conf".text =
          let
            defaultLimits = [
              {
                domain = "*";
                type = "soft";
                item = "core";
                value = 0;
              }
              {
                domain = "*";
                type = "hard";
                item = "nofile";
                value = 1048576;
              }
              {
                domain = "root";
                type = "hard";
                item = "nofile";
                value = 1048576;
              }
            ];
            allLimits = defaultLimits ++ options.loginLimits;
            formatLimit = l: "${l.domain}\t${l.type}\t${l.item}\t${toString l.value}";
          in
          ''
            # /etc/security/limits.conf
            # Generated by ekaos
            #
            #<domain>      <type>  <item>         <value>
            #
            ${builtins.concatStringsSep "\n" (builtins.map formatLimit allLimits)}
          '';

        # Create /etc/nologin.txt (message shown when login is disabled)
        "nologin.txt".text = ''
          System is booting up. Login is temporarily disabled.
        '';
      };

      # Add linux-pam package for PAM libraries
      environment.systemPackages = [ pkgs.linux-pam ];
    };
}
