# Sudo - Execute commands as another user (typically root)
# Provides privilege escalation for authorized users
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.security.sudo;

  # Generate sudoers file with proper syntax
  sudoersContent = ''
    # Generated by ekaos sudo module
    # This file MUST be edited with the 'visudo' command as root.

    # Host alias specification

    # User alias specification

    # Cmnd alias specification

    # Defaults
    Defaults env_reset
    Defaults mail_badpass
    Defaults secure_path="/run/current-system/sw/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ${optionalString cfg.wheelNeedsPassword "Defaults lecture=always"}

    # Root privileges
    root ALL=(ALL:ALL) ALL

    # Wheel group privileges
    ${
      if cfg.wheelNeedsPassword then "%wheel ALL=(ALL:ALL) ALL" else "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"
    }

    # User-specific rules
    ${concatMapStringsSep "\n" (
      rule:
      "${rule.users} ${rule.hosts}=(${rule.runAs}) ${
        if rule.nopasswd then "NOPASSWD: " else ""
      }${rule.commands}"
    ) cfg.extraRules}

    # Extra configuration
    ${cfg.extraConfig}
  '';

  # Rule type for extra sudo rules
  ruleType = types.submodule {
    options = {
      users = mkOption {
        type = types.str;
        example = "alice";
        description = "User or group (prefix with %) that this rule applies to";
      };

      hosts = mkOption {
        type = types.str;
        default = "ALL";
        description = "Hosts where this rule applies";
      };

      runAs = mkOption {
        type = types.str;
        default = "ALL:ALL";
        description = "Users and groups the command can be run as";
      };

      commands = mkOption {
        type = types.str;
        default = "ALL";
        example = "/bin/systemctl restart nginx";
        description = "Commands that can be executed";
      };

      nopasswd = mkOption {
        type = types.bool;
        default = false;
        description = "Whether password is required";
      };
    };
  };

in

{
  options = {
    security.sudo = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = ''
          Whether to enable the sudo command.

          Sudo allows authorized users to run commands as other users,
          typically as root for system administration tasks.
        '';
      };

      wheelNeedsPassword = mkOption {
        type = types.bool;
        default = true;
        description = ''
          Whether users in the wheel group need to enter their password
          to use sudo.

          When false, wheel group members can use sudo without a password.
          This is convenient but less secure.
        '';
      };

      extraRules = mkOption {
        type = types.listOf ruleType;
        default = [ ];
        example = literalExpression ''
          [
            {
              users = "alice";
              commands = "/bin/systemctl restart nginx";
              nopasswd = true;
            }
            {
              users = "%operators";
              commands = "/usr/bin/docker";
            }
          ]
        '';
        description = ''
          Extra sudo rules to add to sudoers file.

          Each rule specifies which users can run which commands.
        '';
      };

      extraConfig = mkOption {
        type = types.lines;
        default = "";
        example = ''
          Defaults timestamp_timeout=30
          Defaults insults
        '';
        description = ''
          Extra configuration to append to sudoers file.

          See sudoers(5) for available options.
        '';
      };
    };
  };

  config = mkIf cfg.enable {
    # Add sudo to system packages
    environment.systemPackages = [ pkgs.sudo ];

    # Set up security wrapper for sudo (requires setuid)
    security.wrappers.sudo = {
      source = "${pkgs.sudo}/bin/sudo";
      owner = "root";
      group = "root";
      setuid = true;
      permissions = "u+rx,g+x,o+x";
    };

    # Generate sudoers file
    environment.etc."sudoers" = {
      text = sudoersContent;
      mode = "0440"; # sudoers must be 0440
    };

    # Add PAM configuration for sudo
    environment.etc."pam.d/sudo".text = ''
      # PAM configuration for sudo
      auth      include     system-auth
      account   include     system-auth
      password  include     system-auth
      session   optional    pam_keyinit.so revoke
      session   required    pam_limits.so
      session   include     system-auth
    '';

    # Ensure wheel group exists (should be created by users-groups module)
    # but we make it explicit here
    users.groups.wheel = mkDefault {
      gid = 10;
    };

    # Set up sudoers directory for drop-in files
    system.activationScripts.sudo = {
      deps = [ "etc" ];
      text = ''
        # Create sudoers.d directory
        mkdir -p /etc/sudoers.d
        chmod 750 /etc/sudoers.d
      '';
    };
  };
}
