# Adios port of ekaos/modules/config/xdg/mime.nix.
# TODO(adios-cutover) notes below mark semantics changed in translation.
#
# XDG MIME type associations
{ types, pkgs, ... }:

{
  options = {
    mime = {
      options = {
        enable = {
          type = types.bool;
          default = true;
          description = ''
            Whether to install files to support the XDG Shared MIME-info
            and MIME Applications specifications.
          '';
        };

        defaultApplications = {
          type = types.attrsOf (types.either types.string (types.listOf types.string));
          default = { };
          example = {
            "application/pdf" = "firefox.desktop";
            "image/*" = [
              "sxiv.desktop"
              "gimp.desktop"
            ];
          };
          description = ''
            Default applications for given MIME types.
          '';
        };

        addedAssociations = {
          type = types.attrsOf (types.either types.string (types.listOf types.string));
          default = { };
          description = ''
            Additional associations between MIME types and applications.
          '';
        };

        removedAssociations = {
          type = types.attrsOf (types.either types.string (types.listOf types.string));
          default = { };
          description = ''
            Removed associations between MIME types and applications.
          '';
        };
      };
      description = "XDG MIME type association settings.";
    };
  };

  impl =
    { options, ... }:
    let
      optionalString = cond: s: if cond then s else "";

      # Normalize values to lists
      toList = v: if builtins.isList v then v else [ v ];

      # Generate mimeapps.list section
      mkSection =
        name: assocs:
        optionalString (assocs != { }) ''
          [${name}]
          ${builtins.concatStringsSep "\n" (
            builtins.map (mime: "${mime}=${builtins.concatStringsSep ";" (toList assocs.${mime})};") (
              builtins.attrNames assocs
            )
          )}
        '';
    in
    if !options.mime.enable then
      { }
    else
      {
        environment.etc."xdg/mimeapps.list" =
          if
            (
              options.mime.defaultApplications != { }
              || options.mime.addedAssociations != { }
              || options.mime.removedAssociations != { }
            )
          then
            {
              text = ''
                # Generated by ekaos
                ${mkSection "Default Applications" options.mime.defaultApplications}
                ${mkSection "Added Associations" options.mime.addedAssociations}
                ${mkSection "Removed Associations" options.mime.removedAssociations}
              '';
            }
          else
            { };

        environment.systemPackages =
          if (pkgs ? shared-mime-info) then
            [
              pkgs.shared-mime-info
            ]
          else
            [ ];
      };
}
