# XDG MIME type associations
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.xdg.mime;

  # Association type: string or list of strings per MIME type
  associationType = types.attrsOf (types.either types.str (types.listOf types.str));

  # Normalize values to lists
  toList = v: if builtins.isList v then v else [ v ];

  # Generate mimeapps.list section
  mkSection =
    name: assocs:
    optionalString (assocs != { }) ''
      [${name}]
      ${concatStringsSep "\n" (
        mapAttrsToList (mime: apps: "${mime}=${concatStringsSep ";" (toList apps)};") assocs
      )}
    '';

in

{
  options = {
    xdg.mime = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = ''
          Whether to install files to support the XDG Shared MIME-info
          and MIME Applications specifications.
        '';
      };

      defaultApplications = mkOption {
        type = associationType;
        default = { };
        example = {
          "application/pdf" = "firefox.desktop";
          "image/*" = [
            "sxiv.desktop"
            "gimp.desktop"
          ];
        };
        description = ''
          Default applications for given MIME types.
        '';
      };

      addedAssociations = mkOption {
        type = associationType;
        default = { };
        description = ''
          Additional associations between MIME types and applications.
        '';
      };

      removedAssociations = mkOption {
        type = associationType;
        default = { };
        description = ''
          Removed associations between MIME types and applications.
        '';
      };
    };
  };

  config = mkIf cfg.enable {
    environment.etc."xdg/mimeapps.list" =
      mkIf
        (cfg.defaultApplications != { } || cfg.addedAssociations != { } || cfg.removedAssociations != { })
        {
          text = ''
            # Generated by ekaos
            ${mkSection "Default Applications" cfg.defaultApplications}
            ${mkSection "Added Associations" cfg.addedAssociations}
            ${mkSection "Removed Associations" cfg.removedAssociations}
          '';
        };

    environment.systemPackages = mkIf (pkgs ? shared-mime-info) [
      pkgs.shared-mime-info
    ];
  };
}
